### ISSUE TITLE
Position breaks stockfish15

### ISSUE THREAD

**Issue by kingmaneuvers** [official-stockfish/Stockfish#4153] opened 2022-09-04 00:54 UTC
Position link: https://lichess.org/58UgVrV0#92 and some ongoing moves, stockfish fails to search above depth10 and halts(only had this issue 1 out of 400k+ fen positions, extremely rare).
Replicate issue with the latest build on the official site and multipv set to 10, fen search.
Did not try to diagnose with source code, many people are more experienced than I am :), hopefully this issue gets resolved.

**Comment by dubslow** [comment] 2022-09-04 03:36
fen `8/R2Kp1k1/3p1b2/6p1/7p/6r1/8/1R6 w - - 0 47`

**Comment by dubslow** [comment] 2022-09-04 03:42
cannot reproduce with:

```git checkout master
make profile-build
./stockfish 
Stockfish 030922 by the Stockfish developers (see AUTHORS file)
setoption name MultiPV value 10
position fen 8/R2Kp1k1/3p1b2/6p1/7p/6r1/8/1R6 w - - 0 47
go depth 20
```

do threads/hashsize matter for reproducibility?

**Comment by vondele** [comment] 2022-09-04 05:31
reproduces with sf15, however, this probably is a duplicate of https://github.com/official-stockfish/Stockfish/issues/3911 

I'll close this here.

**Closed by vondele** 2022-09-04 05:31 UTC
