### ISSUE TITLE
Compiling warning with gcc 13

### ISSUE THREAD

**Issue by peregrineshahin** [official-stockfish/Stockfish#5031] opened 2024-02-04 09:04 UTC
### Describe the issue

Compiling stockfish with `make -j build EXTRACXXFLAGS="-g3 -fsanitize=undefined -fsanitize=address" COMPCXX=g++-13` gives this warning
```
In member function ‘load’,
    inlined from ‘__conv_op ’ at /usr/include/c++/13/atomic:87:26,
    inlined from ‘_ZN9Stockfish6Search6Worker15start_searchingEv.part.0’ at search.cpp:167:63:
/usr/include/c++/13/bits/atomic_base.h:505:31: warning: ‘__atomic_load_1’ writing 1 byte into a region of size 0 overflows the destination [-Wstringop-overflow=]
  505 |         return __atomic_load_n(&_M_i, int(__m));
      |                               ^
In member function ‘_ZN9Stockfish6Search6Worker15start_searchingEv.part.0’:
lto1: note: destination object is likely at address zero
```

### Expected behavior

No warning for overflows

### Steps to reproduce

make -j build EXTRACXXFLAGS="-g3 -fsanitize=undefined -fsanitize=address" COMPCXX=g++-13

### Anything else?

Culprit commit is https://github.com/official-stockfish/Stockfish/commit/a10791095150bf7c020b92be0f55566fe34e9bf2
before it there is no warning.

### Operating system

Linux

### Stockfish version

latest

**Comment by Disservin** [comment] 2024-02-04 11:32
I think gcc doesnt realize that `main_manager()` at that point is only called from the "mainthread" and thus will yield a correct main_manager. This fixes the warning for me.

```diff
➜  src git:(master) ✗ git --no-pager diff
diff --git a/src/search.cpp b/src/search.cpp
index e57f2557..5e70f35e 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -26,8 +26,8 @@
 #include <cstdlib>
 #include <initializer_list>
 #include <iostream>
-#include <utility>
 #include <sstream>
+#include <utility>
 
 #include "evaluate.h"
 #include "misc.h"
@@ -137,14 +137,16 @@ Search::Worker::Worker(SharedState&                    sharedState,
 }
 
 void Search::Worker::start_searching() {
+    SearchManager* mainThread = (thread_idx == 0 ? main_manager() : nullptr);
+
     // Non-main threads go directly to iterative_deepening()
-    if (!is_mainthread())
+    if (!mainThread)
     {
         iterative_deepening();
         return;
     }
 
-    main_manager()->tm.init(limits, rootPos.side_to_move(), rootPos.game_ply(), options);
+    mainThread->tm.init(limits, rootPos.side_to_move(), rootPos.game_ply(), options);
     tt.new_search();
 
     if (rootMoves.empty())
@@ -164,7 +166,7 @@ void Search::Worker::start_searching() {
     // the UCI protocol states that we shouldn't print the best move before the
     // GUI sends a "stop" or "ponderhit" command. We therefore simply wait here
     // until the GUI sends one of those commands.
-    while (!threads.stop && (main_manager()->ponder || limits.infinite))
+    while (!threads.stop && (mainThread->ponder || limits.infinite))
     {}  // Busy wait for a stop or a ponder reset
 
     // Stop the threads if not already stopped (also raise the stop if
@@ -177,8 +179,8 @@ void Search::Worker::start_searching() {
     // When playing in 'nodes as time' mode, subtract the searched nodes from
     // the available ones before exiting.
     if (limits.npmsec)
-        main_manager()->tm.advance_nodes_time(limits.inc[rootPos.side_to_move()]
-                                              - threads.nodes_searched());
+        mainThread->tm.advance_nodes_time(limits.inc[rootPos.side_to_move()]
+                                          - threads.nodes_searched());
 
     Worker* bestThread = this;
     Skill   skill =
@@ -188,12 +190,12 @@ void Search::Worker::start_searching() {
         && rootMoves[0].pv[0] != Move::none())
         bestThread = threads.get_best_thread()->worker.get();
 
-    main_manager()->bestPreviousScore        = bestThread->rootMoves[0].score;
-    main_manager()->bestPreviousAverageScore = bestThread->rootMoves[0].averageScore;
+    mainThread->bestPreviousScore        = bestThread->rootMoves[0].score;
+    mainThread->bestPreviousAverageScore = bestThread->rootMoves[0].averageScore;
 
     // Send again PV info if we have a new best thread
     if (bestThread != this)
-        sync_cout << main_manager()->pv(*bestThread, threads, tt, bestThread->completedDepth)
+        sync_cout << mainThread->pv(*bestThread, threads, tt, bestThread->completedDepth)
                   << sync_endl;
 
     sync_cout << "bestmove " << UCI::move(bestThread->rootMoves[0].pv[0], rootPos.is_chess960());
```

**Comment by peregrineshahin** [comment] 2024-02-04 14:46
> I think gcc doesnt realize that main_manager() at that point is only called from the "mainthread" and thus will yield a correct main_manager. This fixes the warning for me.
Hmm this suggests that the call to `main_manager()` is somehow not attainable at all compile time...

**Comment by Disservin** [comment] 2024-02-04 15:18
```diff
➜  src git:(master) ✗ git --no-pager diff
diff --git a/src/search.cpp b/src/search.cpp
index e57f2557..07b8b88a 100644
--- a/src/search.cpp
+++ b/src/search.cpp
@@ -164,7 +164,8 @@ void Search::Worker::start_searching() {
     // the UCI protocol states that we shouldn't print the best move before the
     // GUI sends a "stop" or "ponderhit" command. We therefore simply wait here
     // until the GUI sends one of those commands.
-    while (!threads.stop && (main_manager()->ponder || limits.infinite))
+    auto x = main_manager();
+    while (!threads.stop && (x->ponder || limits.infinite))
     {}  // Busy wait for a stop or a ponder reset
 
     // Stop the threads if not already stopped (also raise the stop if
```
this also fixes it :p

**Comment by peregrineshahin** [comment] 2024-02-04 15:32
I can confirm that the short-circuiting somehow is related, this also fixes it
```diff
    // the UCI protocol states that we shouldn't print the best move before the
    // GUI sends a "stop" or "ponderhit" command. We therefore simply wait here
    // until the GUI sends one of those commands.
-   while (!threads.stop && (main_manager()->ponder || limits.infinite))
+  while ((main_manager()->ponder || limits.infinite) && !threads.stop)
    {}  // Busy wait for a stop or a ponder reset
```

**Comment by Disservin** [comment] 2024-02-04 16:48
Should be a gcc regression here's a minimal reproduction
```cpp
#include <atomic>
#include <memory>
#include <thread>

class Base {
   public:
    virtual ~Base() {}
};

class Derived : public Base {
   public:
    std::atomic_bool ponder = true;
};

class Foo {
   public:
    Foo() { manager = std::unique_ptr<Base>(new Derived()); }

    Derived* main_manager() const { return static_cast<Derived*>(manager.get()); }

    void foo() {
        while (main_manager()->ponder) {
        }
    }

   private:
    std::unique_ptr<Base> manager;
};

int main() {
    Foo f = Foo();
    std::thread t1(&Foo::foo, &f);

    f.main_manager()->ponder = false;

    t1.join();
}

// -O3 -std=c++17 -Wall -fsanitize=undefined -fsanitize=address
```

**Comment by Disservin** [comment] 2024-02-10 08:36
I think we can close this for now since it only happens when used together with sanitizer flags and also is a false positive. GCC report here https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113775

**Closed by Disservin** 2024-02-10 08:36 UTC
