### ISSUE TITLE
Wrong bench on some archs for some of the new nets?

### ISSUE THREAD

**Issue by snicolet** [official-stockfish/Stockfish#3466] opened 2021-05-14 12:58 UTC
Let's move all the discussion here

**Comment by Sopel97** [comment] 2021-05-14 13:19
Seems that replacing add with adds masks the issue for these nets. The problem is due to overflow for large weights, which are normally handled by the specialized path. However it's unclear whether this fixes it for all possible nets.

https://github.com/Sopel97/Stockfish/commit/35741a545ba52672b830621e0d658d3830e7315a

**Comment by vondele** [comment] 2021-05-15 15:08
just did a test with that patch applied https://tests.stockfishchess.org/tests/view/609fdbb15085663412d09094 looks consistent with the one without the patch. One way to deal with this could also be restricting the weights in the trainer further so this can't happen... given the fact that most nets don't need it, probably can be done without reducing the strength.

**Comment by Sopel97** [comment] 2021-05-15 17:38
For which net does it not fix the behaviour? I only tested with nn-bb3b6489d21f.nnue

**Comment by vondele** [comment] 2021-05-15 17:40
I haven't seen such a net, but just added that suggestion that it could be addressed in training, if needed. Ideally it is not needed.

**Comment by snicolet** [comment] 2021-05-17 08:56
Can't we write assertions in the evaluation code to catch more of these saturation problems?

**Comment by vondele** [comment] 2021-05-17 08:59
IMO, the saturation is not a problem per se, just the implementation should be consistent across architectures, and ideally between player and trainer.

**Comment by snicolet** [comment] 2021-05-17 09:14
Maybe we could ask the regular contributors to this part of the code to have a small round of review from time to time? 
@mstembera , @MaximMolchanov , @Fanael and @syzygy1 are obvious names that come to mind, but maybe there are others (can't remember)

**Comment by Sopel97** [comment] 2021-05-17 10:40
the net `nn-ac7637a567be.nnue` seems to exhibit issues even when applying the patch above. For these nets reverting https://github.com/snicolet/Stockfish/commit/7e51d283b4f55e2d468cb596161565351fd7f097 might be needed, but at that point it might be a high enough performance hit for some nets that they would be virtually unusable.

**Comment by vondele** [comment] 2021-05-17 11:36
let me check as well, I didn't see any issues for nn-ac7637a567be.nnue so far, but I might need to do a deeper bench.

**Comment by vondele** [comment] 2021-05-17 12:39
i've checked this with patch, and all I've looked at so far look fine.

**Closed** 2021-06-02 05:48 UTC
