### ISSUE TITLE
How to build stockfish for android?

### ISSUE THREAD

**Issue by anonymous7002** [official-stockfish/Stockfish#2506] opened 2020-01-21 13:18 UTC
I tried on Windows with MSYS2 MinGW64: make -j profile-build ARCH=arm64v8 COMP=mingw
Apparently, building Stockfish does not allow arm64v8, although compiled Android version downloaded from the home page has arm64v8 version with it.
I tried armv7, but that produced normal Windows binaries.

**Comment by snicolet** [comment] 2020-01-23 18:22
Looks like a duplicate of https://github.com/official-stockfish/Stockfish/issues/2380. Closing.

**Closed by snicolet** 2020-01-23 18:22 UTC
