### ISSUE TITLE
No Windows bmi2/AVX2 compiles for abrok with latest SF versions?

### ISSUE THREAD

**Issue by ssj100** [official-stockfish/Stockfish#3216] opened 2020-11-03 05:22 UTC
As title states, has been the case since the patch called: "Optimize affine transform for SSSE3 and higher targets.":
https://abrok.eu/stockfish/

Seems that patch "broke" the automatic compilation for Windows bmi2 and AVX2?

**Comment by locutus2** [comment] 2020-11-03 06:37
I can confirm the problems on my laptop. I get at the current master a segmentation fault on bench, After reverting the commit "Optimize affine transform for SSSE3 and higher targets." it works again:

Windows 10
Intel Core I5-8250U

Compiled by g++ (GNUC) 9.2.0 on MinGW64
Compilation settings include:  64bit BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 9.2.0

make clean
make build ARCH=x86-64-bmi2 COMP=mingw

./stockfish bench >/dev/null

Position: 1/47 (rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1)

Position: 2/47 (r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 10)
Segmentation fault

**Comment by vondele** [comment] 2020-11-03 07:05
@Sopel97 can you have a look? I suspect it might need an extended version of the workaround we have in place already to use unaligned version of the intrinsics on windows for older gcc compilers (see https://github.com/official-stockfish/Stockfish/blob/a260c9a8a24a2630a900efc3821000c3481b0c5d/src/nnue/nnue_common.h#L59-L67)

**Comment by vondele** [comment] 2020-11-03 07:18
I can reproduce this crash using gcc 7.3 (mingw cross under linux), but it works fine with gcc 9.3

**Comment by vondele** [comment] 2020-11-03 07:36
@locutus2 you say you're using gcc 9.2... so that is actually suggesting the above workaround would actually be disabled, and it might be an issue that affects also more recent gcc.

**Comment by locutus2** [comment] 2020-11-03 07:45
@vondele 
Yes, i have verified by using g++ --version:
g++.exe (Rev2, Built by MSYS2 project) 9.2.0

**Comment by Sopel97** [comment] 2020-11-03 07:57
Every access should be aligned so this is something else.

**Comment by vondele** [comment] 2020-11-03 08:01
It could be something else, but I think the problem is that on (older?) windows gcc these alignment guarantees are somehow violated. (at least that's my interpretation of things like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54412#c25)

**Comment by Sopel97** [comment] 2020-11-03 08:20
Could be https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89357
which was fixed in gcc 9.3
https://github.com/gcc-mirror/gcc/blob/67d2ec77af1fc7c49a2333656ff87013e9f9dd1d/gcc/config/i386/cygming.h#L272

**Comment by Sopel97** [comment] 2020-11-03 08:26
54412 is still present in trunk so unlikely

**Comment by Sopel97** [comment] 2020-11-03 08:28
can I get a hand on a problematic binary? I don't have older gccs

**Comment by vondele** [comment] 2020-11-03 08:34
Under wine I get: wine: Unhandled page fault at address 0x44c520 (thread 0021), starting debugger... 
but can't use the debugger. I'll upload the binary.

```
Position: 2/47 (r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 10)
info string NNUE evaluation using nn-cb26f10b1fd9.nnue enabled
wine: Unhandled page fault at address 0x44c520 (thread 0021), starting debugger...
0026:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0026:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0026:fixme:dbghelp:elf_search_auxv can't find symbol in module
0026:fixme:dbghelp:elf_search_auxv can't find symbol in module
0026:fixme:dbghelp:elf_search_auxv can't find symbol in module
0026:fixme:dbghelp:elf_search_auxv can't find symbol in module
0026:fixme:dbghelp:elf_search_auxv can't find symbol in module
0026:fixme:dbghelp:elf_search_auxv can't find symbol in module
Unhandled exception: page fault in 64-bit code (0x000000000044c520).
0026:fixme:dbghelp:elf_search_auxv can't find symbol in module
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 15
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 14
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 13
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 12
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 11
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 10
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 9
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 8
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 7
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 6
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 15
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 14
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 13
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 12
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 11
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 10
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 9
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 8
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 7
0026:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 6
Register dump:
 rip:000000000044c520 rsp:0000000003f37a50 rbp:0000000005760000 eflags:00010246 (  R- --  I  Z- -P- )
 rax:0000000000000000 rbx:0000000003f37c70 rcx:0000000002669940 rdx:0000000002669540
 rsi:0000000003f37bf0 rdi:0000000003f3b900  r8:0000000002669740  r9:0000000002669340 r10:0000000002669280
 r11:0000000000000000 r12:00000000027100e0 r13:0000000000000000 r14:0000000002710980 r15:0000000003f3b840
Stack dump:
0x0000000003f37a50:  0000000000000000 0000000000000000
0x0000000003f37a60:  0000000000000000 0000000000000000
0x0000000003f37a70:  0000000003f37c70 0000000000000000
0x0000000003f37a80:  0000000000000000 0000000000000000
0x0000000003f37a90:  0000000003f3b840 0000000000000000
0x0000000003f37aa0:  0000000000000000 0000000000000000
0x0000000003f37ab0:  00000000000007fb 0000000000000000
0x0000000003f37ac0:  0000000000000000 0000000000000000
0x0000000003f37ad0:  0000000000000000 0000000000000000
0x0000000003f37ae0:  0000000000000000 0000000000000000
0x0000000003f37af0:  0000000000000000 0000000000000000
0x0000000003f37b00:  0000000000000000 0000000000000000
Backtrace:
=>0 0x000000000044c520 in stockfish (+0x4c520) (0x0000000005760000)
0x000000000044c520: ldsl	%ebp,%edi
Modules:
Module	Address					Debug info	Name (22 modules)
PE	          400000-         25f2000	Dwarf           stockfish
ELF	        7b400000-        7b80d000	Deferred        kernel32<elf>
  \-PE	        7b420000-        7b80d000	\               kernel32
ELF	        7bc00000-        7bd16000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bd16000	\               ntdll
ELF	        7c000000-        7c004000	Deferred        <wine-loader>
ELF	    7fa0f43cc000-    7fa0f45f6000	Deferred        libtinfo.so.5
ELF	    7fa0f45f6000-    7fa0f4819000	Deferred        libncurses.so.5
ELF	    7fa0f4819000-    7fa0f4ae7000	Deferred        msvcrt<elf>
  \-PE	    7fa0f4840000-    7fa0f4ae7000	\               msvcrt
ELF	    7fa0f4be7000-    7fa0f4e77000	Deferred        advapi32<elf>
  \-PE	    7fa0f4c00000-    7fa0f4e77000	\               advapi32
ELF	    7fa0f4e77000-    7fa0f5089000	Deferred        libnss_files.so.2
ELF	    7fa0f5089000-    7fa0f52a3000	Deferred        libnsl.so.1
ELF	    7fa0f52a3000-    7fa0f54af000	Deferred        libnss_nis.so.2
ELF	    7fa0f54af000-    7fa0f56b9000	Deferred        libnss_compat.so.2
ELF	    7fa0f5ac7000-    7fa0f5cdf000	Deferred        libgcc_s.so.1
ELF	    7fa0f5cdf000-    7fa0f607d000	Deferred        libm.so.6
ELF	    7fa0f607d000-    7fa0f6281000	Deferred        libdl.so.2
ELF	    7fa0f6281000-    7fa0f6672000	Deferred        libc.so.6
ELF	    7fa0f6672000-    7fa0f6891000	Deferred        libpthread.so.0
ELF	    7fa0f6c36000-    7fa0f6e62000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000015    0
	00000014    0
	00000013    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	00000017    0
	00000016    0
	00000012    0
00000018 explorer.exe
	0000001d    0
	0000001c    0
	00000019    0
0000001a (D) Z:\root\Stockfish\src\stockfish.exe
	00000021    0 <==
	0000001b    0
System information:
    Wine build: wine-3.0 (Ubuntu 3.0-1ubuntu1)
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 5.4.0-52-generic
```

**Comment by vondele** [comment] 2020-11-03 08:35
[stockfish.exe.gz](https://github.com/official-stockfish/Stockfish/files/5480039/stockfish.exe.gz)
that should be a crashing exe (cross from linux to windows, built in a container with an old linux :-0)

**Comment by locutus2** [comment] 2020-11-03 08:43
Here my crashing windows compile with gcc 9.2:
https://drive.google.com/file/d/15n3ufEbHQ-DyUv3RIj0oi5eEQy1ws1Rx/view?usp=sharing

**Comment by Sopel97** [comment] 2020-11-03 08:59
The crash happens on `const __m256i in = input_vector[j];`, line 343 of affine transform

```
XDIS 44c476: AVX2      AVX2       C4E3FD00C9D8             vpermq ymm1, ymm1, 0xd8
XDIS 44c47c: DATAXFER  AVX        C5F8298C24E0030000       vmovaps xmmword ptr [rsp+0x3e0], xmm1
XDIS 44c485: AVX2      AVX2       C4E37D398C24F003000001   vextracti128 xmmword ptr [rsp+0x3f0], ymm1, 0x1
XDIS 44c490: DATAXFER  AVX        C5FA6F88C0010000         vmovdqu xmm1, xmmword ptr [rax+0x1c0]
XDIS 44c498: DATAXFER  AVX        C5FA6F90E0010000         vmovdqu xmm2, xmmword ptr [rax+0x1e0]
XDIS 44c4a0: AVX2      AVX2       C4E3753888D001000001     vinserti128 ymm1, ymm1, xmmword ptr [rax+0x1d0], 0x1
XDIS 44c4aa: AVX2      AVX2       C4E36D3890F001000001     vinserti128 ymm2, ymm2, xmmword ptr [rax+0x1f0], 0x1
XDIS 44c4b4: AVX2      AVX2       C5F563CA                 vpacksswb ymm1, ymm1, ymm2
XDIS 44c4b8: AVX2      AVX2       C4E2753CC0               vpmaxsb ymm0, ymm1, ymm0
XDIS 44c4bd: AVX2      AVX2       C4E3FD00C0D8             vpermq ymm0, ymm0, 0xd8
XDIS 44c4c3: DATAXFER  AVX        C5F829842400040000       vmovaps xmmword ptr [rsp+0x400], xmm0
XDIS 44c4cc: AVX2      AVX2       C4E37D3984241004000001   vextracti128 xmmword ptr [rsp+0x410], ymm0, 0x1
XDIS 44c4d7: DATAXFER  BASE       4C8B15426E6301           mov r10, qword ptr [rip+0x1636e42]
XDIS 44c4de: DATAXFER  AVX        C5FD6F0D5A804D01         vmovdqa ymm1, ymmword ptr [rip+0x14d805a]
XDIS 44c4e6: MISC      BASE       498D92C0020000           lea rdx, ptr [r10+0x2c0]
XDIS 44c4ed: WIDENOP   BASE       0F1F00                   nop dword ptr [rax], eax
XDIS 44c4f0: LOGICAL   AVX        C5C9EFF6                 vpxor xmm6, xmm6, xmm6
XDIS 44c4f4: DATAXFER  AVX        C481796F6C1A40           vmovdqa xmm5, xmmword ptr [r10+r11*1+0x40]
XDIS 44c4fb: MISC      BASE       4C8D8A00FEFFFF           lea r9, ptr [rdx-0x200]
XDIS 44c502: MISC      BASE       4C8D8200020000           lea r8, ptr [rdx+0x200]
XDIS 44c509: MISC      BASE       488D8A00040000           lea rcx, ptr [rdx+0x400]
XDIS 44c510: LOGICAL   BASE       31C0                     xor eax, eax
XDIS 44c512: DATAXFER  AVX        C57D6FC6                 vmovdqa ymm8, ymm6
XDIS 44c516: DATAXFER  AVX        C57D6FCE                 vmovdqa ymm9, ymm6
XDIS 44c51a: DATAXFER  AVX        C5FD6FFE                 vmovdqa ymm7, ymm6
XDIS 44c51e: NOP       BASE       6690                     data16 nop
XDIS 44c520: DATAXFER  AVX        C5FD6F0403               vmovdqa ymm0, ymmword ptr [rbx+rax*1] <<<<<<<<<<<<<<<<<<<<<
XDIS 44c525: AVX2      AVX2       C4C27D041C01             vpmaddubsw ymm3, ymm0, ymmword ptr [r9+rax*1]
XDIS 44c52b: AVX2      AVX2       C4E27D041402             vpmaddubsw ymm2, ymm0, ymmword ptr [rdx+rax*1]
XDIS 44c531: AVX2      AVX2       C5E5F5D9                 vpmaddwd ymm3, ymm3, ymm1
XDIS 44c535: AVX2      AVX2       C5EDF5D1                 vpmaddwd ymm2, ymm2, ymm1
XDIS 44c539: AVX2      AVX2       C5E5FEE7                 vpaddd ymm4, ymm3, ymm7
XDIS 44c53d: AVX2      AVX2       C4C16DFED9               vpaddd ymm3, ymm2, ymm9
XDIS 44c542: AVX2      AVX2       C4C27D041400             vpmaddubsw ymm2, ymm0, ymmword ptr [r8+rax*1]
XDIS 44c548: AVX2      AVX2       C4E27D040401             vpmaddubsw ymm0, ymm0, ymmword ptr [rcx+rax*1]
XDIS 44c54e: BINARY    BASE       4883C020                 add rax, 0x20
XDIS 44c552: BINARY    BASE       483D00020000             cmp rax, 0x200
XDIS 44c558: AVX2      AVX2       C5EDF5D1                 vpmaddwd ymm2, ymm2, ymm1
XDIS 44c55c: AVX2      AVX2       C5FDF5C1                 vpmaddwd ymm0, ymm0, ymm1
XDIS 44c560: AVX2      AVX2       C4C16DFED0               vpaddd ymm2, ymm2, ymm8
XDIS 44c565: AVX2      AVX2       C5FDFEC6                 vpaddd ymm0, ymm0, ymm6
XDIS 44c569: DATAXFER  AVX        C5FD6FFC                 vmovdqa ymm7, ymm4
XDIS 44c56d: DATAXFER  AVX        C57D6FCB                 vmovdqa ymm9, ymm3
XDIS 44c571: DATAXFER  AVX        C57D6FC2                 vmovdqa ymm8, ymm2
XDIS 44c575: DATAXFER  AVX        C5FD6FF0                 vmovdqa ymm6, ymm0
XDIS 44c579: COND_BR   BASE       75A5                     jnz 0x44c520
XDIS 44c57b: AVX2      AVX2       C4E26D02C0               vphaddd ymm0, ymm2, ymm0
XDIS 44c580: AVX2      AVX2       C4E25D02DB               vphaddd ymm3, ymm4, ymm3
XDIS 44c585: AVX2      AVX2       C4E26502C0               vphaddd ymm0, ymm3, ymm0
XDIS 44c58a: DATAXFER  AVX        C5F96FD0                 vmovdqa xmm2, xmm0
```

**Comment by Sopel97** [comment] 2020-11-03 09:05
alternatively you could try 
```

    char buffer[Network::kBufferSize + kCacheLineSize];
    uintptr_t buf = reinterpret_cast<uintptr_t>(&buffer);
    buf = (buf + 63) / 64 * 64;
    char* bufptr = reinterpret_cast<char*>(buf);
    const auto output = network->Propagate(transformed_features, bufptr);
```
in evaluate_nnue.cpp

**Comment by vondele** [comment] 2020-11-03 09:16
tried:
```diff
diff --git a/src/nnue/evaluate_nnue.cpp b/src/nnue/evaluate_nnue.cpp
index b5dcd992..e4b34915 100644
--- a/src/nnue/evaluate_nnue.cpp
+++ b/src/nnue/evaluate_nnue.cpp
@@ -129,8 +129,14 @@ namespace Eval::NNUE {
     alignas(kCacheLineSize) TransformedFeatureType
         transformed_features[FeatureTransformer::kBufferSize];
     feature_transformer->Transform(pos, transformed_features);
-    alignas(kCacheLineSize) char buffer[Network::kBufferSize];
-    const auto output = network->Propagate(transformed_features, buffer);
+//    alignas(kCacheLineSize) char buffer[Network::kBufferSize];
+//    const auto output = network->Propagate(transformed_features, buffer);
+
+    char buffer[Network::kBufferSize + kCacheLineSize];
+    uintptr_t buf = reinterpret_cast<uintptr_t>(&buffer);
+    buf = (buf + 63) / 64 * 64;
+    char* bufptr = reinterpret_cast<char*>(buf);
+    const auto output = network->Propagate(transformed_features, bufptr);
 
     return static_cast<Value>(output[0] / FV_SCALE);
   }
```
but it still crashes for me.

**Comment by Sopel97** [comment] 2020-11-03 09:20
so I guess one could try going back to `const __m256i in = _mm256_loadu_si256(&input_vector[j]);` and see if there are other problematic places

**Comment by vondele** [comment] 2020-11-03 09:27
that fixes it for me (also reverting the earlier change to buf).

**Comment by Sopel97** [comment] 2020-11-03 09:41
now that I think about it, https://github.com/official-stockfish/Stockfish/issues/3216#issuecomment-720991171 should have worked if applied to `transformed_features[]` too.

**Comment by vondele** [comment] 2020-11-03 09:45
can't we use the `_mm256_loadA_si256` macro that we defined in the earlier workaround? 
Probably we need to enable the workaround for gcc <=9.2

**Comment by Sopel97** [comment] 2020-11-03 09:51
That works too, but personally I would prefer just manually aligning the stack arrays as it would fix the problem at its core and without performance penalties.

**Comment by vondele** [comment] 2020-11-03 09:56
I'm quite open to either solution, I'm not sure what is best. This is a windows specific issue with gcc, so having it confined to that case would make some sense. If, however, we could get fully rid of the workaround by using the manual alignment that would be beficial (I think that makes that abrok binaries something like 10% slower than they should be).

Won't be able to do further testing till tonight however.

**Comment by Sopel97** [comment] 2020-11-03 09:57
I'll make a PR with a fix

**Comment by syzygy1** [comment] 2020-11-03 19:12
I think manually aligning makes the generated code a bit less efficient. But probably still a win on compilers that otherwise need unaligned load/store instructions.

**Comment by Sopel97** [comment] 2020-11-03 20:34
Manually aligning the arrays generates almost the same code

**Comment by syzygy1** [comment] 2020-11-03 20:53
I would think the local arrays cannot be addressed via %rsp anymore? And gcc seems to have more difficulty holding the local variables in regsters. At least in Cfish I noticed enough degradation of the compiled code that I made the alignment conditional on the compiler being used. If your solution doesn't have this problem then that would be great.

**Comment by amchess** [comment] 2020-11-03 21:00
Me too I have the problem: windows build, BMI2 and 7.3.0 compiler version.
Do you think we can have the bugs correction?

**Comment by Sopel97** [comment] 2020-11-03 21:15
> I would think the local arrays cannot be addressed via %rsp anymore?
oof, I have not considered that. May be the case.

**Comment by Zerbinati** [comment] 2020-11-03 22:17
No problem compiled by g ++ (GNUC) 10.1.0 on MinGW64 (bmi2+avx2+avx512)

**Comment by Sopel97** [comment] 2020-11-03 22:18
We know it's only an issue with GCC <= 9.2 with _WIN32 defined

**Comment by Zerbinati** [comment] 2020-11-03 22:21
Also with other compilers, such as GCC 7.30

**Closed** 2020-11-04 18:55 UTC
