### ISSUE TITLE
Perft generates wrong moves, and sometimes duplicate entries

### ISSUE THREAD

**Issue by amanjpro** [official-stockfish/Stockfish#3343] opened 2021-02-09 05:26 UTC
I tried perft, and noticed that it generates illegal moves:

Actually I found another (serious bug):

```
position fen r2k3r/p1ppqpb1/bn2pQp1/3PN3/1p2P3/2N4p/PPPBBPPP/R3K1R1 b Qkq - 0 1
go perft 1
b4b3: 1
g6g5: 1
c7c6: 1
d7d6: 1
c7c5: 1
h3g2: 1
e6d5: 1
b4c3: 1
b6a4: 1
b6c4: 1
b6d5: 1
b6c8: 1
g7f6: 1
g7h6: 1
g7f8: 1
a6e2: 1
a6d3: 1
a6c4: 1
a6b5: 1
a6b7: 1
a6c8: 1
a8b8: 1
a8c8: 1
h8h4: 1
h8h5: 1
h8h6: 1
h8h7: 1
h8e8: 1
h8f8: 1
h8g8: 1
d8c8: 1
d8g8: 1
e7f6: 1
d8e8: 1
d8c8: 1

Nodes searched: 35


```

d8g8 is absolutely wrong!
<img width="508" alt="Screen Shot 2021-02-09 at 1 04 42 AM" src="https://user-images.githubusercontent.com/3101099/107322613-ccd10b00-6a72-11eb-84f4-5f022065bd40.png">

And sometimes its entries are duplicated, an example:

```
Stockfish 12 by the Stockfish developers (see AUTHORS file)
position fen r2k4/p1ppqpb1/1n2p1p1/1b1PN3/Pp2P3/2N2Q2/1PPBBPpr/1R2K2R b Kq - 0 1
go perft 1
b4b3: 1
g6g5: 1
a7a6: 1
c7c6: 1
d7d6: 1
f7f6: 1
a7a5: 1
c7c5: 1
f7f5: 1
g2h1q: 1
g2h1r: 1
g2h1b: 1
g2h1n: 1
g2g1q: 1
g2g1r: 1
g2g1b: 1
g2g1n: 1
e6d5: 1
b4c3: 1
b6a4: 1
b6c4: 1
b6d5: 1
b6c8: 1
g7e5: 1
g7f6: 1
g7h6: 1
g7f8: 1
g7h8: 1
b5e2: 1
b5d3: 1
b5a4: 1
b5c4: 1
b5a6: 1
b5c6: 1
a8b8: 1
a8c8: 1
h2h1: 1
h2h3: 1
h2h4: 1
h2h5: 1
h2h6: 1
h2h7: 1
h2h8: 1
e7h4: 1
e7c5: 1
e7g5: 1
e7d6: 1
e7f6: 1
e7e8: 1
e7f8: 1
d8c8: 1
d8e8: 1
d8c8: 1

Nodes searched: 53
```

Look at the very end:
```
...
d8c8: 1
d8e8: 1
d8c8: 1
```

**Comment by vondele** [comment] 2021-02-09 06:04
I can confirm this even for older SF (8, 9, 10).

**Comment by amanjpro** [comment] 2021-02-09 06:04
Actually I found another (serious bug):

```
position fen r2k3r/p1ppqpb1/bn2pQp1/3PN3/1p2P3/2N4p/PPPBBPPP/R3K1R1 b Qkq - 0 1
go perft 1
b4b3: 1
g6g5: 1
c7c6: 1
d7d6: 1
c7c5: 1
h3g2: 1
e6d5: 1
b4c3: 1
b6a4: 1
b6c4: 1
b6d5: 1
b6c8: 1
g7f6: 1
g7h6: 1
g7f8: 1
a6e2: 1
a6d3: 1
a6c4: 1
a6b5: 1
a6b7: 1
a6c8: 1
a8b8: 1
a8c8: 1
h8h4: 1
h8h5: 1
h8h6: 1
h8h7: 1
h8e8: 1
h8f8: 1
h8g8: 1
d8c8: 1
d8g8: 1
e7f6: 1
d8e8: 1
d8c8: 1

Nodes searched: 35


```

d8g8 is absolutely wrong!
<img width="508" alt="Screen Shot 2021-02-09 at 1 04 42 AM" src="https://user-images.githubusercontent.com/3101099/107322613-ccd10b00-6a72-11eb-84f4-5f022065bd40.png">

**Comment by ddobbelaere** [comment] 2021-02-09 07:16
Both FENs are invalid (illegal castling rights). For the first FEN, it can at most be "Q" (Qkq given). Note that d8g8 indicates black castles short (k), i.e. SF is confused by this.

In the second FEN, no castling is possible (Kq given).

**Comment by vondele** [comment] 2021-02-09 10:06
closing as solved, we don't deal with illegal fens

**Closed by vondele** 2021-02-09 10:06 UTC

**Comment by amanjpro** [comment] 2021-02-09 12:15
Cool. They both disappeared with the valid FEN. The first one is interesting though. It tells me that Stockfish doesn't consider the origin square of the king

**Comment by BM123499** [comment] 2021-02-09 12:17
It does not. Because it also support FRC (chess960).
