### ISSUE TITLE
Non-standard-chess position gives wrong eval up to 1 move before it's over

### ISSUE THREAD

**Issue by danispringer** [official-stockfish/Stockfish#5702] opened 2024-11-28 04:18 UTC
### Describe the issue

Using this non-standard position:
https://lichess.org/analysis/B1B1B3/1B1B1Bk1/B1B1B3/1B1B1BKP/B1B1B2P/1B1B1B1P/B1B1B1BP/1B1B1B2_b_-_-_0_1

Eval (on lichess, using SF17) says it's winning (+60), letting SF play out the many moves it takes to slowly push all the pawns, keeps saying it's winning, even when the last pawn is pushed and promoted with h8=Q+, *it still says it's winning, even when the queen is hanging, and black's only legal move is to capture it, at which point it's immediately a technical draw due to same color bishops not being able to mate*

### Expected behavior

The fact that the engine is confused at first is understandable, since there are many more pieces than standard chess, and it's a very long line. But once all pawns besides one are gone, and the last pawn promotes with check, and is hanging, and capturing it is the only legal move, and capturing it immediately ends with a draw, that I would imagine SF "can" see, which is why I'm reporting this.

If this is the wrong place to report this, as more than the standard material is present, please let me know, and I will happily post wherever fitting.

Thank you.

### Steps to reproduce

Turn on eval on lichess

### Operating system

All

### Stockfish version

17

**Comment by xu-shawn** [comment] 2024-11-28 04:51
Probably a duplicate of #4799, it is well-known that SF misevaluates positions with multiple same-colored bishops

**Comment by Disservin** [comment] 2024-12-01 22:23
Well #4799 and this are vastly different. Here the position is completely illegal for standard chess.
We aren't interested in the analysis of such illegal position, maybe fairy stockfish, but even for this I doubt there is any real value gained from having a correct analysis in this lol

**Comment by Disservin** [comment] 2024-12-01 22:23
Well #4799 and this are vastly different. Here the position is completely illegal for standard chess.
We aren't interested in the analysis of such illegal position, maybe fairy stockfish, but even for this I doubt there is any real value gained from having a correct analysis in this lol

**Closed by Disservin** 2024-12-01 22:23 UTC

**Comment by Disservin** [comment] 2024-12-01 22:33
It's not. This position is not a position which can be achieved in chess. It is an arbitrary setup position which is not evaluated "right", have you ever put 100 football player on a field and then complained to the coach that his team isn't playing correctly?

**Comment by Disservin** [comment] 2024-12-01 22:48
Well it isn't strictly over, lichess doesn't let you continue with the game anymore because they apparently implemented a solver which detects if the position doesn't result in mate. We don't have this for stockfish (not to this degree). In stockfish's eyes the position isn't over and white has a huge material advantage, it just doesn't far enough to realize that with all the bishops this will also end in a draw, and we kinda assume that the gui will stop such positions
