### ISSUE TITLE
Unable to add engine to ChessBase 

### ISSUE THREAD

**Issue by Maratka2** [official-stockfish/Stockfish#4489] opened 2023-04-02 12:49 UTC
### Describe the issue

It appears in the add engine menu, but it is not in the engine selection menu.
Probably the problem is that a few days ago the engine was renamed, like:
was: Stockfish dev-20230314-78532af9
became: Stockfish dev-"20230401"-"6a6e32df"

So it looks like the shell doesn't accept either quotes or a long engine name.

### Expected behavior

_

### Steps to reproduce

Try to add the latest version of the Abrok engine to the ChessBase shell, such as Frirz 15.

### Anything else?

_

### Operating system

Windows

### Stockfish version

last few

**Comment by vondele** [comment] 2023-04-02 12:52
duplicate of https://github.com/official-stockfish/Stockfish/discussions/4486 
seems like an issue with the abrok compiled binaries. 
You can download latest binaries on github as well https://github.com/official-stockfish/Stockfish/actions/runs/4583679966 (look for artifacts), they are fine.

**Comment by Maratka2** [comment] 2023-04-02 13:15
I always use MS VS 2022, there is no problem there (or maybe I already downloaded more recent sources).
In any case, there were no problems with my compilations.

**Comment by vondele** [comment] 2023-04-03 10:21
The abrok issue has been fixed. Downloads now are OK.

**Closed by vondele** 2023-04-03 10:21 UTC
