### ISSUE TITLE
Removing Slow Mover is a mistake!

### ISSUE THREAD

**Issue by Ipmanchess** [official-stockfish/Stockfish#1336] opened 2017-12-11 18:26 UTC
It's already a few month..exactly date 17-08-17 when Slow Mover get removed for a Time management simplification? https://github.com/official-stockfish/Stockfish/commit/01d97521fd675ed157ff7d61e6057916abbcc56c
Since then every new Stockfish Dev. i have tested get not higher in my lists..
After this patch people begin to see weird time loses ,while Stockfish never lose on time for many years!
I play always 5min.games called sudden death games..so no increment.
When you revert the patch or download the compiles from Ultimaiq i get Stockfish back on top ,and this on my 3 systems or lists..so from 1core till 8cores testings.
Have tried a few times to tell people,but nobody react..why not try and test this out?
Stockfish has lost a lot Elo with removing SM in these sudden death games..and i think a engine can only be best if it can handle all time controls ,and 5min.games is still a official TC used in the chess world.
You will see Stockfish back on top everywhere when adding Slow Mover again..or have a fix for it!

My lists you find here: http://www.ipmanchess.yolasite.com/

Engines are marked with +sm or +Slow Mover.

Ipman.

**Comment by hero2017** [comment] 2017-12-12 04:11
I have to agree with Ipman. The results speak for themselves.

**Comment by Kingdefender** [comment] 2017-12-12 11:13
Marco wants to leave room for experimentation and support Ivan a bit. That is part of it. Whether it is gonna work well is another thing. Removing UCI parameters is going contrary to the experimentation idea but in line with simplification Thanks for your observations Ipman. Personally I'm not going to change the time management in Kaissa soon. It is from an older codebase so. Another reason is, like you I also prefer testing without time increment. The GUI is adding some increment anyway and the time increments that you can choose are at least one second, so big. I have not tested any of the new TM versions with it, but I expect even those will not lose on time in Shredder's Gui.

What I do not understand, the Ultimaiq compiles are from Ivan Ivec too, So apparently he does not trust his own time management enough for his own?

**Comment by Ipmanchess** [comment] 2017-12-12 12:27
Maybe Ivan have read my findings during these last month ,or Ivan have seen also in his own testings..
The compiles are updated till last patch + revert slow mover,so we can choose..
But how long can we revert it..till one day it doesn't and problem still exsist!?

I was planning when new system is build up to use TC+increments ,but when i see this then i want to keep my 5min.games for final and to have a check that engines can play sudden death games also!

**Comment by xoto10** [comment] 2017-12-13 09:46
ipman, I see there used to be a "Slow Mover" UCI option. Did you used to give a value for this? What value? I guess this made SF move quicker so that time losses were less likely?

**Comment by Ipmanchess** [comment] 2017-12-13 09:54
Hi xoto10..just the last default value = 89
I did never get losses on time even with these new dev's without Slow Mover..but for some reason Stockfish plays much weaker without it in my 5min.games?
Slow Mover revert..everything back at full strenght as you can see in my lists!

**Comment by mcostalba** [comment] 2017-12-17 08:59
Closing as duplicate of https://github.com/official-stockfish/Stockfish/issues/1272

**Closed by mcostalba** 2017-12-17 08:59 UTC

**Comment by namebrandon** [comment] 2017-12-27 05:12
Since this closed, have left issue with more detail in https://github.com/official-stockfish/Stockfish/issues/1272 but would also support the SlowMover option being reintroduced. For now it's removal forces me to use an entirely different engine with better time management strategies.
