### ISSUE TITLE
32 bit abrok compiles creating exception in SF9-dev

### ISSUE THREAD

**Issue by DragonMist** [official-stockfish/Stockfish#1000] opened 2017-02-11 21:53 UTC
System: WIN XP 32-bit, CB F11 GUI, 5 men Syzygy on hard disc used. For several years on that particular machine and setup abrok 32-bit compiles worked perfectly, but since stockfish_16110507_32bit.exe i.e. compile after

**Author: Marco Costalba 
Date: Sat Nov 5 07:55:08 2016 +0100 
Timestamp: 1478328908 

Rewrite syzygy in C++** 

runing infinite makes SF crash:

_"The instruction at "(varying)" referenced memory at "something". The memory could not be "read"."_

So, last working exe was SF8 official, i.e. stockfish_16110110_32bit.exe. Sounds like something related to Syzygy, of course, judging by the patch that introduced it. Checked several later abrok 32 bit compiles, all not working and producing the same crash (several seconds after hitting infinite).

**Comment by stockfishdeveloper** [comment] 2017-02-13 14:52
Please post all the commands you entered including setting the TB path.
If possible, please post part of the error log or crash statements.

**Comment by DragonMist** [comment] 2017-02-13 15:37
Here are 2 examples:

http://pasteboard.co/xT12NcvEB.png

http://pasteboard.co/xT1u7U28U.png

Syzygy path has not been changed (i.e. somewhere on the disc and working for 2 years previously). Command is GUI equivalent of "go infinite" I pressume. My suspicions are SF crashes as soon as it first hits Syzygy (default settings as per engine). Another info: engine is running on 2 cores (system max).

**Comment by MichaelB7** [comment] 2017-02-13 15:51
If it's truly a SF issue , you should be able to duplicate it on the command line.   Otherwise , I'm suspecting it's a GUI issue.   Have you tried other GUI's ?

**Comment by DragonMist** [comment] 2017-02-13 16:18
No, but I will try command line and report what happens. Probably not be able to try other GUI, it is not my PC.

**Comment by DragonMist** [comment] 2017-02-13 19:16
PS besides, how can it be GUI issue when GUI worked absolutely fine for couple of years with all previous versions, and without a single settings change, any SF dev from stockfish_16110507_32bit.exe onward crashes? Just wondering ...

**Comment by ddugovic** [comment] 2017-02-13 19:29
No need for a second GUI - run SF8 from a command line, then issue the input `go infinite`.  This sounds simple to duplicate on that architecture.

**Comment by MichaelB7** [comment] 2017-02-13 19:51
If this was sf centric issue only with the 32 bit version of sf from this version on forward , do you not think there would be scores if not hundreds of users reporting the same issue ?  Probably trouble shooting this issue is to first identify whether is the sf exe , the GUI or the host OS - any which could be the culprit - the question to ask yourself - was there any OS update , GUI update , is the issue reproducible on another machine?  Unless others are reporting the same issue , I have to believe it's related to the host computer or GUI but not sf.

**Comment by DragonMist** [comment] 2017-02-13 20:49
@ddugovic will try and report back
@MichaelB7 I see, thanks for explaining. I rather naively figured 32 bit users are rather scarce nowadays. Still, to note is: there was no OS upate, no GUI update or any other kind of important software update between working and non working versions.
I shall report back after trying command line, could take a day or 2, though. Thanks for helping.

**Comment by MichaelB7** [comment] 2017-02-13 20:55
Which GUI are you using ?

**Comment by DragonMist** [comment] 2017-02-13 20:56
CB F11 GUI

Dana 13. velj 2017. 21:55 osoba "Michael Byrne" <notifications@github.com>
napisala je:

**Comment by vondele** [comment] 2017-02-14 18:54
@DragonMist since it seems difficult to reproduce, it will require some help to narrow it down. 

* Since you suspect syzygy, an easy test would be to use a SF version that crashes with syzygy and run it on the same position without syzygy. Does it still crash ?

* Could you try to do your own compile ? If so, you could compile with 'optimize=no debug=yes' arguments to the 'make ARCH=... build optimize=no debug=yes' and try to run with such a compile. This hopefully gives a more useful location of the offending instruction. 

* Finally, it is conceivable that the new code deals differently, e.g. with a corrupted syzygy file. Any chance you could check the integrity of the files you have, by checking their checksums ?

**Comment by stockfishdeveloper** [comment] 2017-02-14 19:37
@DragonMist I've had problems with the tablebase DLL(something like "tablebase.dll") that comes with the CB GUI. It's in the main folder. Try replacing it with the same DLL from a good copy of CB.

**Comment by DragonMist** [comment] 2017-02-14 19:47
Thank you all guys for useful advices. Unfortunately I do not have permanent access to that particular PC (my father's PC), so will have to wait a couple of days before I try as many of things you mentioned as I can. Then we'll probably know more.

**Comment by stockfishdeveloper** [comment] 2017-02-15 01:27
@DragonMist Thanks for the concern about this issue.
Since nobody has been able to reproduce the error, I think it's time to close this as non-issue.

**Comment by DragonMist** [comment] 2017-02-15 11:42
No problem, if I have anything else to report, I'll post on fishcooking forum.

**Comment by theo77186** [comment] 2017-02-15 12:21
Can confirm the issue. Steps to reproduce the segfault:
1. Download SF 32-bit from Abrok.
2. Run these following commands:
```
setoption name SyzygyPath value <path>
position fen 6k1/2R5/3K2N1/3P2P1/5P2/r4n2/8/8 w - - 3 66
go infinite
```
And it will segfault at depth 5-6.
I'll give some GDB reports later.

**Comment by DragonMist** [comment] 2017-02-15 17:39
I would like to try my own 32 bit builds, but I am not sure if it (creating 32 bit compile) can be done on my 64 bit machine? Or do I have to install mingw on that 32 bit and compile there?

**Comment by stockfishdeveloper** [comment] 2017-02-16 23:35
Every 64 bit machine can by definition compile 32 bit builds.
If you're using a GUI it is trivial to find the build option for x32-x64.
If you're using "plain" MinGW you must use a 32 bit version for 43 bit builds.
32 bit machines can also compile 64 bit programs as a side note.

**Comment by DragonMist** [comment] 2017-02-18 09:57
@vondele checked latest abrok.eu 32 bit, still crashes with syzygy, no crash on same position without syzygy. Tried to compile my own version, but it does not work (as indicated by @stockfishdeveloper , I am using plain MinGW on my machine) - couldn't even install it there. Checked installed 5 men syzygy with fsum, no problems found.

@theo77186 @ddugovic tried command line as per instructed, latest abrok.eu 32 bit crashed as theo reported:

http://pasteboard.co/zLY9Rqfsv.jpg

**Comment by vondele** [comment] 2017-02-18 10:26
@DragonMist, so that rather clearly identifies an issue with the syzygy code, as you already observed correctly, but only triggering on a particular architecture and/or build setup. To debug this, somebody needs to be able to reproduce a crashing build.

Reminds me a bit of the exchange in #962 ... would have been caught earlier if syzygy was tested automatically, and if testing of windows was more extensive (that's to 'if's, however).

**Comment by DragonMist** [comment] 2017-02-18 15:10
@vondele thanks, I would still like to help solve this, if possible. I can install mingw on machine with issues and try to compile special 32 bit version, but would need instructions on how to compile that special debug version.

**Comment by vondele** [comment] 2017-02-18 16:47
@DragonMist if you can install and build with mingw on that machine, the debug version could be something like:

`make build ARCH=x86-32 COMP=mingw optimize=no debug=yes`

if that compile doesn't work try to remove 'optimize=no'.

you can than run the command line version and see if it reproduces the crash. Hopefully that results in useful information.... otherwise one would need to run stockfish under a debugger (gdb) to get a backtrace.

**Comment by DragonMist** [comment] 2017-02-18 19:03
Ok, will try and report back (installing mingw not the easiest of things :( ).

**Comment by rohitrajiit** [comment] 2017-02-19 20:28
I compile Stockfish on my 32 bit machine since last  year March. After that syngzy patch, compiles on my machine crash if given exit command. But otherwise they run fine since I don't use table bases. 
Before this issue was reported I had independently compiled all SF patches since Sf8 and identified that this problem started after syngzy patch only. But since abrok.eu compiles don't exhibit the same behavior, I had not reported it.

**Comment by rohitrajiit** [comment] 2017-02-19 20:33
And I use a different compiler version then one used on abrok.eu.  Since  abrok.eu compiles are slower.

**Comment by tthsqe12** [comment] 2017-04-28 07:40
This is a well-known issue with gcc on windows. See
[forum post](https://groups.google.com/forum/?fromgroups=#!searchin/fishcooking/movaps%7Csort:relevance/fishcooking/TbGf7fFMavE/RZUblXxRCgAJ)
One fix would be to a the necessary flags to the makefile

**Comment by lantonov** [comment] 2017-04-28 07:55
It turned out to be related to the gcc (mingw) version. Old gcc (e.g. 4.7.3) produced crashing compiles. Newer gcc (after 6.0.0) produced stable compiles. See the closed issue [#721](https://github.com/official-stockfish/Stockfish/issues/721)

**Comment by rohitrajiit** [comment] 2017-05-10 12:16
After upgrading from gcc 4.9.2 to gcc 7.10. My compiles don't crash. But I dont use tablebases.

**Comment by snicolet** [comment] 2018-03-08 08:38
Is the problem still present in SF9 and SF10-dev?
I would like to be able to close the issue, if possible.

**Comment by DragonMist** [comment] 2018-03-08 08:42
Unfortunately I do not have the 32-bit machine to test it any more. Feel free to close it.

**Closed** 2018-03-14 22:00 UTC
