### ISSUE TITLE
Mate in #4 is not detected stockfish 7 64 POPCNT (move sequence is same)

### ISSUE THREAD

**Issue by ChameleonRed** [official-stockfish/Stockfish#615] opened 2016-04-03 18:32 UTC
For this position there is no mate detected ...

1Q6/p4pkp/4p1p1/1Np4q/2P1nP2/4P1P1/P5KP/8 b - - 6 35

Now is mate in #5 still not detected ...

1Q6/p4pkp/4p1p1/1Np5/2P1nP2/4P1P1/P3q1KP/8 w - - 7 36

Now mate in #4, #7, #8, #8 is possible - why???

1Q6/p4pkp/4p1p1/1Np5/2P1nP2/4P1PK/P3q2P/8 b - - 8 36

**Comment by mcostalba** [comment] 2016-04-05 07:15
I am not able to reproduce: with position 1Q6/p4pkp/4p1p1/1Np4q/2P1nP2/4P1P1/P5KP/8 b - - 6 35

I got mate in 5: h5e2 g2h3 e4f2 h3g2 f2g4 g2h3 e2h2 h3g4 h2h5

**Comment by pb00068** [comment] 2016-04-05 07:40
A possible explanation could be that move 35...Qh5e2 in your specific game led to a position repetition, which Stockfish (and most other engines too) considers draw.
Can it be that position 1Q6/p4pkp/4p1p1/1Np5/2P1nP2/4P1P1/P3q1KP/8 w - - was already on board earlier in your game?

**Comment by ChameleonRed** [comment] 2016-04-05 19:11
I can send PGN - that was not repetition - it is second repetition it was still time to mate. I am programmer so I can send you detailed log if you need. By the way I finished it with draw because not saw mates :)

**Comment by ChameleonRed** [comment] 2016-04-05 19:16
This is PGN - see move 34:
Analysis says 28 [-6.22]  35.Kg2 a6 36.Nd4 cxd4 37.Qb2 e5 38.Qc2 Nd6 39.exd4 Nf5 40.Qd3 exf4 41.gxf4 Qg4+ 42.Kf2 Qxf4+ 43.Ke1 Nxd4 44.Kd1 Nc6 45.Qc3+ f6 46.h3 Ne5 47.c5 Qe4 48.Kc1 Nc4 49.a3 Qd5 50.Kc2 Qxc5 51.Kb3 Qb5+ 52.Ka2  (136.99)

[Annotator "Stockfish 7 64 POPCNT"]
[Depth "20"]

1.d4 d5 2.Nf3 e6 3.Bg5 Be7 $201 4.e3 $4 $19 $201 
    ( 4.Bxe7 Nxe7 5.c4 O-O 6.e3 b6 7.cxd5 Nxd5 8.Bb5 c5 9.dxc5 Ba6 10.a4 bxc5 11.O-O Bxb5 12.axb5 Nd7 13.Nc3 N7f6 14.Qe2 Qc7 $10 )
4...Nd7 $4 $10 
    {+0.28 / -3.08}
    ( 4...Bxg5 5.Nxg5 Qxg5 6.Nd2 Bd7 7.a3 Nc6 8.Nf3 Qe7 9.c4 Nf6 10.Rc1 h6 11.Be2 O-O 12.O-O Rfe8 13.Ne5 Ne4 14.Nxd7 Qxd7 $19 )
5.Bxe7 Qxe7 6.c3 Ngf6 7.Nbd2 O-O 8.Nb3 b6 9.Bd3 Bb7 10.O-O Rac8 11.Qc2 c5 $201 12.Ng5 $2 $17 $201 
    {-2.01 / -0.25 ****D9 -0.3->-2.0 }
    ( 12.Nbd2 e5 13.dxe5 Nxe5 14.Nxe5 Qxe5 15.a4 Rfe8 16.Nf3 Qc7 17.Rfd1 a5 18.Rab1 Bc6 19.b4 axb4 20.cxb4 c4 21.Bf5 Ra8 $10 )
12...g6 $2 $10 
    {-0.40 / -2.01}
    ( 12...h6 13.Nh7 Nxh7 14.Bxh7+ Kh8 15.dxc5 f5 16.cxb6 axb6 17.Bxf5 Rxf5 18.a4 Ba6 19.Rfe1 Nc5 20.Nxc5 Qxc5 21.a5 bxa5 22.Qa4 Bb5 23.Qd4 a4 24.Qxc5 Rxc5 25.e4 Rf7 26.exd5 exd5 27.f3 $17 )
13.dxc5 bxc5 14.c4 Ba6 15.Rae1 Ne5 16.Nd2 Nxd3 17.Qxd3 Rfd8 18.Qc2 Nd7 19.f4 Nb6 20.b3 dxc4 21.bxc4 Bb7 22.Nge4 Bxe4 23.Nxe4 Nd7 24.Rb1 Rc7 25.Rfd1 Nf6 26.Nc3 Rxd1+ 27.Rxd1 Rb7 28.Rb1 Rxb1+ 29.Qxb1 Qd7 30.Qb8+ Kg7 $201 31.Nb5 $4 $19 $201 
    {-327.48 / +0.00 ****D2 0.0->-327.5 }
    ( 31.Qe5 h5 32.h3 Qd3 33.Nb5 Qxc4 34.Nd6 Qa4 35.Qxc5 Qd1+ 36.Kh2 Qd5 37.Qc7 e5 38.f5 e4 39.fxg6 Qe5+ 40.Kg1 Qa1+ 41.Kh2 Qe5+ $10 )
31...Ne4 $4 $14 $201 
    {+0.77 / -327.48 ****D1 -327.5->0.8 }
    ( 31...Qd1+ 32.Kf2 Ne4# $19 )
32.g3 $4 $19 
    {-327.44 / +0.77}
    ( 32.Qe5+ Nf6 33.h3 h5 34.Qxc5 Qd2 35.Kh2 Qe1 36.Qe5 h4 37.Qc3 Qxc3 38.Nxc3 Nd7 39.Ne4 Kf8 40.Kg1 Ke7 41.Kf2 e5 42.Ng5 Nc5 43.Nf3 Nd3+ 44.Ke2 e4 45.Nxh4 Kd6 46.g3 $14 )
32...Qd1+ 33.Kg2 Qe2+ 34.Kh3 $201 Qh5+ $4 $19 
    {-4.84 / -327.46}
    ( 34...Nf2+ 35.Kg2 Ng4+ 36.Kg1 Qxh2+ 37.Kf1 Qf2# $19 )
35.Kg2 $201 Qe2+ $4 $10 
    {+0.00 / -5.10}
    ( 35...a6 36.Nc3 Nxc3 37.Qb2 Qe2+ 38.Qxe2 Nxe2 39.Kf2 Nc3 40.a3 Nd1+ 41.Ke2 Nb2 42.Kd2 Nxc4+ 43.Kd3 Nxa3 44.Kc3 Kf6 45.Kb3 Nb5 46.Kc4 Kf5 47.Kxc5 Ke4 48.Kb6 Kxe3 49.Kxa6 Nd4 50.Ka5 Nf3 $19 )
36.Kh3 $201 Qh5+ $4 $10 
    {+0.00 / -327.46}
    ( 36...Nf2+ 37.Kg2 Ng4+ 38.Kg1 Qxh2+ 39.Kf1 Qf2# $19 )
37.Kg2 $201 Qe2+ $4 $10 
    {+0.00 / -5.13}
    ( 37...a6 38.Nc3 Nxc3 39.Qb2 Qe2+ 40.Qxe2 Nxe2 41.Kf2 Nc3 42.a3 Nd1+ 43.Ke2 Nb2 44.Kd2 Nxc4+ 45.Kd3 Nxa3 46.Kc3 Kf6 47.Kb3 Nb5 48.Kc4 Kf5 49.Kxc5 Ke4 50.Kb6 Kxe3 51.Kxa6 Nd4 52.Kb7 Nf3 53.Kc6 Nxh2 54.Kd6 Nf1 $19 )
38.Kh3 $201 Qh5+ $4 $10 
    {+0.00 / -327.46}
    ( 38...Nf2+ 39.Kg2 Ng4+ 40.Kg1 Qxh2+ 41.Kf1 Qf2# $19 )
39.Kg2 Qe2+ 
    ( 39...Qe2+ { 20:+0.00} 40.Kh3 )
*

**Comment by pb00068** [comment] 2016-04-06 06:50
>> it is second repetition, it was still time to mate.

Indeed move 35...Qh5e2 in your specific game led to a position repetition.
As I tried to explain above, most chess engines (Stockfish included) behave different on position repetition and don't follow the official chess rules, they adjudicate a position repetition directly as draw. This is because implementing a correct 3-fold repetition detection so far always made the engine loose in playing strength by some elo-points.

**Comment by zamar** [comment] 2016-04-07 17:43
Closing as non-issue.

**Closed by zamar** 2016-04-07 17:43 UTC

**Comment by ChameleonRed** [comment] 2016-04-07 19:25
I think that was helpful to send you some position whatever I am not chess programmer but playing chess and program a lot so nice to learn something about how it works.
