### ISSUE TITLE
Depth 245 anomaly during TCEC

### ISSUE THREAD

**Issue by mstembera** [official-stockfish/Stockfish#2717] opened 2020-06-05 21:09 UTC
I was looking at this TCEC game
https://tcec-chess.com/#div=p&game=72&season=18&x=archive
and noticed that on move 67 SF reached our max depth of 245.  This isn't so strange on its own except that the depth never went above 68 on any other move.  The time used, nodes searched, and TB hits, all look normal.  Does anyone have a plausible explanation or could this be an issue?

**Comment by joergoster** [comment] 2020-06-06 08:39
There was also a big difference in depth between threads reported here https://github.com/official-stockfish/Stockfish/issues/2620
Probably the thread with the highest depth was chosen by the thread voting. TB scores are getting stored with max depth, and one thread probably always took the TT cutoff and made it to MAX_PLY ...

**Comment by vondele** [comment] 2020-06-06 13:22
TB could indeed be a reason for this. I couldn't yet reproduce it, but so far tried without TB.

**Comment by mstembera** [comment] 2020-06-06 18:22
Maybe that's correct I'm not sure.   The fact that it only happened in the position on move 67 and not any of the other similar positions just before or after seems odd regardless.

**Comment by mstembera** [comment] 2020-06-06 21:04
Ok here is a game where it happens several times
https://tcec-chess.com/#div=p&game=16&season=18&x=archive

**Comment by vondele** [comment] 2020-06-09 17:22
could we get the cutechess log for that game? Might be useful to figure out what's going on.

**Comment by vondele** [comment] 2020-06-09 17:36
[s18p_16live.log.txt](https://github.com/official-stockfish/Stockfish/files/4753795/s18p_16live.log.txt)

**Comment by Alayan-stk-2** [comment] 2020-07-02 15:01
This happened again yesterday in another game after Stockfish had found a TB win.

**Comment by joergoster** [comment] 2020-07-07 10:58
Are we sure the thread voting patch is working correctly for cases with very high depth differences?
https://github.com/official-stockfish/Stockfish/blob/master/src/thread.cpp#L240-L241

**Comment by vondele** [comment] 2020-07-07 11:13
@joergoster not necessarily, or said differently, that thread will have a very high weight. I once tried to limit the depth difference, but those patches did not pass:
https://tests.stockfishchess.org/tests/view/5e9c2bd927460669d4042db0
https://tests.stockfishchess.org/tests/view/5e9c2bcd27460669d4042dae
https://tests.stockfishchess.org/tests/view/5e9c2bc127460669d4042dac

Some analysis why this is happening is still missing.

**Comment by joergoster** [comment] 2020-07-07 11:34
@vondele But that seems more like a bugfix, no?

But first, however, it must be fully understood what is going on.

**Comment by vondele** [comment] 2020-07-07 11:43
Yes, we need to fully understand before we can say something is a bug fix, or test it as a bug fix.... so testing as an Elo gainer was a quick workaround ;-)

I agree that in TB win positions we should use the score, rather than a vote (but I think we do that already).

**Comment by vondele** [comment] 2022-02-20 19:35
This seemingly still happens in quite recent times 
https://www.chess.com/computer-chess-championship#event=ccc-16-blitz-finals&game=1 
https://www.chess.com/computer-chess-championship#event=ccc-16-blitz-finals&game=22
https://www.chess.com/computer-chess-championship#event=ccc-16-blitz-finals&game=23
https://www.chess.com/computer-chess-championship#event=ccc-16-blitz-finals&game=54
...
shows this again.

**Comment by dav1312** [comment] 2022-04-20 18:38
Happened again
https://tcec-chess.com/#div=sf&game=84&season=22

**Comment by movepicker** [comment] 2022-04-23 07:13
depth 245 is a maximum depth of stockfish
it was happened when `adjustedDepth` has bug or problem in main source code 

```
Depth adjustedDepth = std::max(1, rootDepth - failedHighCnt - searchAgainCounter);
bestValue = Stockfish::search<Root>(rootPos, ss, alpha, beta, adjustedDepth, false);
```

see `search.cpp`  , line 372 & 373 from this link :

https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L372
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L373

**Comment by vondele** [comment] 2022-05-08 15:43
so, some more investigation of the games https://tests.stockfishchess.org/tests/view/6272a6afc8f14123163c1997 some of these high depth happen also there, so it doesn't require TB. It doesn't happen in a single threaded run (https://tests.stockfishchess.org/tests/view/626abd7e8707aa698c0093a8), so it seems purely related to threading.
(not that these ar depth 245 in the middle of a game, they can happen without concern if there is a mate announcement, or stalemate, 3fold on then next move).

So somehow an interaction between threads, but at least we can take TB out of the picture.

**Comment by miguel-l** [comment] 2022-05-09 06:42
I'm not too familiar with threading code, but does the following make sense:
Is it possible that this has something to do with `Threads.increaseDepth` ?

As far as I can tell, this is handled only by mainThread and updated only at the end of its current iteration. My thought is if it gets stuck in resolving a fail or stuck in some search explosion while increaseDepth is false, then some other thread could be looping over the same rootDepth until they reach 245.

**Comment by ruicoelhopedro** [comment] 2022-06-08 18:36
Two examples where this issue happens: [depth245.zip](https://github.com/official-stockfish/Stockfish/files/8864182/depth245.zip)
Logs with both regular debug log file and with per-thread search logs, reproduced locally.

**Comment by mstembera** [comment] 2022-06-08 20:39
I'm not sure if this is related but in the current TCEC swiss SF announced mate in 73 even though it only reported depth 39 and select depth 61.  This was on move 53 of this game https://tcec-chess.com/#div=sw3&game=93&season=22

**Comment by vondele** [comment] 2022-06-30 07:52
looks like @miguel-l has identified the cause in the test https://tests.stockfishchess.org/tests/view/62aee644e7ee5525ef88c15a 

In discord: 
Disservin
 — 
Today at 9:47 AM
I just checked the first 756 pgns and the patch has no weird 245 depths other than near checkmate or draw, base has 422
422 (some of them are also checkmate and draw depths) but shouldnt be that many < 10

I can see how these changes could be related.

**Comment by vondele** [comment] 2022-06-30 08:04
@ruicoelhopedro any chance you could repeat your analysis, printing out an additional number of each thread, namely the `adjustedDepth` in addition to the rootDepth?

**Comment by ruicoelhopedro** [comment] 2022-06-30 10:45
> @ruicoelhopedro any chance you could repeat your analysis, printing out an additional number of each thread, namely the `adjustedDepth` in addition to the rootDepth?

I've started some games with the extra field. I'll post the logs when the issue is reproduced.

**Comment by ruicoelhopedro** [comment] 2022-06-30 13:28
Here they go, got a bit lucky as this happened in 3 games: [depth245_adjustedDepth.zip](https://github.com/official-stockfish/Stockfish/files/9020141/depth245_adjustedDepth.zip)

**Comment by vondele** [comment] 2022-06-30 14:05
so, the logs show that what we think is happing is actually happening. The increaseDepth is false, adjustedDepth is constant, and the rootDepth just reaches the maximum.

**Comment by miguel-l** [comment] 2022-07-02 07:41
Just want to have these somewhere I can find it (and also in case others might want to use or improve upon).

For downloading sample pgns from a test
`for i in {0..99}; do wget "https://tests.stockfishchess.org/api/pgn/62aee644e7ee5525ef88c15a-${i}.pgn"; done`

For manual checking
`cat *.pgn | grep "White\|Black\|\/245" | grep -B 2 "\/245" | less`

**Closed** 2022-07-09 10:32 UTC
Labels: search
