### ISSUE TITLE
How to compile Stockfish on Android?

### ISSUE THREAD

**Issue by anonymous7002** [official-stockfish/Stockfish#2504] opened 2020-01-20 15:01 UTC
I tried on Windows with MSYS2 MinGW64: make -j profile-build ARCH=arm64v8 COMP=mingw
Apparently, Stockfish does not allow arm64v8, although compiled Android version has arm64v8.
I tried armv7, but that produced normal Windows binaries.

**Comment by snicolet** [comment] 2020-01-23 18:23
Looks like a duplicate of https://github.com/official-stockfish/Stockfish/issues/2380. Closing.

**Closed by snicolet** 2020-01-23 18:23 UTC
