### ISSUE TITLE
Strange Behavior NNUE

### ISSUE THREAD

**Issue by GiordanoVicoli** [official-stockfish/Stockfish#3223] opened 2020-11-09 08:20 UTC
Hi everybody,

I have a strange behavior of Stockfish with nnue in my iOS application.

I have set this position: 3b4/1q2nb1k/2n3pp/1p2P3/3B1NQP/1pP5/5PP1/1B4K1 w - - 0 37

The evaluation of Stockfish without NNUE is always > 2.0.

The evaluation of Stockfish with NNUE is > 2.0 the first time I enable NNUE. If I switch off the  engine,  when I switch on again with NNUE the evaluation is about 0.1. If I close the application and open again the evaluation with NNUE is > 2.0 the first time I run the. engine.  Is there someone able to explain this behavior?

Many thanks and regards,
Giordano

**Comment by syzygy1** [comment] 2020-11-09 20:40
It is quite common that a second search of the same position returns a different result (even in single-threaded mode) if the hash table is not cleared between the first search and the second search. This is not specific to NNUE.

**Comment by GiordanoVicoli** [comment] 2020-11-09 21:09
Thank you for explanation but how can clear the hash table after a first search?

**Comment by vondele** [comment] 2020-11-09 21:22
send `ucinewgame` or use `option name Clear Hash type button`

**Comment by GiordanoVicoli** [comment] 2020-11-10 14:37
I tried the suggestion but the problem is not about Hashtable. The problem is tied to nnue file. Probably when I switch off nnue analysis in memory remains spurious nnue data. Is there a reset command about nnue file?
Obviously if you use Stochfish on command line there is not this problem but if you use Stockfish inside another application this problem arises.

**Comment by vondele** [comment] 2020-11-10 14:51
Does that other application use an unmodified version of Stockfish, and communicate via pipes to it? If anything else, likely the problem is with the integration, IMO.

**Comment by GiordanoVicoli** [comment] 2020-11-10 17:53
Communication is not via pipe, commands to engine are pushed in a queue then they are execute directly in the uci.cpp class.
In the uci.cpp class a function has been implemented (execute_command) that is similar to UCI::loop function without loop.

**Comment by snicolet** [comment] 2020-11-10 18:24
Can we see the source code, please?

**Comment by GiordanoVicoli** [comment] 2020-11-10 18:29
This is the function execute_command in the uci.cpp class

void execute_command(const string &cmd) {
    //void UCI::loop(int argc, char* argv[]) {
    
    //Position pos;
    //pos.set(StartFEN, false, &States->back(), Threads.main());
    
    //StateListPtr states(new std::deque<StateInfo>(1));
    auto uiThread = std::make_shared<Thread>(0);
    
    //static Position10 pos(StartFEN, false, &states->back(), Threads.main()); // The root position
    static Position pos(StartFEN, false, &states->back(), uiThread.get());
    
    //pos.set(StartFEN, false, &states->back(), uiThread.get());
    
    
    //Position pos(StartFEN, false, &states->back(), uiThread.get());
    
    //
    
    //sync_cout << pos << sync_endl;
    
    //static Position pos(StartFEN, false, &states->back(), uiThread.get()); // The root position
    
    //pos.set(StartFEN, false, &States->back(), Threads.main());
    
    //  Position pos(StartFEN, false, Threads.main()); // The root position
    //static Position pos(StartFEN, false, Threads.main()); // The root position
    
    string token; //, cmd;
    
    //for (int i = 1; i < argc; ++i)
    //    cmd += std::string(argv[i]) + " ";
    
    //do {
    //if (argc == 1 && !getline(cin, cmd)) // Block here waiting for input or EOF
    //    cmd = "quit";
    
    istringstream is(cmd);
    
    token.clear(); // getline() could return empty or blank line
    is >> skipws >> token;
    
    // The GUI sends 'ponderhit' to tell us to ponder on the same move the
    // opponent has played. In case Signals.stopOnPonderhit is set we are
    // waiting for 'ponderhit' to stop the search (for instance because we
    // already ran out of time), otherwise we should continue searching but
    // switching from pondering to normal search.
    if (    token == "quit"
        ||  token == "stop"
        || (token == "ponderhit" && Threads.stopOnPonderhit))
    {
        Threads.stop = true;
    }
    else if (token == "ponderhit")
        Threads.ponder = false; // Switch to normal search
    
    else if (token == "uci")
        sync_cout << "id name " << engine_info(true)
        << "\n"       << Options
        << "\nuciok"  << sync_endl;
    
    else if (token == "ucinewgame")
    {
        Search::clear();
        Time.availableNodes = 0;
    }
    else if (token == "isready")    sync_cout << "readyok" << sync_endl;
    else if (token == "go")         {
        //sync_cout << poscommand << sync_endl;
        //sync_cout << is.str() << sync_endl;
        //sync_cout << pos << sync_endl;
        //istringstream is2(poscommand);
        //sync_cout << is2.str() << sync_endl;
        //position(pos, is2, states);
        //sync_cout << pos << sync_endl;
        go(pos, is, states);
    }
    else if (token == "position") {
        //poscommand = is.str();
        //sync_cout << is.str() << sync_endl;
        position(pos, is, states);
        //sync_cout << pos << sync_endl;
        //go(pos, is, states);
        //p111 = true;
    }
    else if (token == "setoption")  setoption(is);
    
    // Additional custom non-UCI commands, useful for debugging
    else if (token == "flip")       pos.flip();
    else if (token == "bench")      bench(pos, is, states);
    else if (token == "d")          sync_cout << pos << sync_endl;
    else if (token == "eval")       sync_cout << Eval::trace(pos) << sync_endl;
    else if (token == "perft")
    {
        int depth;
        stringstream ss;
        
        is >> depth;
        ss << Options["Hash"]    << " "
        << Options["Threads"] << " " << depth << " current perft";
        
        bench(pos, ss, states);
    }
    else
        sync_cout << "Unknown command: " << cmd << sync_endl;
    
    //  } while (token != "quit" && argc == 1); // Passed args have one-shot behaviour
    //} while (token != "quit"); // Passed args have one-shot behaviour
    
    //Threads.main()->wait_for_search_finished();
}

**Comment by GiordanoVicoli** [comment] 2020-11-10 18:32
This is the loop inside a class called EngineController that push commands to a queue and at the end call execute_command

- (void)startEngine:(id)anObject {
   NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];

   engineThreadIsRunning = YES;
   engineThreadShouldStop = NO;

    if (!hasInit) {
        if ([_delegate getBoardType] == PLAY_ENGINE) {
            engine_init();
            //engine_init5();
        }
        else {
            engine_init();
            //engine_init5();
        }
    }

   //engine_uci_loop();
    
    while (!engineThreadShouldStop) {
         pthread_mutex_lock(&WaitConditionLock);
         if ([commandQueue isEmpty]) {
            NSLog(@"Nothing to do, sleeping. Wake me up when something happens!");
            pthread_cond_wait(&WaitCondition, &WaitConditionLock);
            NSLog(@"Waking up, work to do!");
         }
         pthread_mutex_unlock(&WaitConditionLock);
         while (![commandQueue isEmpty]) {
            NSString *command = [commandQueue pop];
            /*
            if ([command hasPrefix: @"go"]) {
               while (engineIsThinking);
               engineIsThinking = YES;
            }
            */
            NSLog(@"Executing command: %@", command);
            //execute_command(std::string([command UTF8String]));
             ///esegui_comando(std::string([command UTF8String]));
            //engineIsThinking = NO;
             
             command_to_engine(std::string([command UTF8String]));
         }
      }

   NSLog(@"engine is quitting");
    if ([_delegate getBoardType] == PLAY_ENGINE) {
        engine_exit10();
        //engine_exit5();
    }
    else {
        //engine_exit5();
        engine_exit10();
    }

   [pool release];
   engineThreadIsRunning = NO;
}

**Comment by syzygy1** [comment] 2020-11-12 11:13
In normal Stockfish, if you search, clear hash, search, everything is fine. The bug is therefore not in Stockfish but in the different way your program does things. I'm afraid you (or whoever wrote it) will have to debug your code yourself...

**Comment by GiordanoVicoli** [comment] 2020-11-12 14:45
Sorry but what does mean "In normal Stockfish, if you search, clear hash, search, everything is fine."?

**Comment by MichaelB7** [comment] 2020-11-12 15:30
> Sorry but what does mean "In normal Stockfish, if you search, clear hash, search, everything is fine."?

That the problem is with the program interacting with Stockfish , Stockfish is not causing the strange behavior.  Sorry - but we can't help you.

**Comment by syzygy1** [comment] 2020-11-13 00:32
It just means that if you search, clear hash, search, by giving it the right uci commands, the second search will be identical to the first search (if single threaded).

You are free to implement some other way of interacting with the engine (as long as you abide by the GPLv3), but then the debugging work is on you.

**Comment by vondele** [comment] 2020-11-13 06:11
I think it is now clear the issue is not related to stockfish itself, so I'll close the issue.

**Closed by vondele** 2020-11-13 06:11 UTC
