### ISSUE TITLE
For rootComplexity eval is called even if in check

### ISSUE THREAD

**Issue by vondele** [official-stockfish/Stockfish#4512] opened 2023-04-09 07:05 UTC
### Describe the issue

causes assert with for example `./stockfish*.exe bench 16 1 13 default depth classical`

### Expected behavior

no assert triggered

### Steps to reproduce

see above

### Operating system

All

### Stockfish version

master

**Comment by dubslow** [comment] 2023-04-09 07:50
I find Takes 1 and 3 to be rather illogical.

Take 1 results in a base time factor at the minimum of 0.85, which is unnatural but might pass nonregression; Take 3 is unnecessarily complicated, and has the effect of diluting the effect of this section of code by a factor of 2.

Take 2, on the other hand, is the logical and natural fix: keep the current effect as is when not in check, and when in check, simply set the time factor to the non-effect value of 1.0. This is also more or less what I wrote and submitted. On this basis, I paused my test as duplicate of your Take 2.

I recommend also pausing Takes 1 and 3.

**Comment by dubslow** [comment] 2023-04-09 07:51
On a deeper note, this suggests that the current default bench does not include any classical in check positions, i.e. doesn't offer sufficient code coverage from a test perspective. I suggest that, in addition to fixing this immediate issue, we upgrade the bench to include this check in the future.

**Comment by dubslow** [comment] 2023-04-09 12:47
4515 LGTM (presuming passer).

On the question of preventing this in the future, we could certainly make that in check position be HCE in the default mixed bench, but is it perhaps more useful to instead add the same assert to nnue eval as well? Or is that better left alone?

**Comment by vondele** [comment] 2023-04-09 12:56
I'll add the additional assert in evaluate.

**Comment by dubslow** [comment] 2023-04-09 13:00
I was just about to PR this lol https://github.com/official-stockfish/Stockfish/compare/master...dubslow:Stockfish:inCheckAssert

**Closed** 2023-04-09 13:20 UTC
