### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by samer707** [official-stockfish/Stockfish#3052] opened 2020-08-23 09:17 UTC
HELLO , i found something important to mention , the ( Author: Joost VandeVondele
Date: Thu Aug 20 21:13:07 2020 +0200
Timestamp: 1597950787) is working good for chesspartner software , but the ( Author: Joost VandeVondele
Date: Thu Aug 20 21:14:32 2020 +0200
Timestamp: 1597950872 ) not continue after 2 moves and stops analyse , video is here about that , and all developer versions after that the same till now 23/8/2020
![11111](https://user-images.githubusercontent.com/65483350/90975144-6d218a80-e53a-11ea-8f57-115bcd33cfd3.gif)

**Comment by vondele** [comment] 2020-08-24 05:13
closing as resolved.

**Comment by samer707** [comment] 2020-08-24 05:51
hello , is the (default net nnue) give the same development build action and moves when i download it and put it beside development build whatever version of development build ?

**Comment by vondele** [comment] 2020-08-24 05:53
each development build comes with one specific default net, which is indicated by the default value of EvalFile. That's the net to use. The net doesn't change often, so if the name is the same, you don't need to download again.

**Comment by samer707** [comment] 2020-08-24 08:22
thank you

**Comment by samer707** [comment] 2020-08-24 08:26
did you see the comment with video i sent it before 23 hour before ? because the new development build until now dose not work without putting (default net nnue) beside it, and all versions before working only good

**Comment by samer707** [comment] 2020-08-24 08:28
sorry : all versions before working lonely , good

**Comment by vondele** [comment] 2020-08-24 08:35
yes, things are changing, and we're figuring out the best way to deal with the addition on the net. On the positive side, enjoy a 100+ Elo stronger chess.

**Comment by samer707** [comment] 2020-08-24 08:45
yes my only best engine in the world is stockfish , because of That i want it to develop ahead without little changes that affects on It's work

**Comment by samer707** [comment] 2020-08-24 08:52
it is strongest chess engine for me , i depend on it to solve chess positions

**Comment by samer707** [comment] 2020-08-31 06:25
Thanks for the interest, ( for last development versions ) it is possible that you integrate (nn-82215d0fd0df.nnue) with Developer, i do not know , this is very good act ,however,  I was confident of your interest because Stockfish is a company that respects its self and its customers

**Comment by samer707** [comment] 2020-09-22 18:59
the same problem in same developer person that i mentioned before in video ( samer707 commented on May 19 ) the developer is (Author: Sami Kiminki)
and the problem in (Author: Sami Kiminki
Date: Mon Sep 21 08:43:48 2020 +0200
Timestamp: 1600670628Date: Mon Sep 21 08:43:48 2020 +0200
Timestamp: 1600670628) repeated again the same error that i mentioned in video  ( samer707 commented on May 19 ) , (this is for because i respect stockfish company)

**Comment by vondele** [comment] 2020-09-22 19:32
I'll reopen this issue, but it is unclear what exactly the issue is.

**Comment by vondele** [comment] 2020-09-22 19:38
@skiminki I actually have an idea. With  485d517c687a2d3cb0b88cc8c198483759eaf2c7 to use large pages for the nets, we again have the output 
`info string Hash table allocation: Windows large pages not used.`
before any uci command which breaks certain GUIs. Also, this output is now somewhat wrong, as it appears on the allocation of the net variable. Could you have a look how this could be fixed?

**Comment by samer707** [comment] 2020-09-23 05:40
ok the problem i will explain again but by video , the problem is when i import engine ((Author: Sami Kiminki
Date: Mon Sep 21 08:43:48 2020 +0200
Timestamp: 1600670628Date: Mon Sep 21 08:43:48 2020 +0200
Timestamp: 1600670628)        that make chesspartner program freeze and stop

**Comment by samer707** [comment] 2020-09-23 05:43
but the versions before working good , the same problem happened before from the same developer and you fixed it , but problem returned again by this developer, (you can watch story of my chat) , remember i am not programmer to fix this , i want new version that fix this

**Comment by samer707** [comment] 2020-09-23 06:48
ok the video is here notice that Stefan Geschwentner - Timestamp: 1600669150 is working
but Sami Kiminki - Timestamp: 1600670628 is not working in chesspartner and make it freeze
![1233333](https://user-images.githubusercontent.com/65483350/93976195-48ab0f00-fd81-11ea-8e35-c96fb22fffba.gif)

**Comment by skiminki** [comment] 2020-09-23 08:06
> With 485d517 to use large pages for the nets, we again have the output

Sounds like a likely culprit.

> Could you have a look how this could be fixed?

The quick'n'dirty fix would be to suppress 2 first prints, instead of just one, and reformulate the info print a bit. However, this setup will remain as fragile as it is today.

For long-term, better fixes would be to do either or both:

(1) Deferred resource allocation on 'isready' or on the first 'go' command. Something similar to this one: https://github.com/skiminki/Stockfish/commit/607988fcdf2b1dd5e09ba63d59c0dcd7349a2fc2 

IIRC, the idea was rejected last time for the fear of timeout on 'go' if GUI/arena software is missing the 'isready' command. However, I only later realized that the timeout will happen even if resources are allocated on "setoption". Consider:

* setoption name Hash value 32768
* go wtime 1

The hash is still being resized when "go wtime 1" is sent. Timeout. That's why "isready" --> "readyok" synchronization is critical so that the GUI/arena knows when the engine is ready for the prime time.

Deferred allocations would also push the info strings to "isready", which is after "uci" by the protocol definition. There are also other benefits with deferred allocs, namely, faster engine init in case the GUI sends "Hash" before "Threads"

(2) Instead of printing out the use of large pages at alloc, maybe we could print them on "isready" as a summary. Something like:

```
> isready
< info Windows: large page memory not used
< readyok

> isready
< info Windows: large page memory used
< readyok

> isready
< info Windows: large pages used for some allocations but not for all.
< readyok
```

or

```
> isready
< info Windows: using 0 MB large page memory for requested total of 1234 MB
< readyok

> isready
< info Windows: using 1234 MB large page memory for requested total of 1234 MB
< readyok
```

**Comment by skiminki** [comment] 2020-09-23 10:10
Let’s get the dirty fix in first, and worry about longterm later? The print is still correct about hash table, since the weights alloc print gets suppressed. Pushed a PR

**Closed** 2020-09-25 15:45 UTC

**Comment by samer707** [comment] 2020-09-26 13:27
thank you , Respectable company stockfish and members , the problem solved in last ( Author: SFisGOD
Date: Fri Sep 25 17:44:19 2020 +0200
Timestamp: 1601048659
thank you

**Comment by samer707** [comment] 2020-09-29 09:11
something strange , when i want to select new developer engine as uci after importing it , it disappeared !! and not shown in select list ( software chesspartner )

**Comment by samer707** [comment] 2020-09-29 09:11
this is new problem

**Comment by samer707** [comment] 2020-09-29 09:14
sorry , thank you
