### ISSUE TITLE
Fishtest maintenance

### ISSUE THREAD

**Issue by mcostalba** [official-stockfish/Stockfish#1267] opened 2017-10-08 15:09 UTC
Fishtest development is practically stalled since 2 years.

We need someone well versed in phyton and with a good amount of time and energy to dedicate to it. I really don't have time enough and I can just keep SF maintenance, both Gary and Joona are very busy in their day job. OTH fishtest needs improvements and needs a dedicated maintainer.

**Comment by Stefano80** [comment] 2017-10-08 18:59
I agree and I would even volunteer. But I think my knowledge of database and server maintenance is just not enough (although I think I could help with stats and optimization).

**Comment by vondele** [comment] 2017-10-09 08:18
I agree that some modernization is needed, and it would benefit from more active maintainership. Presumably by adding a few more active maintainers to the official fishtest repo. 

@Stefano80, From my point of view, it is not needed to have a single person with all skills of Gary, a small team would be good as well, and reduce the bus-factor of fishtest. @ianfab and @ppigazzini have been doing quite some work on fishtest...

**Comment by student-t** [comment] 2017-10-09 11:38
It's unnecessary for a single person to take over the job. A few Python developers can do that. I'm happy to contribute if we have a team.

**Comment by Stefano80** [comment] 2017-10-09 15:40
Yes, if we could convince @ppigazzini to step up, I would gladly join more active development efforts. I was always somewhat discouraged from the inactivity of fishtest. (Without any criticism to Gary, let me be very explicit about that, everybody has a lot to do here...)

**Comment by ppigazzini** [comment] 2017-10-11 09:46
I have some spare time only at weekend, and I'm not a developer (I learnt some very basic python only to contribute some patches to fishtest). As many of you I think that looking for a @glinscott clone (developer, server administrator, github maintainer, chess developer, etc.) could be unsuccessful, perhaps it's better to try to build a team with all those skills.

I suggest this steps:
* start writing a list of new fishtest features & milestones
* build the team
then:
* fork fishtest to a new github repo
* develop and push the new features
* prepare a [test fishtest framework](https://github.com/glinscott/fishtest/wiki/Installing-a-development-fishtest-server-on-Ubuntu).
* test the new release of fishtest (server and worker) in the test fishtest framework.
* push the new features to the official fishtest server. The fishtest server atm uses some old python packages and there are some HW constrains (RAM, disk space, CPU)
* test the new features with some controlled workers
* push the new features to all workers

ps: I think that atm @ianfab is the person with the bigger knowledge of fishtest and fishtest administration (just below Gary) , but he is contributing the 99% of multivariant stockfish patches.

**Comment by Stefano80** [comment] 2017-10-11 17:47
Hi @ppigazzini , in principle I agree, I would reorder your plan as follows

- build the team (without it we go nowhere)
- put online a test fishtest framework
- decide again what to do and keep the ball rolling (I think how we test heavily depends on which kind of resources we will have for the test framework)

**Comment by ianfab** [comment] 2017-10-11 18:24
I will try to continue contributing to fishtest development, but I do not have much knowledge about server and database maintenance/administration (although at least being able to keep multi-variant fishtest somehow running most of the time) and I am also quite busy for the reasons @ppigazzini mentioned. So I could contribute to the code (even if it might be mostly minor improvements as in my open PRs), but not really to the server administration.

**Comment by ppigazzini** [comment] 2017-10-12 00:11
@Stefano80
* a team (a sort of) seems already here
* a development fishtest server with a basic hardening is on line in half a hour, here is a [fishtest instance](http://144.217.56.164:6543/tests), running with a CPU Broadwell 4 core + HT @ 2.4 GHz, 50 GB hard disk, 8 GB RAM (the HW features can be changed with a reboot, max RAM 64 GB)
* so here we are at the list of features and milestones :)

@mcostalba you never posted in the threads about the stalled fishtest development, so I'm curious to know the new features that you have in mind.

**Comment by student-t** [comment] 2017-10-12 00:17
We need a team leader. Someone who give general direction, otherwise we can't work as a team!

@mcostalba Do you want to be a team leader?

**Comment by Stefano80** [comment] 2017-10-12 04:14
Hi @ppigazzini, I think we need to work on 3 fields

General stability: 
We don't have a acceptance test environment for fishtest and we actually need one without which fishtest will remain inherently fragile.

Endgame testing: we need a concept to test TB patches and we need a endgames dataset for testing endgame patches.

Tuning: we need a concept to evaluate tuning strategies, and we need to put some hard work on improving SPSA, input from @ilvec would be probably useful.

What are your thoughts?

**Comment by ppigazzini** [comment] 2017-10-12 22:30
@Stefano80 I leave at developers the task to suggest new fishtest features chess related.

Some short term goals:
1. some clean up: naming convention (function and variables), function refactoring, remove dead code (windows builder), remove hard coded defaults (Linux, x86-64-modern), exception handling, etc.
Also some fishtest components are stored in a different repo ([opening books & cutechess-cli](https://github.com/mcostalba/FishCooking/tree/setup)). cutechess-cli is very old and not built static (on Linux QT is a prerequisite, the old cutechess-cli does not close cleanly on MSYS2 python)
2. some new features: system info collection, compile options CPU based, nps computing as average on several benches etc.
3. comments and documentation.

Some medium term goals:
1. pgn collection, speedup test, other chess related features
2. optional: MSYS2 MinGW-w64 & python as default for Windows (here I'm biased)

Some long term goals:
1. user & worker management etc.
2. tests search
3. python 3 ?

Regarding the acceptance test, I think that atm it suffix to follow this workflow:
1. test locally with a development server and some workers (windows, linux), using some VMs. I use lxc/lxd to test some features with several distros (ubuntu, centos, arch etc.)
2. if necessary test with some cloud development servers and to have a bigger number of workers
3. the worker patches are more difficult to test thoroughly (e.g. I haven't a mac)

**Comment by mcostalba** [comment] 2017-10-22 18:08
What about this one?

![image](https://user-images.githubusercontent.com/1099265/31864668-9ce6daae-b761-11e7-9261-2011607f406a.png)

1. All tests in one page (with infinite scrolling btw)
2. Led (green/yellow/gray) on the left to show started, pending or finished state
3. New graphic and arrangement of the columns
4. Black border of the score box to show LTC tests
5. Link rendering in the test description column
6. Fancy date format
7. Number of active machines for each running test (see the number under the green led)

It is done in [go language](https://golang.org/) (actually it is a way for me to learn 'go', because I am totally new at it). It reads from the same MongoDB of official fishtest, fetching data from there (through a private VPN), so it is in strictly read-only mode to avoid any issues for the official fishtest site.

**Comment by Stefano80** [comment] 2017-10-22 18:12
I like it better than current. What does it cX tY after the score?

**Comment by mcostalba** [comment] 2017-10-22 18:51
@Stefano80 crashes and time losses

**Comment by mcostalba** [comment] 2017-10-22 18:51
@Stefano80 crashes and time losses

**Comment by Yery** [comment] 2017-10-24 18:40
For what it is worth: This new layout looks great! Strange there is so little enthusiasm.

**Comment by Stefano80** [comment] 2017-10-24 18:52
I find it great too! Should have said with more emphasis!

**Comment by xoto10** [comment] 2017-10-25 11:32
Looks great!

I have one question, is it possible to include part of the commit ref in
the test name? If people (I am guilty of this!) submit multiple tests with
altered code on the same branch, we need to click on the test to remember
which code version it is. A couple of letters from the commit ref giving
test_name_xy instead of test_name might be a bit easier to follow.

**Comment by mcostalba** [comment] 2017-10-26 16:09
@xoto10 this is a good idea. I will do. Thanks.

**Comment by mcostalba** [comment] 2017-10-26 16:26
Here e go:

![image](https://user-images.githubusercontent.com/1099265/32064748-090290c2-ba7b-11e7-94da-2e0df5275aed.png)

I have replace the 3 ellipsis with the first 4 digits of the sha of new commit.

**Comment by mcostalba** [comment] 2017-10-28 11:34
I have added the machines page (open clicking on the number under the green leds):

![image](https://user-images.githubusercontent.com/1099265/32133978-5709b1a6-bbe3-11e7-9c48-b6b5c637bf27.png)

1. Modal view with machines grouped by collapsing elements for each active test
2. View is rendered fully on client-side: immediate and withouth requests to the server
3. Visual and animated summary for assorted stats
4. Same information further detailed for each task
5. Show idle workers (more than 5 minutes) with proper idle color (light gray)

**Comment by joergoster** [comment] 2017-10-28 15:48
Looks great!

**Comment by xoto10** [comment] 2017-10-29 13:13
I had another thought. Is it possible to display the wins and losses for
each colour, or is this information not available from cutechess?

**Comment by mcostalba** [comment] 2017-10-29 13:38
@xoto10 no, I don't think it is available in fishtest (I am not sure for cutechess).

**Comment by crossbr** [comment] 2017-11-15 04:16
Marco, I think it would helpful to have a real-time graph for each test, the x-axis being number of games played, and the y-axis being the current LLR value, along with the upper and lower bounds for passing and failing. That way you could see a test's history, and also see visually how close it was and is to passing or failing. -Bryan

**Comment by vondele** [comment] 2017-11-19 20:22
@crossbr I have implemented a python script to do that, see
https://groups.google.com/d/msg/fishcooking/0QTFBQJcuas/WQro-FSTAQAJ
or
https://github.com/vondele/FishTestWatch

**Comment by mcostalba** [comment] 2017-11-19 20:32
@crossbr yes, this is a good idea but it requires an update to the DB (or using an external DB)

@vondele nice! Indeed in the very few free time, I implemented live update functionality. This can't be shown with a screenshot but it means that main page and machine page are not static but change lively while you are watching :-) reflecting changes in the underlying data. I have used a websocket to keep a connection alive between server and browser and push updates to the browser view: learning a lot of new stuff in the process...

**Comment by xoto10** [comment] 2017-12-03 11:39
@mcostalba 
Would dates be better displayed in YYYY-MM-DD format?
Could you display number of active cores instead of active machines?

> 6. Fancy date format
> 7. Number of active machines for each running test (see the number under the green led)

**Comment by xoto10** [comment] 2017-12-03 11:42
My suggestion is we get one or two of the smallest things fixed asap.
e.g. how do we get the timeout changed back from 30 minutes to 5 minutes?

**Comment by Stefano80** [comment] 2017-12-17 19:10
Btw, this thread was about stalled fishtest. Are we going anywhere with that? I thought there was some kind of agreement that @ppigazzini (and I) would be interested and available to do some work. @mcostalba: thoughts from your side?

**Comment by IIvec** [comment] 2017-12-28 21:03
I now see that I was mentioned here. I think that fishtest should be open for 2 different tuners and then the worse one could in the future be replaced with new attempt.

Also, some strong opening books could reduce statistical errors significantly. I developed 2moves_strong book and I'm doing statistical analysis for it at the moment.

**Comment by glinscott** [comment] 2018-01-02 05:35
This is great @mcostalba!

Of course, I'd be more than happy to hand over the keys to fishtest.  I'm happy to keep the server up, but I just don't have time to update the code these days.  I don't want to make changes because it's so damn stable now :).  But if someone else is willing to take it on, that would be great!

**Comment by glinscott** [comment] 2018-01-02 05:57
@Stefano80 and @ppigazzini I've invited you as collaborators on the fishtest repo.  Give me an email at glinscott@gmail.com, and I'll give you credentials to the server.

**Comment by ppigazzini** [comment] 2018-01-02 11:48
@glinscott : done
@mcostalba @Stefano80 : we need a list of features and milestones

**Comment by Stefano80** [comment] 2018-01-02 14:24
Hi @ppigazzini , @mcostalba : I think the first milestone is to decide what to do with the several PRs open on the repository.

**Comment by CoffeeOne** [comment] 2018-01-05 11:52
Sorry to say, but ...
Not only fishtest development is stalled, also fishtest **maintenance** is stalled, which is more critical.
The workers get 
Timeout: HTTPConnectionPool(host='tests.stockfishchess.org', port=80): Request timed out. (timeout=5.0) 
more and more often

**Comment by CoffeeOne** [comment] 2018-01-05 14:06
@ppigazzini At the moment only 15 workers are working and there is still something to do, so something IS defenitely wrong.

**Comment by IIvec** [comment] 2018-01-05 14:41
Hi all,

with each new refresh I see different tests running. Sometimes, I see all of them, but sometimes only some of them. This alert is important.

**Comment by joergoster** [comment] 2018-01-05 14:43
@IIvec Same here. Although it mainly affects only one test not being displayed at a time, and next time it's there again.

**Comment by ppigazzini** [comment] 2018-01-05 15:01
@IIvec try to stop the "tune_nmb" to view if this solve the problem.
I have some free time only in the week end and I prefer to not touch anything on the production server before I figured out the whole configuration.
My plan is to write a new fishtest server installer for CentOS and to have some servers as test/backup.

**Comment by IIvec** [comment] 2018-01-05 15:07
@ppigazzini : OK, stopped, it seems that I anyway have enough data from that test.

**Comment by ppigazzini** [comment] 2018-01-05 15:48
@IIvec thank you. BTW I used "stop" but I intended "suspend", Next time I will chose the word more carefully.

**Comment by joergoster** [comment] 2018-01-05 15:54
Maybe these problems are a general problem atm. I also experience problems reaching other sites or streaming via Fire-TV ...

**Comment by ppigazzini** [comment] 2018-01-05 16:13
@joergoster this is already known problem for tuning sessions with many parameters.

**Comment by IIvec** [comment] 2018-01-05 22:50
@ppigazzini : I guess the problem was the number og games (500000) and not the number of parameters (33).

**Comment by mcostalba** [comment] 2018-01-13 08:10
@ppigazzini thank you for picking up this!

I don't have milestones to give you, you are mainly free to develop in areas where you see possible improvements. Anyhow the critical job, apart from development, is maintenance and in particular fixing bugs and addressing issues (luckily very few, although code base is mostly stalled since years).

In case you are looking for ideas, I'd suggest to post a specific topic on the forum, although, beware, you will receive _many_ feature requests, not all valuable and you have to be prepared to filter them out and to explain why you consider them not acceptable: this is, by far, the most difficult part of maintainer job :-)

**Comment by ppigazzini** [comment] 2018-01-13 11:15
@mcostalba : OK, message received.
ATM @Stefano80 is reviewing the PRs on GitHub (I'm still not so confident w/ git), I'm in charge for the server administration tasks.

**Comment by vondele** [comment] 2018-01-13 12:45
@ppigazzini not sure if this is a server admin related thing... i assume there is more details in some log somewhere...

I'm seeing (since a long time) the following error message on (first) login to fishtest, e.g. to modify the state of a test:
```
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```
somehow I'm nevertheless logged in afterwards, so I can with a few extra clicks ignore it, but would be nice to get rid of it.

**Comment by ianfab** [comment] 2018-01-13 13:11
In case someone wants to pick them up, here are a few ideas (some of which might have been mentioned before in this thread, I have not checked) I would like to implement or at least think through further but did not have the time yet:
- add support for speed measurements, i.e., distributed bench testing
- add an option to disable auto-purge per test
- show bad tasks in a table below the tasks of a test, but still do not include them in the stats of the test. So far stats of bad tasks are deleted, so this would only work for new tests.
- tags on tests (added by test author, editable by maintainers, possibly only selectable from a predefined set) to enable better filtering of the test list
- remove or fix the test type "regression"
- make internal priority depend on LLR (for ideas on the formulae, see https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/lH9I0Kajb7I)
- add a field to input an EPD (with limited size) for a test
  - to support custom books (e.g., endgame positions or the like)
  - and/or add support for test suite testing (maybe using python-chess)
- in addition to the score from the first engine's point of view, report the score from white's point of view (only on the test details page)
- probably there could be more minor usability improvements similar to some of my previous PRs, e.g., regarding test submission, displaying and browsing of tests list, etc. Here feedback from users might be helpful.

I would also like to get rid of the error message @vondele mentioned which I also often encounter, but I have not investigated yet where this is coming from.

**Comment by Mindbreaker1** [comment] 2018-01-23 11:48
Honestly, I like it a lot the way it is, with a few minor changes: draw percentages, and a next/previous page button at the bottom.  And I would like to see more opening book options, particularly various endgames. Maybe 30 books each focused on one kind of ending.  Then we can improve our endings and judge endings from afar more accurately.  Though an automatic 30 second refresh mode would be nice for following progress.  And though completely eye candy, it would be nice to see a graph of how a patch did during testing...its ups and downs...how close it came to passing...
Maybe distinguish more clearly between patches testing for Elo and those just trying to avoid regressing. Maybe a darker shade of green, red, yellow for the attempts at Elo gain vs the others.

I did make a bunch of ending books, but they haven't been checked for large advantages and such.  Some I haven't even run.  And they have repeated positions because I just used our 2-move book and removed pieces (the duplicate removers I tried required that there be games, not just positions).  And there are 5 or 6 that someone else made so I could do some testing a couple years ago.  There could be all kinds of problems with the books I made, I don't know.  But maybe it is a starting point.

[2moves_v1__endgames.zip](https://github.com/official-stockfish/Stockfish/files/1655673/2moves_v1__endgames.zip)

**Comment by Mindbreaker1** [comment] 2018-01-23 11:53
I probably should think about those ending choices better and come up with a better set.  And test them to insure they work.

**Comment by Mindbreaker1** [comment] 2018-01-23 18:00
You know what? The white is hard on the eyes.  I don't like grey-white-grey.  I do like your expansion of the names. But could they be under or over the name of the test to reduce the width?

**Comment by Mindbreaker1** [comment] 2018-01-23 18:11
Ooo, is the rollover revel of the details of the commits new?  I like that.

**Comment by Mindbreaker1** [comment] 2018-01-23 19:41
Testing in Little Blitzer my endgame openings appear to be broken. In Fritz they mostly work.  I think I know what is wrong.

**Comment by vondele** [comment] 2018-01-24 16:50
@ppigazzini another server thing would be to move http://tests.stockfishchess.org/ to https that would get rid of some of the warnings a browser gives on input of login/password.

**Comment by ppigazzini** [comment] 2018-01-24 17:02
@vondele let me know which browser you are using. I will try on the [dev server](http://94.198.98.239/tests) (I think that I will need to configure let's encrypt).

**Comment by vondele** [comment] 2018-01-24 17:12
This is the warning (using firefox 57.0.4):
https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox?as=u&utm_source=inproduct
yes, I think using a let's encrypt certificate is the right idea.

**Comment by Mindbreaker1** [comment] 2018-01-31 04:24
I have attached a number of endgame books. I have tested them. And they have no obvious issues I can detect.  There are still at least 4 more I would like to include, but they will require a little more work, because I have to remove some pawns from the stronger side to make them reasonably close.

They all have between 14 and 16 pawns so there is still a lot of play left in the games.

I haven't removed duplicates or removed extremely one-sided positions.  Though, if a lot of games are played, it should not make much difference.
[Endgame.zip](https://github.com/official-stockfish/Stockfish/files/1680382/Endgame.zip)

**Comment by Stefano80** [comment] 2018-01-31 19:37
Answered here https://github.com/glinscott/fishtest/issues/139

**Comment by Stefano80** [comment] 2018-01-31 19:37
Let us move this to fishtest repo.

**Comment by snicolet** [comment] 2018-03-08 08:15
@tomtor would you be interested to help @Stefano80 and @ppigazzini as fishtest maintainers?

**Comment by ppigazzini** [comment] 2018-05-26 09:39
I think that this Issue can be closed :)

**Comment by snicolet** [comment] 2018-05-26 09:51
Yep, thanks to all :-)

**Closed by snicolet** 2018-05-26 09:51 UTC
