### ISSUE TITLE
Compilation error on Ubuntu 16.04

### ISSUE THREAD

**Issue by iw6dgm** [official-stockfish/Stockfish#3177] opened 2020-10-11 10:24 UTC
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)

make build ARCH=x86-64-ssse3
(tried with other archs, same result)

`Default net: nn-baeb9ef2d183.nnue
Already available.
make ARCH=x86-64-ssse3 COMP=gcc all
make[1]: Entering directory '/home/joshua/src/Stockfish/src'
g++ -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o benchmark.o benchmark.cpp
In file included from nnue/architectures/../features/features_common.h:25:0,
                 from nnue/architectures/../features/feature_set.h:24,
                 from nnue/architectures/halfkp_256x2-32-32.h:24,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from benchmark.cpp:24:
nnue/architectures/../features/../nnue_common.h:69:15: error: expected ‘{’ before ‘::’ token
 namespace Eval::NNUE {
               ^
nnue/architectures/../features/../nnue_common.h:69:17: error: ‘NNUE’ in namespace ‘::’ does not name a type
 namespace Eval::NNUE {
                 ^
In file included from nnue/architectures/../features/feature_set.h:24:0,
                 from nnue/architectures/halfkp_256x2-32-32.h:24,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from benchmark.cpp:24:
nnue/architectures/../features/features_common.h:27:15: error: expected ‘{’ before ‘::’ token
 namespace Eval::NNUE::Features {
               ^
nnue/architectures/../features/features_common.h:27:17: error: ‘NNUE’ in namespace ‘::’ does not name a type
 namespace Eval::NNUE::Features {
                 ^
In file included from nnue/architectures/halfkp_256x2-32-32.h:24:0,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from benchmark.cpp:24:
nnue/architectures/../features/feature_set.h:27:15: error: expected ‘{’ before ‘::’ token
 namespace Eval::NNUE::Features {
               ^
nnue/architectures/../features/feature_set.h:27:17: error: ‘NNUE’ in namespace ‘::’ does not name a type
 namespace Eval::NNUE::Features {
                 ^
In file included from nnue/architectures/halfkp_256x2-32-32.h:25:0,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from benchmark.cpp:24:
nnue/architectures/../features/half_kp.h:27:15: error: expected ‘{’ before ‘::’ token
 namespace Eval::NNUE::Features {
               ^
nnue/architectures/../features/half_kp.h:27:17: error: ‘NNUE’ in namespace ‘::’ does not name a type
 namespace Eval::NNUE::Features {
                 ^
In file included from nnue/architectures/halfkp_256x2-32-32.h:27:0,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from benchmark.cpp:24:
nnue/architectures/../layers/input_slice.h:26:15: error: expected ‘{’ before ‘::’ token
 namespace Eval::NNUE::Layers {
               ^
nnue/architectures/../layers/input_slice.h:26:17: error: ‘NNUE’ in namespace ‘::’ does not name a type
 namespace Eval::NNUE::Layers {
                 ^
In file included from nnue/architectures/halfkp_256x2-32-32.h:28:0,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from benchmark.cpp:24:
nnue/architectures/../layers/affine_transform.h:27:15: error: expected ‘{’ before ‘::’ token
 namespace Eval::NNUE::Layers {
               ^
nnue/architectures/../layers/affine_transform.h:27:17: error: ‘NNUE’ in namespace ‘::’ does not name a type
 namespace Eval::NNUE::Layers {
                 ^
In file included from nnue/architectures/halfkp_256x2-32-32.h:29:0,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from benchmark.cpp:24:
nnue/architectures/../layers/clipped_relu.h:26:15: error: expected ‘{’ before ‘::’ token
 namespace Eval::NNUE::Layers {
               ^
nnue/architectures/../layers/clipped_relu.h:26:17: error: ‘NNUE’ in namespace ‘::’ does not name a type
 namespace Eval::NNUE::Layers {
                 ^
In file included from nnue/nnue_architecture.h:25:0,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from benchmark.cpp:24:
nnue/architectures/halfkp_256x2-32-32.h:31:15: error: expected ‘{’ before ‘::’ token
 namespace Eval::NNUE {
               ^
nnue/architectures/halfkp_256x2-32-32.h:31:17: error: ‘NNUE’ in namespace ‘::’ does not name a type
 namespace Eval::NNUE {
                 ^
In file included from nnue/nnue_accumulator.h:24:0,
                 from position.h:31,
                 from benchmark.cpp:24:
nnue/nnue_architecture.h:27:15: error: expected ‘{’ before ‘::’ token
 namespace Eval::NNUE {
               ^
nnue/nnue_architecture.h:27:17: error: ‘NNUE’ in namespace ‘::’ does not name a type
 namespace Eval::NNUE {
                 ^
In file included from position.h:31:0,
                 from benchmark.cpp:24:
nnue/nnue_accumulator.h:26:15: error: expected ‘{’ before ‘::’ token
 namespace Eval::NNUE {
               ^
nnue/nnue_accumulator.h:26:17: error: ‘NNUE’ in namespace ‘::’ does not name a type
 namespace Eval::NNUE {
                 ^
In file included from benchmark.cpp:24:0:
position.h:60:9: error: ‘NNUE’ in namespace ‘Eval::Eval::Eval::Eval::Eval::Eval::Eval::Eval::Eval::Eval’ does not name a type
   Eval::NNUE::Accumulator accumulator;
         ^
benchmark.cpp:170:1: error: expected ‘}’ at end of input
 }
 ^
benchmark.cpp:170:1: error: expected ‘}’ at end of input
benchmark.cpp:170:1: error: expected ‘}’ at end of input
benchmark.cpp:170:1: error: expected ‘}’ at end of input
benchmark.cpp:170:1: error: expected ‘}’ at end of input
benchmark.cpp:170:1: error: expected ‘}’ at end of input
benchmark.cpp:170:1: error: expected ‘}’ at end of input
benchmark.cpp:170:1: error: expected ‘}’ at end of input
benchmark.cpp:170:1: error: expected ‘}’ at end of input
benchmark.cpp:170:1: error: expected ‘}’ at end of input
<builtin>: recipe for target 'benchmark.o' failed
make[1]: *** [benchmark.o] Error 1
make[1]: Leaving directory '/home/joshua/src/Stockfish/src'
Makefile:715: recipe for target 'build' failed
make: *** [build] Error 2
`

interestingly, this is the first version I try to compile after the NNUE code was added. Prior this update (few months ago) I was always able to compile Stockfish on this platform.

**Comment by vondele** [comment] 2020-10-11 10:39
Stockfish now requires C++17, and thus a compiler that supports it. gcc >7.5 should work.

**Comment by iw6dgm** [comment] 2020-10-11 10:47
Thanks for your prompt reply. I suspected it was a compatibility issue.
It would be nice having those requirements stated in the documentation (README) and/or in the Makefile: alternatively you can let the `make` to abort if the compiler versions are not met.

**Comment by vondele** [comment] 2020-10-11 11:01
The compilation flags set by the Makefile include `-std=c++17` so it is more surprising the compiler accepts it, but actually doesn't implement it properly. If the issue is resolved for you, please close it.

**Closed** 2020-10-11 11:03 UTC
