### ISSUE TITLE
Endgame score

### ISSUE THREAD

**Issue by Marat-Ka** [official-stockfish/Stockfish#3196] opened 2020-10-24 15:00 UTC
SF and its clones give strange results when playing and analyzing.
 7k/3K2p1/6Pp/7P/8/8/8/7B b - - 0 68 

https://live.staticflickr.com/65535/50522628868_e0ff54c620_o.jpg

![50522628868_e0ff54c620_o](https://user-images.githubusercontent.com/51216501/97085213-b8344880-1624-11eb-97eb-cb40aab2bded.jpg)

The engine uses six-figure tables.
Seven-figure tables are not involved, but if they are included, the score is correct: 0.0.

[Game.txt](https://github.com/official-stockfish/Stockfish/files/5433046/Game.txt)

My SF plays black.

**Comment by vondele** [comment] 2020-10-24 15:14
I can't reproduce that here. The score is not great, but not a TB win:
```
info depth 77 seldepth 99 multipv 1 score cp -314 nodes 191359547 nps 29201823 hashfull 88 tbhits 7457 time 6553 pv h8g8 d7e7 g8h8 h1b7 h8g8 e7e8 g8h8 b7e4 h8g8 e4d5 g8h8 d5b7 h8g8 b7e4 g8h8 e8d7 h8g8 d7c7 g8f8 c7d6 f8e8 e4c6 e8f8 c6d7 f8g8 d7h3 g8f8 h3e6 f8e8 e6g8 e8f8 g8c4 f8e8 d6e6 e8f8 c4d5 f8e8 d5b7 e8f8 e6d7 f8g8 d7c7 g8f8 b7e4 f8e7 c7c6 e7e8 e4f3 e8e7 c6d5 e7f8 f3d1 f8e7 d1e2 e7f8 d5d6 f8e8 d6c7 e8e7 e2f1 e7e8 f1b5 e8f8 c7c8 f8e7 b5d3 e7f8 c8d7 f8g8 d7c7 g8f8 c7c6 f8g8 c6d5 g8f8 d5e5 f8e7 d3b5 e7f8 b5a6 f8e7 a6b7 e7f8 e5e6 f8g8 b7d5 g8f8 d5c4 f8g8 e6e7 g8h8 c4a6 h8g8 a6e2 g8h8 e7d8 h8g8 e2c4 g8h8
```
Right now, I would like to exclude that you have corrupted TB files. Did you verify the md5sum of them?

**Comment by Marat-Ka** [comment] 2020-10-24 15:20
We analyzed this on at least two different systems: me during the game, and another volunteer just started an analysis from the provided FEN.

I guess it's unlikely that the problem is broken tables.

**Comment by vondele** [comment] 2020-10-24 15:24
OK, can you provide the exact lUCI commands needed to reproduce it in that case? If I analyze from the FEN it doesn't happen. Does it always happen, and with how many threads?

**Comment by Marat-Ka** [comment] 2020-10-24 15:28
I do not know how to do this, but I attached the game above, there are estimates as the game progresses until the engine is handed over on my side.

This is enough?

And in addition, analysis with cFish from FEN was still possible. But there are almost 50 threads.

**Comment by Marat-Ka** [comment] 2020-10-24 15:33
p.s.
I am using an eight-core AMD FX, and SF also showed this estimate, but a little later.

**Comment by JavaMast** [comment] 2020-10-24 15:39
@Marat-Ka 
on your PC, SF and CF scores +3.xx , not +151, correct?

**Comment by vondele** [comment] 2020-10-24 15:42
scores of +3 are not nice, but typical in this situation, a score of +151 would be wrong however.

**Comment by Marat-Ka** [comment] 2020-10-24 15:45
Yes, but...  later SF also shows this scores .

https://forchess.ru/showpost.php?p=156971&postcount=12793

8/4k1p1/2K3Pp/7P/6B1/8/8/8 b - - 0 78
position at the moment when SF surrendered, SF score 151.xx

**Comment by syzygy1** [comment] 2020-10-24 17:18
If this happens only with TBs enabled and is reproducable on your system, this looks like corrupt files. I can't reproduce it either.

**Comment by Marat-Ka** [comment] 2020-10-24 17:43
I know at least three systems where this takes place: my system, the system of my opponent on PlayChess, and a separate analysis from FEN (see screenshot above).

**Comment by syzygy1** [comment] 2020-10-24 19:21
If all these systems got their tables from the same source it would be expected rather than incredible. Did you check the md5sums already?

If you have checked them and they are all fine, please tell us how to reproduce the problem. For example:
$ ./stockfish
Stockfish 241020 by the Stockfish developers (see AUTHORS file)
setoption name SyzygyPath value /path/to/6-piece-TBs
info string Found 510 tablebases
position fen 7k/3K2p1/6Pp/7P/8/8/8/7B b - - 0 68
go infinite
info string NNUE evaluation using nn-eba324f53044.nnue enabled
info depth 1 seldepth 1 multipv 1 score cp -341 nodes 4 nps 4000 tbhits 0 time 1 pv h8g8 h1d5 g8f8
info depth 2 seldepth 3 multipv 1 score cp -341 nodes 11 nps 11000 tbhits 0 time 1 pv h8g8 h1d5 g8f8
info depth 3 seldepth 4 multipv 1 score cp -326 nodes 33 nps 33000 tbhits 0 time 1 pv h8g8 h1c6 g8f8
...
info depth 70 currmove h8g8 currmovenumber 1
info depth 70 seldepth 100 multipv 1 score cp -272 nodes 14965039 nps 2382967 hashfull 84 tbhits 7490 time 6280 pv h8g8 h1d5 g8h8 d5e4 h8g8 d7e8 g8h8 e4d3 h8g8 e8e7 g8h8 d3f5 h8g8 f5h3 g8h8 e7d6 h8g8 d6e6 g8f8 e6d7 f8g8 d7c8 g8h8 c8c7 h8g8 h3e6 g8h8 e6c8 h8g8 c8b7 g8f8 c7d7 f8g8 d7e8 g8h8 b7e4 h8g8 e4a8 g8h8 e8e7 h8g8 e7e6 g8f8 e6d7 f8g8 d7c8 g8f8 a8e4 f8e8 e4b7 e8e7 b7c6 e7f8 c8d7 f8g8 d7e6 g8f8 c6b5 f8g8 b5f1 g8f8 e6d6 f8e8 f1b5 e8f8 b5a4 f8g8 a4e8 g8f8 d6d7 f8g8 d7c6 g8f8 e8d7 f8e7 c6c7 e7f8 d7e6 f8e7 e6b3 e7e8 b3f7 e8e7 c7c6 e7f8 f7e6 f8e7 c6d5 e7f8 d5d6 f8e8 e6c8 e8d8 d6e6 d8e8 c8d7 e8f8 e6f5 f8g8

**Comment by noobgame** [comment] 2020-10-25 08:29
![Screenshot_1593](https://user-images.githubusercontent.com/63532306/97102281-3ccea780-16b5-11eb-9cab-6ec07821c023.png)
my eval is 3.5 + its normal?

**Comment by vondele** [comment] 2020-10-25 08:31
3.5 is 'normal' (but not good). A table base win score (~150) would be a bug.

**Comment by Marat-Ka** [comment] 2020-10-25 11:14
> Did you check the md5sums already?
I just checked it out. Everything is good.


> If you have checked them and they are all fine, please tell us how to reproduce the problem. For example:
I don't know how to reproduce this issue.
I have attached pgn above, maybe this will help you understand.

**Comment by Marat-Ka** [comment] 2020-10-25 11:15
Sorry, I missed the button and closed the problem.

**Comment by Sopel97** [comment] 2020-10-25 11:50
the PGN won't help. Either provide exact reproduction steps or this issue can't be investigated.

**Comment by syzygy1** [comment] 2020-10-25 12:33
Can you open a DOS prompt? Then you can type what I typed:
stockfish
setoption name SyzygyPath value /bla/bla
position fen blabla
go infinite

**Comment by syzygy1** [comment] 2020-10-25 12:34
If it only happens with a particular hash table size (e..g 4096MB), then set it with
set option name Hash value 4096

**Comment by joergoster** [comment] 2020-10-25 12:56
Incomplete TBs?
Misconfigured GUI?

**Comment by syzygy1** [comment] 2020-10-25 13:00
It's an interesting game. White seems to be confused starting from 55.Be6 (where 55.d5 seems to have been much better) and throws away the win with 59.Rxc8. Black then gets equally confused starting from 75...Ke8.

Maybe this is a bug, but I really doubt that this is reproducible even for you. However, if you can show how to reproduce it reliably, we can fix it (or at least find the explanation).

**Comment by Marat-Ka** [comment] 2020-10-25 13:06
> Can you open a DOS prompt? Then you can type what I typed:
> stockfish
> setoption name SyzygyPath value /bla/bla
> position fen blabla
> go infinite

I try:

setoption name Threads value 8
setoption name Hash value 8192
setoption name SyzygyProbeLimit value 6
setoption name SyzygyPath value c:\wdl
position fen 8/1K1k2p1/6Pp/7P/6B1/8/8/8 b - - 0 77
go infinite

fen 8/1K1k2p1/6Pp/7P/6B1/8/8/8 b - - 0 77 - it's position before black resign.

**Comment by syzygy1** [comment] 2020-10-25 13:14
OK, it seems I am able to reproduce it....
Now using 4 threads and 6-piece tables. It wants to play 55.Be6 and a few moves later I am getting +152 scores.

**Comment by Sopel97** [comment] 2020-10-25 13:59
may be worth to try with https://github.com/official-stockfish/Stockfish/pull/2755

**Comment by syzygy1** [comment] 2020-10-25 15:18
I still haven't been able to reproduce it from the position at move 77, but it is clear for me that the problem is real.

Since the PVs I saw does not end in a TB position, it seems the incorrect +152 score is coming out of the hash table. SF's PV search() does not return TT values, but qsearch() does. (I have tried to "fix" that in the past but the fix loses Elo.)

What is less clear to me is whether the incorrect value is caused by a hashing error (so the +152 corresponds to a different position but the TT probing code doesn't realise that) or by some complicated graph history interaction problem. (In the past I have several times blamed the "sardines" patch that greatly increased the number of undetected collisions, but the real cause was usually/always the graph history interaction problem, which simply cannot be fixed without losing hundreds of Elo.)

**Comment by Sopel97** [comment] 2020-10-25 15:26
if you're not able to reproduce from the later positions it's likely a hash issue

**Comment by joergoster** [comment] 2020-10-26 11:04
> I try:
> 
> setoption name Threads value 8
> setoption name Hash value 8192
> setoption name SyzygyProbeLimit value 6
> setoption name SyzygyPath value c:\wdl
> position fen 8/1K1k2p1/6Pp/7P/6B1/8/8/8 b - - 0 77
> go infinite
> 
> fen 8/1K1k2p1/6Pp/7P/6B1/8/8/8 b - - 0 77 - it's position before black resign.

@Marat-Ka And what does the engine respond after `setoption name SyzygyPath value c:\wdl `?

Please also note, the correct fen at move 77 is 8/1K1k2p1/6Pp/7P/6B1/8/8/8 b - - 18 77

**Comment by Marat-Ka** [comment] 2020-10-26 11:14
> @Marat-Ka And what does the engine respond after `setoption name SyzygyPath value c:\wdl `?

info string Found 517 tablebases

**Comment by joergoster** [comment] 2020-10-26 11:23
`info string Found 510 tablebases` is the correct answer for 6-man bases.

**Comment by syzygy1** [comment] 2020-10-26 11:25
I guess @Marat-Ka has a few 7-piece TBs and therefore set SyzygyProbeLimit to 6.

**Comment by joergoster** [comment] 2020-10-26 11:28
@syzygy1 Hmm, shouldn't the 7-piece files simply being ignored then?

**Comment by Marat-Ka** [comment] 2020-10-26 11:29
> I guess @Marat-Ka has a few 7-piece TBs and therefore set SyzygyProbeLimit to 6.

yes, it's true


KNPPPPvK.rtbw
KPPPvKPP.rtbw
KQPPPPvK.rtbw
KQPPvKPP.rtbw
KQPPvKQQ.rtbw
KRPPPPvK.rtbw
KRPPvKQR.rtbw

**Comment by Marat-Ka** [comment] 2020-10-26 15:18
> OK, it seems I am able to reproduce it....
> Now using 4 threads and 6-piece tables. It wants to play 55.Be6 and a few moves later I am getting +152 scores.

 58. d6 #63

It seems to me that this is also not a very correct score, which has the same reason.

**Comment by Marat-Ka** [comment] 2020-10-26 16:14
> 3.5 is 'normal' (but not good). A table base win score (~150) would be a bug.

I want to ask a strange question: why is this "normal"?

Pawns are not passed pawns, and mate with one bishop is impossible, this is a typical "fortress".
White's win is impossible without Black's erroneous play, but can Black itself win if White makes a mistake, or not?
It seems to me that the estimate ~ 3-4 is just an score of an extra bishop (3-4 pawns), nothing more.

It is unbelievable that the engine cannot see it in such a low-figured position.

**Comment by joergoster** [comment] 2020-10-26 16:22
@Marat-Ka Was the game played under the Fritz GUI? Did you also provide the TBs to the GUI?

If yes, this is probably more an issue of the GUI than of the engine ...

**Comment by Marat-Ka** [comment] 2020-10-26 16:25
> Was the game played under the Fritz GUI?

Yes



> Did you also provide the TBs to the GUI?

only for engine

![1](https://user-images.githubusercontent.com/51216501/97199305-ed759d80-17c0-11eb-9520-6a7e6ac77fff.PNG)
![2](https://user-images.githubusercontent.com/51216501/97199329-f23a5180-17c0-11eb-98f1-172764fd764a.PNG)

**Comment by vondele** [comment] 2020-10-26 16:29
> > 3.5 is 'normal' (but not good). A table base win score (~150) would be a bug.
> 
> I want to ask a probably strange question: why is this "normal"?
> 
> Pawns are not passed pawns, and mate with one bishop is impossible, this is a typical "fortress".

yes, the typical ('normal') wrong score in a fortress position. Unless search reaches the 50mr counter, hard for an engine to see that the material advantages leads nowhere. So, normal in that it is an understood behavior, and nobody has a fix that doesn't cost Elo in general.

The 150 scores are more of a concern, as they suggest the engine found a line to TB won position, and that obviously can't happen.

**Comment by Marat-Ka** [comment] 2020-10-26 16:30
I understand. Thanks!

**Comment by syzygy1** [comment] 2020-10-26 16:31
@Marat-Ka 
It is extremely difficult to let the hand-crafted evaluation accurately detect fortresses in general. It could be done for this particular case, of course, but that wouldn't help for other positions.

The network in fact handles this case quite well (set "Use NNUE" to "pure" in Cfish). In SF's hybrid mode, this position is apparently evaluated by the hand-crafted evaluation.

**Comment by Marat-Ka** [comment] 2020-10-26 16:33
Let's use pure NNUE?
It seems to me that it is not very difficult to make such an option?

**Comment by syzygy1** [comment] 2020-10-26 16:39
Use Cfish or prove that pure is stronger.
It is probably just luck that the NNUE evaluation somehow does well on this position. You can probably find positions that are not a fortress but are evaluated close to a draw by NNUE.

**Comment by Marat-Ka** [comment] 2020-10-26 16:45
sFish is faster, I'm not sure if it can be checked even on time control like 180+
Also, I prefer to use the original over the clone.

However, this is another topic for discussion.

Now it would be interesting to know how realistic it is to fix the existing problem.

If it costs 5 or 10 Elo, I think it's a good option, because the difference in Elo can be returned in a month or so, but without this problem.

**Comment by syzygy1** [comment] 2020-10-26 16:50
You can forget about individual positions receiving individual fixes. There are billions of positions to fix, so with your calculation that will quickly give Stockfish a negative Elo.

If it is clear that the +152 is caused by a bug rather than an unlucky hash collision, then that should certainly be fixed as long as it does not lose Elo. This is not clear at the moment.

**Comment by Marat-Ka** [comment] 2020-10-26 16:55
Ok, I'll wait for accuracy on this question.

**Comment by Marat-Ka** [comment] 2020-10-26 17:50
I would also like to know, just to understand the problem: what is a hash and its structure.

The first thing that comes to mind is the base of FEN's and the assessment for them, but then - how are collisions possible between them? After all, each hair FEN is unique?

**Comment by syzygy1** [comment] 2020-10-26 18:06
https://www.chessprogramming.org/Transposition_Table
https://www.chessprogramming.org/Zobrist_Hashing

FENs are also not used in tablebases ;-)

**Comment by Marat-Ka** [comment] 2020-10-26 18:45
Thus, there are defects in hash processing at the algorithm level, due to which collisions are possible?

"The surjective mapping from chess positions to a signature and an even more denser index range implies collisions, different positions share same entries, for two different reasons, hopefully rare ambiguous keys (type-1 errors), or regularly ambiguous indices (type-2 errors)."

**Comment by vondele** [comment] 2020-10-27 21:44
Also I can reproduce it, but it is not so easy. The following search executed a thousand times gives on average 1 search with scores < cp -15000
```
setoption name Threads value 8
setoption name Hash value 8192
setoption name SyzygyProbeLimit value 6
setoption name SyzygyPath value /home/vondele/chess/syzygy/3-4-5-6/WDL:/home/vondele/chess/syzygy/3-4-5-6/DTZ
position fen 7k/3K2p1/6Pp/7P/8/8/8/7B b - - 0 68
go depth 40
ucinewgame
```

**Comment by syzygy1** [comment] 2020-10-27 21:55
@Marat-Ka Yes, and the type-1 errors are in fact quiet common in SF (about 1 in 22000 nodes that should not have a hash hit have an erroneous hash hit). But it turns out this is worth it, as it allows the engine to get more benefit out of the same amount of RAM.

**Closed** 2020-11-02 18:43 UTC
