### ISSUE TITLE
Disabling analysis contempt doesn't disable contempt

### ISSUE THREAD

**Issue by gcp** [official-stockfish/Stockfish#2208] opened 2019-06-25 11:43 UTC
Some contempt is disabled here:
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L309

But this doesn't check that setting and unconditionally adds some contempt back in:
https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L359

Is this intentional?

**Comment by ddugovic** [comment] 2019-06-25 12:04
I don't see a contradiction:
https://github.com/official-stockfish/Stockfish/blob/4c986b050111e4fb96716a75ae2168c005b03df9/src/search.cpp#L305-L317

https://github.com/official-stockfish/Stockfish/blob/4c986b050111e4fb96716a75ae2168c005b03df9/src/search.cpp#L358-L362

**Comment by JavaMast** [comment] 2019-06-25 12:28
@gcp 
yes, dynamic contempt is always enabled

**Comment by Vizvezdenec** [comment] 2019-06-25 12:53
dynamic contempt is a workaround engines overestimating winnability of quite a lot of endgames.
So if you are ahead it increases eval of lines that leave more material on board.

**Comment by gcp** [comment] 2019-06-25 14:31
Does it make sense to do that operation though, if the user has already indicated he doesn't want contempt?

**Comment by Vizvezdenec** [comment] 2019-06-25 16:48
It's confirmed to be decent elo gain in selfplay regardless of base contempt value.

**Comment by snicolet** [comment] 2019-08-21 15:02
@gcp This seems to be in the zone of expected behaviour and not really a bug, so I'll close this issue.

**Closed by snicolet** 2019-08-21 15:02 UTC
