### ISSUE TITLE
Visible regression compared to pre-NNUE version when using Use NNUE=false

### ISSUE THREAD

**Issue by Sopel97** [official-stockfish/Stockfish#2981] opened 2020-08-11 13:07 UTC
According to https://tests.stockfishchess.org/tests/view/5f31c6d09081672066537576 the classical version of stockfish has lost ~7 elo since the introduction of NNUE due to search changes. This shows that it's infeasible to maintain two versions at the same time using the current developement model. 

Therefore I propose the following changes:
1. Remove the "Use NNUE" option and assume it to be always true. 
2. Provide the default net along the binaries and handle the case when no net is loaded by either:
  - Move the EvalFile uci option to be a command line option. Gracefully exit on startup when no net loaded.
  - Gracefully exit when attempting to eval/start search with no net loaded.
  - Show info string with an error and stop search/eval immediately.

2.1. Alternatively always include the default net (there is a nice simple [compressor on the forums](https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/cG-F-80M-Sw) that would allow it to fit in ~6MB) as a resource within the exe file.
3. Tag the last classical stockfish version and possibly make a semi-official release of it.

**Comment by LouisZulli** [comment] 2020-08-11 14:42
Yes, the era of human-coded evaluation is ending. Seems like a good time to revisit SMP searching instead.

**Comment by ddugovic** [comment] 2020-08-11 15:23
As long as we understand what platforms we continue to support (WASM? mobile?) or are dropping support for, I have no objection.

**Comment by vondele** [comment] 2020-08-11 15:58
@ddugovic any idea about the status of having this run on WASM? I notice there is even a SIMD spec for it https://github.com/WebAssembly/simd

**Comment by ddugovic** [comment] 2020-08-11 16:29
I'll ask the @lichess-org team for advice on this one; I believe they are knowledgeable & interested.

**Comment by Hanamuke** [comment] 2020-08-11 17:37
I've been looking into your point 2.1 but I haven't found any way of making that in a simple or portable way. Providing the net seems best.

**Comment by syzygy1** [comment] 2020-08-16 12:13
The easy way to recover the lost speed in classical mode is to #ifdef all NNUE code and create separate binaries for classical and nnue-enabled.

In the long term it seems unlikely that the same search will be optimal for classical and nnue.

**Comment by vondele** [comment] 2020-08-16 12:18
The Elo loss of 7 Elo quoted above is due to changes in search already. The speed loss was measured in the merge and was pretty small ~1.5Elo.

**Comment by syzygy1** [comment] 2020-08-16 12:24
OK, then scratch "in the long term" ;-)

**Comment by vondele** [comment] 2020-08-16 21:20
So, let me comment on this. The 'regression' of the SF classical is as expected. We should continue to improve classical eval, but can't maintain a second search. That we have lost a little Elo is as anticipated. Making Use NNUE the default is an open question, not unrelated to the question on how to deal with the net in a user friendly way. 

I do think we can tag with SF_classical and SF_NNUE the two commits around the merge. I don't see a particular value in doing a formal release of these two tagged commits.

**Comment by fohristiwhirl** [comment] 2020-08-16 22:48
Perhaps this is crazy, but you could make `Use NNUE` the default if the binary's name contains the string `nnue`. (Lc0 actually does something [vaguely similar](https://github.com/LeelaChessZero/lc0/pull/1319)).

**Comment by mstembera** [comment] 2020-08-16 23:56
What about making it the default if the default net is found?

**Comment by vondele** [comment] 2020-08-17 05:52
I'm usually hesitant about things that 'magically' work. These are typically harder to debug when the magic fails. 

Technically, the whole development chain is setup to switch from false to true. This issue suggests to remove the flag 'Use NNUE', my answer to that would be not yet.

The question that stops a change of default is really about the ability for the user to download the net. I've mentioned it across issues, but I really like the new banksia feature that will just download the net if the user adds the engine to the gui (http://www.talkchess.com/forum3/viewtopic.php?f=2&t=72350&start=960#p856303). Anybody with the skill to run the engine from the command line has the skills to download the file. Those that use a GUI should get a GUI that helps them.

**Comment by Sopel97** [comment] 2020-08-17 09:21
> Perhaps this is crazy, but you could make Use NNUE the default if the binary's name contains the string nnue. (Lc0 actually does something vaguely similar).

Hidden logic like this is only good for hidden functionality.

> The question that stops a change of default is really about the ability for the user to download the net

I would think that if NNUE was the default and a net was required then people who provide stockfish builds would start including nets or point to the resource. For the people who compile from source getting a net shouldn't be a problem at all.

> Those that use a GUI should get a GUI that helps them.

The question here is what would happen first: them discovering such a GUI or them discovering the network repo or them looking for help with "Stockfish 160820 caused an exception.  This is a problem in the engine.".

The message when trying to run search without a net in the command line is already sufficient in my opinion for even the least informed people to know what to do. But right now they need to first know to set "Use NNUE" to true. There's sadly no good way of making a GUI print that to the user; which brings us back to the best solution being just packaging the default net with the binaries.

**Comment by vondele** [comment] 2020-08-24 10:27
so, I have tagged the NNUE merge with SF_NNUE and the commit before that with SF_classical. 
NNUE is now the default, discussions on how to deal with the default net are best continued in https://github.com/official-stockfish/Stockfish/issues/3030
I'll close this issue.

**Closed by vondele** 2020-08-24 10:27 UTC
