### ISSUE TITLE
[AARCH64] thread-local storage (TLS) , improves my Stockfish (around 2%)

### ISSUE THREAD

**Issue by 888luck8** [official-stockfish/Stockfish#5155] opened 2024-04-05 17:47 UTC
### Describe the issue

 -ftls-model=local-exec  increases the speed by a lot

**-fwritable-strings -ftls-model=local-exec**

using this two flags. Improved stockfish speed by a lot for me 

**uname -m && ./stockfish bench 2>&1 | tail -n 4 && ./stockfish.CLANG bench 2>&1 | tail -n 4
aarch64
=========================== (-ftls-model=local-exec)
Total time (ms) : 4067
Nodes searched  : 1823302
Nodes/second    : 449918**

=========================== (default $make -j profile-build COMP=clang )
Total time (ms) : 4061
Nodes searched  : 1823302
Nodes/second    : 448278

why is that happening 
tried atleast 20 times to run this bench command and same result 
 -ftls-model=local-exec

is better, but why 

### Expected behavior

---

### Steps to reproduce

----

### Operating system

All

### Stockfish version

dev version as of today

**Comment by Disservin** [comment] 2024-04-05 18:43
Please use a speedup script from here https://github.com/official-stockfish/Stockfish/wiki/Advanced-topics#measure-the-speed-of-stockfish.

**Comment by 888luck8** [comment] 2024-04-05 23:05
> Please use a speedup script from here https://github.com/official-stockfish/Stockfish/wiki/Advanced-topics#measure-the-speed-of-stockfish.

Thanks for that but not related to what I am trying to suggest

**Comment by Sopel97** [comment] 2024-04-05 23:34
can't reproduce

**Comment by bftjoe** [comment] 2024-04-06 00:16
This doesn't make much sense to me, since stockfish doesn't use any TLS storage specifiers, unless I'm missing something.

**Comment by Torom** [comment] 2024-04-06 10:08
Results are close to error bar:
```
Result of  30 runs
==================
base (../stockfish   ) =     241196  +/- 926
test (...h_local-exec) =     242134  +/- 1239
diff                   =       +938  +/- 973

speedup        = +0.0039
P(speedup > 0) =  0.9704

CPU: 4 x aarch64
Hyperthreading: off
```
```
Result of  50 runs
==================
base (../stockfish   ) =     233157  +/- 1769
test (...h_local-exec) =     233818  +/- 1830
diff                   =       +661  +/- 584

speedup        = +0.0028
P(speedup > 0) =  0.9865

CPU: 4 x aarch64
Hyperthreading: off
```

**Comment by Disservin** [comment] 2024-04-06 10:35
> This doesn't make much sense to me, since stockfish doesn't use any TLS storage specifiers, unless I'm missing something.

https://github.com/official-stockfish/Stockfish/blob/master/src/nnue/nnue_architecture.h#L113

**Comment by Disservin** [comment] 2024-04-06 10:41
> > Please use a speedup script from here https://github.com/official-stockfish/Stockfish/wiki/Advanced-topics#measure-the-speed-of-stockfish.
> 
> Thanks for that but not related to what I am trying to suggest

You are suggesting that this flag is a speedup, and you show 1 benchmark which is supposedly confirming that, you should use one of our speedup scripts to get a more relevant comparison. Your benchmarks seem flawed anyway, the first one took 4067ms so 6ms longer than the second one, but the second completed faster but somehow has a lower nps..

**Comment by vondele** [comment] 2024-04-06 10:47
for me using gcc on aarch64 adding `-ftls-model=local-exec` results in an identical binary.

**Comment by Disservin** [comment] 2024-04-06 10:53
i'll close it for now, since it is anyway not an issue but rather something which should be a pr if it were an actual speedup

**Closed by Disservin** 2024-04-06 10:53 UTC

**Comment by Torom** [comment] 2024-04-06 10:55
> for me using gcc on aarch64 adding `-ftls-model=local-exec` results in an identical binary.

Same here :laughing: 
As I said, everything close to error bars.
