### ISSUE TITLE
Stockfish does not stop calculating for particular FEN position

### ISSUE THREAD

**Issue by kieferro** [official-stockfish/Stockfish#4023] opened 2022-05-14 16:17 UTC
I work with Stockfish 15 (AVX2) on Windows. When I start Stockfish and enter the following commands:

```
position fen 3r4/p3PNkp/1p4p1/5p2/8/1N6/PPP2PPP/R4RK1 b - - 0 28
setoption name MultiPV value 17
go depth 10
```
Stockfish calculates up to depth 9 and then outputs nothing. I waited over half an hour, which is quite a lot considering that depth 10 calculations usually take less than a second for me. \
This problem only occurs with exactly this FEN. I have written a Python script that uses Stockfish and evaluates different positions and I have never had problems except with this exact position. The problem also occurs exclusively with Stockfish 15. For Stockfish 14 (AVX2) the calculation up to depth 10 is over after less than a second.

Another interesting property of this problem is that it does not occur when first calculating only to depth 9.
So if I first enter the following:

```
position fen 3r4/p3PNkp/1p4p1/5p2/8/1N6/PPP2PPP/R4RK1 b - - 0 28
setoption name MultiPV value 17
go depth 9
```
and then wait until the process is finished and then enter this

```
position fen 3r4/p3PNkp/1p4p1/5p2/8/1N6/PPP2PPP/R4RK1 b - - 0 28
setoption name MultiPV value 17
go depth 10
```
then the program runs up to depth 10 without problems.

Does anyone have any idea what could be the problem here?

Thanks

**Comment by vondele** [comment] 2022-05-14 16:34
yes, a duplicate of https://github.com/official-stockfish/Stockfish/issues/3911
a simple solution is to use 
`go movetime 1000` 
to have exactly 1s searches.

**Closed by vondele** 2022-05-14 16:34 UTC
