### ISSUE TITLE
Warning during compiling in fishtest

### ISSUE THREAD

**Issue by kotenok2000** [official-stockfish/Stockfish#3412] opened 2021-03-25 18:54 UTC
position.cpp: In member function 'void Stockfish::Position::do_move(Stockfish::Move, Stockfish::StateInfo&, bool)':
position.cpp:755:7: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
  755 |       else
      |       ^~~~
position.cpp:757:11: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'else'
  757 |           st->NNMaterial -= PieceValue[NN][captured];
      |           ^~

**Comment by BM123499** [comment] 2021-03-25 18:59
`st->NNMaterial`? it seems that it was a test I was doing some weeks ago. That structure doesn't make part of current SF. it was an variant tested. It's not a bug. It was an unfortunate that I didn't notice, though.

**Comment by BM123499** [comment] 2021-03-25 19:04
https://github.com/official-stockfish/Stockfish/blob/master/src/position.cpp#L739-L755

**Comment by vondele** [comment] 2021-03-27 09:09
so not a real issue with SF as we provide, but something not quite OK with a tested patch. That happens, but is without consequence, so I'll close this issue

**Closed by vondele** 2021-03-27 09:09 UTC
