### ISSUE TITLE
Again about the benchmark

### ISSUE THREAD

**Issue by amchess** [official-stockfish/Stockfish#5157] opened 2024-04-06 22:41 UTC
### Describe the issue

No: imho, the problem isn't the network size.
I think the refactoring with the worker isn't no funcitonal changes.
For example, in position.cpp there are the following lines:

        // Update material hash key and prefetch access to materialTable
        k ^= Zobrist::psq[captured][capsq];
        st->materialKey ^= Zobrist::psq[captured][pieceCount[captured]];
but the materialTable has been deleted and there is no prefetch.

### Expected behavior

not this behaviour

### Steps to reproduce

./Stockfish16 bench
./Stockfish16.1 bench

### Operating system

All

### Stockfish version

S

**Comment by PGG106** [comment] 2024-04-06 22:44
The comment is outdated, a table not being used anymore and a useless prefetch not being present doesn't make the engine slower, the change was non functional.
The newer versions are slower because the net arch changed, the layers are bigger and the inference has to do more work, hence it's slower (multiplications aren't free), this issue is just a duplicate of the previous one.

**Comment by Disservin** [comment] 2024-04-06 22:59
```
SF 16:      
 L1:  1536, nn-5af11540bbfe.nnue
 nps: 1823913

SF 16.1:
 L1:  2560, nn-b1a57edbea57.nnue
 nps: 1210743 

(with smaller network)
SF 16.1:
 L1: 1536, nn-5af11540bbfe.nnue
 nps: 1472458

master: 1096393
```

SF 16, still used a mixed of classical and main net, where the classical part is probably giving the other additional speedup. 

__SF 16 bench was a mix of positions with NNUE and classical, I think 50/50 split.__
__SF 16.1 is 100% NNUE in bench.__

SF 16.1 uses the main net and the small net, with classical completely removed...

**Closed by Disservin** 2024-04-06 22:59 UTC

**Comment by mstembera** [comment] 2024-04-06 23:25
We should probably simplify materialKey away though.

**Comment by amchess** [comment] 2024-04-07 11:37
Before removing classical eval:Simplify PvNode reduction Jul 11,2023
https://github.com/official-stockfish/Stockfish/commit/6a8767a0d5d9502e6d4de1bef97468b5d6fab80a
Nodes/second    : 1502286

With removing classical eval:  Jul 11, 2023
https://github.com/official-stockfish/Stockfish/commits/master/?before=0716b845fdef8a20102b07eaec074b8da8162523+315
Nodes/second    : 885742

Same net

I don't understand why.

**Comment by dav1312** [comment] 2024-04-07 11:39
As Disservin already said, it is because of 50% of the bench positions used only the classical evaluation, which was much faster

**Comment by amchess** [comment] 2024-04-07 11:57
Done 
bench 16 1 13 default depth NNUE 
before
Nodes/second    :  924580
after
Nodes/second    : 769656
I'm very sorry, but yet I don't understand.

**Comment by peregrineshahin** [comment] 2024-04-07 12:00
I will answer you, though I'm already regretting it (interaction with you is sickening).
Classical Eval role, was mianly about delevering not so good eval in compansation of speed, so even with using NNUE as default you still use Classical Eval in winning positions.

**Comment by dav1312** [comment] 2024-04-07 12:07
https://github.com/official-stockfish/Stockfish/blob/6a8767a0d5d9502e6d4de1bef97468b5d6fab80a/src/evaluate.cpp#L1056-L1059

**Comment by Disservin** [comment] 2024-04-07 12:11
```
command: ./stockfish bench 16 1 13 default depth NNUE;
commit : 6a8767a0d5d9502e6d4de1bef97468b5d6fab80a (Simplify PvNode reduction)
changes: with classical part removed in evaluate
nps    : 1111266

command: ./stockfish bench 16 1 13 default depth NNUE;
commit : 6a8767a0d5d9502e6d4de1bef97468b5d6fab80a (Simplify PvNode reduction)
nps    : 1180150

command: ./stockfish bench 16 1 13 default depth NNUE;
commit : af110e02ec96cdb46cf84c68252a1da15a902395 (Remove classical evaluation)
nps    : 1112121
```

**Comment by amchess** [comment] 2024-04-07 12:16
OK: so, for two elo points, do you degrade performance so fearfully?

**Comment by Disservin** [comment] 2024-04-07 12:18
What

**Comment by amchess** [comment] 2024-04-07 12:20
![image](https://github.com/official-stockfish/Stockfish/assets/10925308/8b3754be-5002-48b9-8a6b-7813ef260d8e)

**Comment by XInTheDark** [comment] 2024-04-07 12:22
how is this relevant to your problem about the benchmark nps?

**Comment by PGG106** [comment] 2024-04-07 12:22
hce wasn't removed to gain 2 Elo, it was removed even if removing it lost 2 Elo, because with long enough tc the impact was 0.
A 0 impact on performance is not performance degradation, the fact the engine reports a slower bench speed because hce isn't there to inflate the metric doesn't mean anything.

**Comment by PGG106** [comment] 2024-04-07 12:23
In general arguing about hce removal now is useless, it's a done deal, new and better solutions have propped up to fill the void the hce removal left, devs are working on sf 17 and stuff that was definitive in sf 16 is definitely not relevant now.

**Comment by PGG106** [comment] 2024-04-07 12:28
you don't understand anything you talk about, that's all there is to it, as usual.
Ofc switching over to hce inflates the speed, you are avoiding the nnue slowdown by not using the nnue at all, switching back to fully hce eval would make the engine faster too, but so what?
speed is just a metric, you can sacrifice speed to gain elo, it's what the hce to nnue switch did, moreover removing hce isn't that much of a speed drop, bench shouldn't have been mixed in the first place and the metrics it reports are inflated by the positions that are > 2048 cp in value.
Moreover part 2 current sf dev has a solution to speed up the engine in won positions, it's a smaller net that takes the place of what was hce before (without the need to keep all that hce code around).
For once you should try to understand what you are talking about before second guessing tens of devs that all know far more than you.

**Comment by PGG106** [comment] 2024-04-07 12:29
You are consistently as confident as you are wrong, and that's a really hard feat, stop second guessing devs when you don't understand how a nnue arch works or what a pv node is, it's pathetic.

**Comment by amchess** [comment] 2024-04-07 12:45
I develop a fork of stockfish with the goal of making it understandable/useful to the OTB player, not necessarily, therefore, stronger, and I wondered why this frightening degradation of performance.  That's all.

**Comment by PGG106** [comment] 2024-04-07 12:48
how is a 2 Elo impact at sub blitz time controls a "frightening degradation of performance"^, why are we acting like the basically 0 Elo impact (at the very very very long time controls you otb players love)  wasn't made even less impactful by the fact smallnet exists? the truth of the matter is that sf is now stronger than when hce was still present and it's stronger than it would be if hce was still present.
You are wondering wrong things based off of wrong assumptions and either outdated or wrong "knowledge" (or lack thereof).

**Comment by PGG106** [comment] 2024-04-07 13:04
It doesn't matter what anyone thinks, this is about numbers, nps, elo and time controls. This is equivalent to math, it doesn't matter if i think that 3 + 2 is 7 or if my dream is for 12 * 10 to be 97, this is factual information that can only be correctly or incorrectly interpreted, there's no room for opinions here.
That being said it's pretty evident that you are a troll so there's no use engaging with you and i won't do so any further.

**Comment by WampServer** [comment] 2024-04-07 13:31
@PGG106 If we talk about NPS,  [Lifish](https://github.com/EarlyEdition/Lifish-HalfKP) has the highest NPS among all NNUE chess engines, and so no further explanation is needed.

**Comment by amchess** [comment] 2024-04-07 13:46
Commits on Jan 14, 2024
Remove the dependency on a Worker from evaluate

before refactor
Nodes/second    : 826439

after refactor
Nodes/second    : 822816

Same net and bench
The refactoring isn't no functional changes.
Just about facts, numbers...

**Comment by PGG106** [comment] 2024-04-07 13:54
that's a supposedly 0.4% speed drop, it's too small of a drop to be measured with a single bench run or even 3 or 5, it's easily explained away by noise and error bars in the bench measurement.
If you want an accurate way to measure speed use the script that is customarily used to measure for speed gains/losses. you'll notice that with enough runs the change is just neutral.
The refactoring is definitely non functional

**Comment by Disservin** [comment] 2024-04-07 14:00
> Commits on Jan 14, 2024 Remove the dependency on a Worker from evaluate
> 
> before refactor Nodes/second : 826439
> 
> after refactor Nodes/second : 822816
> 
> Same net and bench The refactoring isn't no functional changes. Just about facts, numbers...

A single bench run isn't very reliable. You could probably redo a single bench at some point and get reversed results. You should be using one of the many speedup scripts to better determine the effect of a patch on the overall performance.

**Comment by PGG106** [comment] 2024-04-07 14:00
Here you can find all the info on how to properly measure the speed of stockfish: https://github.com/official-stockfish/Stockfish/wiki/Advanced-topics#measure-the-speed-of-stockfish, coincidentally it also says `A speedup of 0.3% could be meaningless (i.e. within the measurement noise)` which is exactly what you are measuring.

**Comment by WampServer** [comment] 2024-04-07 16:02
> that's a supposedly 0.4% speed drop, it's too small ....

**SF 16 defeats SF 16.1 in 202 moves! This proves how small changes can make a huge difference in bullet games.**

```
[Event "Bullet 2.0min+1.0sec"]
[Date "2024.04.07"]
[White "Stockfish 16"]
[Black "Stockfish 16.1"]
[Result "1-0"]
[PlyCount "403"]
1. d4 d5 2. c4 c6 3. Nf3 dxc4 4. e3 b5 5. a4 e6 6. axb5 cxb5 7. b3 Nf6 8. bxc4 bxc4 9. Bxc4 Bb7 10. O-O Be7 11. Qb3 Bxf3 12. gxf3 O-O 13. Bd2 Nbd7 14. Ba5 Nb6 15. Nd2  Bd6 16. Rfc1 Rc8 17. f4 g6 18. Qb5 Kg7 19. h3 Qe7 20. Bxb6 axb6 21. Qxb6 Bb4 22. Nf3 Ba3 23. Rc2 Rb8 24. Qa5 Bb4 25. Qa2 Ra8 26. Qb1 Bd6 27. Bf1 Rfb8 28. Qc1 Rxa1 29. Qxa1  Rb7 30. Ne5 Ra7 31. Qe1 Qd8 32. Bg2 Qb6 33. Qc3 Rc7 34. Rb2 Qa6 35. Qb3 Nd7 36. Nd3 Qa3 37. Qb5 Nf6 38. Bf3 Rc8 39. Qb3 Rc3 40. Qxa3 Bxa3 41. Rd2 Nd7 42. Be2 Rc7 43. Kg2 Be7 44. Rb2 Bd8 45. Bd1 Rc3 46. Be2 Rc7  47. Ne1 Nf6 48. Nf3  Ne4 49. Ba6 Nd6 50. Ne5 Bh4 51. Bd3 Nc8 52. Rb5 Ra7 53. Rc5 Nb6 54. Rc2 Nd5 55. Kf3 Rc7  56. Rb2 Bf6 57. Rb1 Ne7 58. Kg3 Nc6 59. Be4  Ne7 60. Rb8 Nc8 61. Ra8 Be7 62. Bf3 Bd6 63. Kg2  Be7 64. Ra6 Bd6 65. Ra8 Nb6 66. Ra5 Nc8 67. Rb5 Ne7 68. Rb6 Nc8 69. Rb8 Ne7 70. Rb6 Nc8 71. Rb8 Ne7 72. Ra8 Nc8 73. Be4 Bf8 74. Kf3 Bd6 75. Ke2 Be7 76. Ra6  Ra7 77. Rc6 Nd6 78. Bd3 Bf8 79. Kf3 Ne8 80. Rc8  Nd6 81. Rb8 Rc7 82. h4 h5 83. Rb1 Nc8 84. Rg1 Ne7 85. Ke2 Rc8 86. Ra1 Rc7 87. Be4 Nc8 88. Rg1 Ne7 89. Bd3 Kf6  90. Ra1 Nc6 91. Nf3 Kg7 92. Ra6 Nb4 93. Ra1 Nd5 94. Ng5 Be7 95. Kf3 Bf6 96. Be4 Ne7 97. Ra5 Rd7 98. Kg2 Kg8 99. Kg3 Kg7 100. Kh3 Ng8 101. Ra6 Ne7 102. Bg2 Nf5 103. Bh1  Rc7 104. Bc6 Be7 105. d5 exd5 106. Bxd5 Bf6 107. Be4 Nh6 108. Kg2 Re7 109. Bb1 Rb7 110. Ba2  Bc3 111. Bd5 Rd7 112. Be4  Bf6 113. Ra5 Re7 114. Kf3 Rd7 115. Kg2 Re7  116. Ra4 Rd7 117. Kg3 Bc3  118. Ra3 Be1 119. Nf3 Bb4  120. Ra6 Re7 121. Bd3 Rc7 122. Ne5 Bc3 123. Kg2 Bxe5 124. fxe5 Rc3 125. Bb1 Rb3 126. Ba2 Rb4 127. Ra7 Kf8 128. Ra8+ Kg7 129. Ra7  Kf8 130. f4 Rb2+ 131. Kg3 Re2 132. Ra3 Nf5+  133. Kf3 Rh2 134. Ra8+ Kg7 135. Ra7 Rh3+ 136. Kf2 Rh2+ 137. Kg1  Rd2 138. e6 Nxh4 139. Bd5 Rxd5 140. Rd7 Nf3+ 141. Kf2 Ng5 142. Rxd5 Nxe6 143. Re5 Nf8 144. Re7 Ne6 145. Kf3 g5 146. Rd7 Kg6 147. Rd6  h4 148. Kg4 f5+  149. Kh3 Kf7 150. fxg5 Nxg5+  151. Kxh4 Ne6 152. Kg3 Kf6 153. Kf3 Ke5 154. Ra6 Ng5+  155. Ke2 Ne6 156. Ra5+ Ke4 157. Ra4+ Ke5 158. Ra5+ Ke4 159. Ra7 Ng5 160. Ra4+  Ke5 161. Ra5+ Ke4 162. Ra1 Ne6 163. Ra5 Ng5 164. Ra6 Ke5 165. Kd3 Nf3  166. Ra5+ Ke6 167. Ra6+ Kd5 168. Rb6 Ne5+ 169. Ke2 Ke4 170. Rb4+ Kd5 171. Ra4  Ke6 172. Ra6+ Kd5 173. Kf2 Nd3+ 174. Kf3  Ke5 175. Rb6 Kd5 176. Rb3 Kc4 177. Ra3 Ne1+ 178. Ke2 Kb4 179. Ra7 Nc2 180. Rf7  Kb5 181. Rxf5+ Kc6 182. Kf3 Na3 183. Ke4 Nc2 184. Kf3 Nb4 185. Ra5 Nc2 186. Ke4 Kb6 187. Ra2 Nb4 188. Rb2 Kc5  189. Rxb4 Kxb4 190. Kd5  Kb5 191. e4 Kb6 192. Ke6 Kc5 193. e5 Kd4 194. Kd6  Ke4 195. e6 Kd4 196. e7 Kc4 197. e8=Q Kd3  198. Kd5 Kd2 199. Kc4 Kc2 200. Qe2+ Kb1 201. Kc3 Ka1 202. Qb2# 1-0
```
