### ISSUE TITLE
[Ryzen] Crashes at framework

### ISSUE THREAD

**Issue by Vizvezdenec** [official-stockfish/Stockfish#1433] opened 2018-02-26 03:46 UTC
Idk if I should create this issue on /fishtest, but w/e.
In recent tests there are a lot of crashes, seems like some of the latest commits causes them.
http://tests.stockfishchess.org/tests/view/5a9379630ebc590297cc89a4
http://tests.stockfishchess.org/tests/view/5a9379120ebc590297cc89a2
http://tests.stockfishchess.org/tests/view/5a93198b0ebc590297cc8942

**Comment by noobpwnftw** [comment] 2018-02-26 04:19
I don't see any crash dumps but here are aggregated results from /var/log/messages from my workers.

[errors.log](https://github.com/official-stockfish/Stockfish/files/1757225/errors.log)

**Comment by AndyGrant** [comment] 2018-02-26 04:27
Many error reports for 'base' in there, but none for 'test'. That seems off.

**Comment by crossbr** [comment] 2018-02-26 04:41
My 3 core also crashed with a segfault, and normally it never crashes.

**Comment by 890403** [comment] 2018-02-26 05:07
The cause is this commit that messes with movepicker logic.
https://github.com/official-stockfish/Stockfish/commit/8dd6875240e05dbcc1fb6467ffb11ad360aa474c

**Comment by AndyGrant** [comment] 2018-02-26 05:46
That commit seems to be where the issue started, but can you identify why?

**Comment by 890403** [comment] 2018-02-26 06:00
@AndyGrant Likely at recursive call to next_move inside next_move with some invalid state combination(e.g. qsearch triggers this).
// Rebranch at the top of the switch via a recursive call

**Comment by vondele** [comment] 2018-02-26 06:45
@noobpwnftw any chance you could resolve these addresses to a code line ? 

FYI the test of the mergeCapture patch shows a rather normal crash pattern:
http://tests.stockfishchess.org/tests/view/5a91a8bb0ebc590297cc875b
which of course doesn't prove it correct.

**Comment by AndyGrant** [comment] 2018-02-26 06:58
http://tests.stockfishchess.org/tests/view/5a923dc80ebc590297cc8806
This test has a fair number of crashes, and happens before the Vondele patch we are looking at.

**Comment by 890403** [comment] 2018-02-26 08:12
To locate the cause of crash the tests which crash needs to be recompiled with older code(preferably before movepick.cpp overhaul) so that we could see the first commit that triggers these crashes.

**Comment by Vizvezdenec** [comment] 2018-02-26 10:17
Issue is still there and it's really bad in some tests 
http://tests.stockfishchess.org/tests/view/5a9379630ebc590297cc89a4

**Comment by Vizvezdenec** [comment] 2018-02-26 11:00
@Stefano80 I have 0 idea that's why I was doubting where to open this issue.

**Comment by noobpwnftw** [comment] 2018-02-26 11:07
I suggest we pick one patch that crashes the most and rebase it against each of the recent master commit.

**Comment by locutus2** [comment] 2018-02-26 13:31
I started with a serious of self-play tests of the various master commits to isolate the possible source of the crashes. Auto purge is set off so crashes could not be removed and masked the results.
The first two are:
"Join all capture init stages in MovePicker"
http://tests.stockfishchess.org/tests/view/5a9404f70ebc590297cc8a26

"More robust interaction of singular search and iid" 
http://tests.stockfishchess.org/tests/view/5a94056e0ebc590297cc8a28

**Comment by Stefano80** [comment] 2018-02-26 13:34
Danke Stefan!

**Comment by noobpwnftw** [comment] 2018-02-26 13:37
http://tests.stockfishchess.org/tests/view/5a94056e0ebc590297cc8a28
This one is actually tested with crosscheck tests before, no crash occurred.

**Comment by lp--** [comment] 2018-02-26 13:40
I see zero crashes in my tests, and they touch only time management, so it is almost master. So it would be weird if they are coming from master in other tests

**Comment by Vizvezdenec** [comment] 2018-02-26 15:30
Seems like there are 0 crashes in sg tests also...

**Comment by VoyagerOne** [comment] 2018-02-26 17:57
It's a framework issue...
Too many requests...
If you want to see crashes just change the priority to 0 for this tuning patch:
http://tests.stockfishchess.org/tests/view/5a9200d10ebc590297cc87a3

**Comment by vondele** [comment] 2018-02-26 19:34
I tested current master (71cc01c2ef45bab91bdcd72c699f66e19dd518b3) with 40'000 games locally, and there has not been a single crash. So, this suggests it is the (fishtest?) environment that is part of the problem. I'm somewhat surprised that this can lead to segfaulting SF binaries (see kernel messages from @noobpwnftw)...

**Comment by lp--** [comment] 2018-02-26 19:50
@vondele My guess  is that you need to take patch which shows crashes and test it. As there are so many of such patches  reason for crashes is not in specific patch but somewhere else in the code. Patches just allow to reach that place with specific parameters.

**Comment by vondele** [comment] 2018-02-26 19:59
@lp-- the kernel messages show that it affects both base and patched binaries, and it is happening for a wide range of patches, so just testing master should be sufficient. 

Having said that, to get more info we need to get a specific trace, ideally by having a binary compiled with -g (by providing the file fishtest/worker/custom_make.txt containing a line like 
```
CXXFLAGS="-g" make build COMP=gcc ARCH=x86-64-modern
```
and using addr2line on that binary with the address obtained in the kernel logs (i.e. the number after ip 0000000000423d1d). Even more useful would be to enable core dumps (ulimit -c 10000000) before starting the fishtest worker.

**Comment by Stefano80** [comment] 2018-02-26 19:59
If it is a transient fishtest problem, then the crashing tests should be located temporally.

Now that we have start and test time recorded for all tests it should be checkable.

I will give it a try tomorrow.

**Comment by AndyGrant** [comment] 2018-02-26 21:52
I cannot recreate crashes on my end, on any of my machines. In my opinion the issue must be with fishtest.
I would recommend we stop submitting anything new, and finish clearing out all the stuff that is currently running, and the two dozen soon-to-be reds sitting at -1.

**Comment by Rocky640** [comment] 2018-02-26 22:15
a) most tuning tests shows a few crashes, but nothing special.

b) However, the http://tests.stockfishchess.org/tests/view/5a9200d10ebc590297cc87a3
    (which was set at priority -1 some time ago) had many. 
    This test is trying to tune 142 variables.
    Some SPSA results are sent after each iteration, and a very large list of variables (142) and value must be fed to the engine. If the string which is passed to the engine is corrupted, a crash is quite likely.

c) other tests still have some parameters which are passed to the engine, Usually, it is just a few parameters, (the hash, the time control to use for the engine,...)
    Are they passed only once when the batch of 1000 tests starts ? Or more often ?

d) the error.log posted at the start of this link shows that both master and test version have crashes,
    but we do not know for which test that log applied (if might be a spsa test or not)

**Comment by noobpwnftw** [comment] 2018-02-26 22:26
Apparently the book is downloaded only once and never checked for sanity, I found 2 of 100 workers had downloaded an incomplete book! (0-sized file)
Now I have synchronized all of them with correct book file and cleared logs. Let's wait and see if any more crashes emerges after this.
This may fix some of the crashes from my workers but I don't see how this could cause other workers to crash too.
However this does not fix tuning crashes I presume.

**Comment by AndyGrant** [comment] 2018-02-26 22:32
There is - or was - a thing where if a worker's task was ended (which I imagine happens in your bookless case) another worker could pick up the stats, and continue it. I suppose it is possible that your crashed workers had their results picked up by others, as you are the only person I have seen report seeing actual crashes.

If only 2 of your workers had this problem, then I am likely wrong. If you checked 8 and found 2 with errors.... I might be right.

**Comment by noobpwnftw** [comment] 2018-02-26 22:51
Caught one:
Feb 27 06:23:01 174 kernel: stockfish[18611]: segfault at 0 ip 0000000000424e60 sp 00007f104d41de70 error 4 in stockfish[400000+47000]
Files are built at Feb 27 06:16 and collected at Feb 27 06:23
[crashed_files.zip](https://github.com/official-stockfish/Stockfish/files/1760547/crashed_files.zip)

**Comment by Rocky640** [comment] 2018-02-26 22:57
Your run_id.txt indicates 5a9480c70ebc590297cc8adc

So it seems that the Error 4 relates to the following test
http://tests.stockfishchess.org/tests/view/5a9480c70ebc590297cc8adc
which does not have any crashes !!!

Maybe the error 4 happened because the tests were finished.
Looks like a false alarm...

**Comment by noobpwnftw** [comment] 2018-02-26 23:09
It did had crashes, now I'm adding a "sys.exit(1)" when a crash occurred, then I preserve the environment where the crash happened.

**Comment by noobpwnftw** [comment] 2018-02-26 23:25
There:
Feb 27 07:20:01 193 kernel: base[2596]: segfault at ffff7076 ip 0000000000423d1d sp 00007fdf719d8640 error 6 in base[400000+47000]
[crash.zip](https://github.com/official-stockfish/Stockfish/files/1760634/crash.zip)

**Comment by AndyGrant** [comment] 2018-02-27 02:44
So I think the conclussion is the bug in your CPUS, + 

> There is - or was - a thing where if a worker's task was ended (which I imagine happens in your bookless case) another worker could pick up the stats, and continue it. I suppose it is possible that your crashed workers had their results picked up by others, as you are the only person I have seen report seeing actual crashes.

**Comment by Vizvezdenec** [comment] 2018-02-27 03:05
there were crashes for other users too as you can see there:
http://tests.stockfishchess.org/tests/view/5a9379630ebc590297cc89a4
Allnautilus, bcross, dew, solarlight and others - their machines usually don't crash.

**Comment by Rocky640** [comment] 2018-02-27 03:09
@Vizvezdenec  the hypothesis is that when a machine crash in a middle of a batch of 1000 games, another one will pick up the remaining games and inherit the crash statistics.

**Comment by noobpwnftw** [comment] 2018-02-27 03:12
As I said, with recent changes in SF, it happened to carry out the piece of code that will trigger the processor bug.

Now I have replaced with 100 Intel chip workers(ChessDB_CN_WorkerPool-8cores-xxx), and ran through the same test with zero crash now.

http://tests.stockfishchess.org/tests/view/5a94be3e0ebc590297cc8b16
vs
http://tests.stockfishchess.org/tests/view/5a9379120ebc590297cc89a2

**Comment by 890403** [comment] 2018-02-27 03:18
Usually when hardware is at fault, you work around the hardware with software fixes: not with hardware fixes. I would suggest amending the problematic next_move code back to earlier  and running the tests again to ensure it doesn't happen.

**Comment by noobpwnftw** [comment] 2018-02-27 05:02
We did nothing wrong here and even if this has to be avoided on the software side, it must be done in the compiler so it won't produce bug triggering code, there seems to be no reliable way otherwise.
Actually the processor bug can be triggered from any running process and cause random segfaults somewhere, it just so happens here because my worker machines run nothing else than fishtest.

**Comment by vondele** [comment] 2018-02-27 05:36
@noobpwnftw ... great debugging. 

I think the debugging was made more complicated due the to fishtest feature of 'reassigning' batches to different workers. This has come up in the past repeatedly, and I wonder if this can be avoided (@Stefano80).

**Comment by Stefano80** [comment] 2018-02-27 05:51
Yes, this should be changed. Could you open an issue on fishtest such that we do not forget this?

**Comment by snicolet** [comment] 2018-02-27 07:32
@noobpwnftw Yes, impressive debugging, thanks.

> Where the crash occurred is a multi-byte "nop" alignment instruction after a jump table for the switch in MovePicker::next_move() function that should never access any memory, I have collected 20 crashes on different machines with the exact same location of segfault. Similar symptoms has been reported with https://github.com/suaefar/ryzen-test.

Do we understand why the compiled binary on ARM has this bug in the switch statement in this commit? https://github.com/official-stockfish/Stockfish/commit/8dd6875240e05dbcc1fb6467ffb11ad360aa474c

As I understand it, you have removed the ARM machines from fishtest and put heaps of Intel machines instead, so this gives us a couple hours of relief for taking actions. We can either revert the patch, or rewrite it in a way that doesn't produce the bogus code pattern (my preference), but for that we must know exactly how and test again on ARM...

Thanks for the awesome work, anyway :-)

**Comment by noobpwnftw** [comment] 2018-02-27 08:34
@snicolet The previous 100 workers are not ARM machines, they are AMD Ryzens(Threadripper). And this SF case may be the first confirmation of such bug exists beyond previously confirmed affected products.

**Comment by Vizvezdenec** [comment] 2018-02-27 12:42
I think that we can close this issue and you can create a new one where you can discuss how to reformat code so it wouldn't crash sf on ryzen CPUs, is this ok? @snicolet

**Comment by noobpwnftw** [comment] 2018-03-01 00:45
[crash_test.zip](https://github.com/official-stockfish/Stockfish/files/1769315/crash_test.zip)
This is a standalone test package to reproduce the crash on Ryzen.

Binaries are prebuilt by me(CentOS 7+kernel-ml 4.15.6+devtoolset-7/llvm-toolset-7), corresponding source codes are included, tested with both GCC & clang, they will all produce a crash somewhere within the MovePicker::next_move() function on Ryzen, although chances for a single machine to encounter it seems low(for this test package it took ~30 mins on 100 machines 15 threads each to see one segfault).

**Comment by tomtor** [comment] 2018-03-01 13:56
@noobpwnftb I cannot reproduce the crash with your latest crash_test.zip on my Ryzen 1700x. The run.sh finished without issues.

It is the 7-core worker on fishtest and it never crashed on fishtest. I did have the RMA problem on an old 1700 which I replaced with this recent 1700x.

Are you sure it is cannot be kernel related? I am using 4.4.0-109-generic #132-Ubuntu SMP. Or perhaps it is specific to threadrippers?

**Comment by vondele** [comment] 2018-03-01 20:34
If we want to try code level workarounds (really?).... Take 1: https://github.com/vondele/Stockfish/commit/1db66a753e828282de6c48feec1152621a08d43a

**Comment by snicolet** [comment] 2018-03-01 21:22
@Vizvezdenec Let's keep this issue open for the moment.

At this moment I want to really understand, I want to be open and doubt about everything on the subject of these crashes.

I even want to be able to doubt that the crash is a direct consequence of the Movepicker patch, because as @AndyGrant noted in this comment:
official-stockfish#1433 (comment)
there were already some crashes on the Ryzen machines (most probably Ryzen, in fact) before the MovePicker patch.

Still, the crash report by @noobpwnft show a crashin machine code for MovePicker.cpp...

**Comment by snicolet** [comment] 2018-03-01 21:56
Take 2: https://github.com/snicolet/Stockfish/commit/9c077ac5271b455627f53776deb66b672c4eeddf

Move the XXX_INIT stages at the end of the switch, and put the switch in an infinite loop to go to the next stages. This version is a simplification which gains 7 lines of code and is a tad faster than master, but that is not the question.

**Comment by noobpwnftw** [comment] 2018-03-01 21:59
Although in my case most of the crashes are related to the MovePicker patch, I object to reverting it because it will only reduce the chances of having crashes for now, but not "solving" it, as @AndyGrant suggested with earlier tests. And it may come back again in the future.

It just so happened because we introduced crash triggering code sequences in a highly frequent execution path, thus on faulty Ryzens(including mine) we are more likely to encounter crashes.

@tomtor suggested that not every Ryzen chips are faulty, so we might just need to prepare the convincing test suite for the users proving the bug to AMD and have their faulty chips replaced.

**Comment by snicolet** [comment] 2018-03-01 23:12
Take 3: https://github.com/snicolet/Stockfish/commit/32d42d7d8edf1df9d092890119907465adfea68d

Get rid of the four stages CAPTURES_INIT, PROBCUT_CAPTURES_INIT, QCAPTURES_INIT and QSEARCH_RECAPTURES_INIT altogether, inlining their computations at the beginning of their next stages using an helper function called "generate_and_score_captures()".

Maybe not elegant (I am not sure, there are arguments pros and cons), but at least the compiled binary has a simpler jump table...

Same speed as master.

**Comment by noobpwnftw** [comment] 2018-03-02 00:09
@snicolet If we'd go this far maybe we should add an ARCH=x86-64-ryzen in Makefiles and fork the source code like `#ifdef (RYZEN) #endif`.

**Comment by snicolet** [comment] 2018-03-02 00:17
I am coming back to the assembly display of the jump table given by @noobpwnftw (thanks!)

![36705431-01f96306-1ba0-11e8-8131-865c5178dced](https://user-images.githubusercontent.com/6761856/36876084-85f4410c-1db3-11e8-85f3-fe9ce69c2715.png)

• The crash occurs indeed in a multi-byte NOP alignment instruction, probably `0f1f8000000000` according to this thread:
https://stackoverflow.com/questions/25545470/long-multi-byte-nops-commonly-understood-macros-or-other-notation

This are seven bytes of code emitted at the end of the first cases of the switch statement...

````C++
  case MAIN_SEARCH: case EVASION: case QSEARCH: case PROBCUT:
      ++stage;
      return ttMove;
````

to align the beginning of the block handling the next stages (the new four stages collapsed by the patch) on 16 bytes boundary:
````C++
  case CAPTURES_INIT:
  case PROBCUT_CAPTURES_INIT:
  case QCAPTURES_INIT:
  case QSEARCH_RECAPTURES:
      endBadCaptures = cur = moves;
      endMoves = generate<CAPTURES>(pos, cur);
     ....
````

This is why I have tried in my two versions of workarounds (take 2 and take 3) to reorder, shake or shrink the jump table, hoping that the alignment instructions would disappear naturally by reformatting the C++ code. Of course we should check the generated code by hand to be sure the `NOP DWORD ptr [EAX + 00000000H]` is no longer there.

• Is there a way to force GCC, via a compiler flag, not to emit NOP padding to align statements in a switch table? We probably want to keep function alignment and loop alignment, and selectively remove *that* switch alignment (anyway there are very few jump tables in Stockfish code).

**Comment by noobpwnftw** [comment] 2018-03-02 00:23
@snicolet 

> Is there a way to force GCC, via a compiler flag, not to emit NOP padding to align statements in a switch table?

From https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html:

> -falign-labels
> -falign-labels=n
> Align all branch targets to a power-of-two boundary, skipping up to n bytes like -falign-functions. This option can easily make code slower, because it must insert dummy operations for when the branch target is reached in the usual flow of the code.
> 
> -fno-align-labels and -falign-labels=1 are equivalent and mean that labels are not aligned.
> 
> If -falign-loops or -falign-jumps are applicable and are greater than this value, then their values are used instead.
> 
> If n is not specified or is zero, use a machine-dependent default which is very likely to be ‘1’, meaning no alignment. The maximum allowed n option value is 65536.
> 
> Enabled at levels -O2, -O3.
> 
> -falign-loops
> -falign-loops=n
> Align loops to a power-of-two boundary, skipping up to n bytes like -falign-functions. If the loops are executed many times, this makes up for any execution of the dummy operations.
> 
> -fno-align-loops and -falign-loops=1 are equivalent and mean that loops are not aligned. The maximum allowed n option value is 65536.
> 
> If n is not specified or is zero, use a machine-dependent default.
> 
> Enabled at levels -O2, -O3.

**Comment by noobpwnftw** [comment] 2018-03-02 01:17
@snicolet Some updates: it is not the NOP that crashed because in clang builds it crashed in the middle of some MOV instructions, it is more likely a bug in the processors' branch predictor while handling switch tables., I think our next_move() logic looks too fancy to them.

**Comment by mcostalba** [comment] 2018-03-02 07:25
Do you really think we _have_ to address compiler/processor bugs in SF sources?

**Comment by snicolet** [comment] 2018-03-03 09:33
In general, no. In this particular case I think we _should_ if we can, yes.

For two reasons:

a) it is very bad publicity for the project if Stockfish stops working on Ryzen.

For instance, SF8 was used as benchmark for speed by some hardware sites when Ryzen came out:
https://www.hardware.fr/articles/970-1/intel-core-i7-8700k-core-i5-8600k-core-i5-8400-core-i3-8350k-test.html . I just don't want their next article to begin with "last year we used Stockfish 8 and Komodo for testing the speed on chess IA on Ryzen, but the last version of Stockfish crashes randomly so this year we only publish results for Komodo"

b) the 1600 Ryzen cores that @noobpwnftw kindly provided for fishtest really boosted the speed of tests while they were there. Now he has replaced them by 800 Intel cores, which are nice too :-) but still gives fishtest 50% less global power. Having the 1600 cores back would definitely accelerate SF development.

**Comment by Ipmanchess** [comment] 2018-03-03 12:25
Can i ask which version is used on Ryzen.. pop or bmi2 version ?!

It's well known that these bmi2 compiles goes much slower on Ryzen/threadripper/EPYC cpu's!
Maybe the problem seen here is maybe to do something with it..if bmi2 version is used..

**Comment by snicolet** [comment] 2018-03-12 23:57
@noobpwnftw 

If you still have access to the Ryzen machines, could you try the following branch: https://github.com/snicolet/Stockfish/tree/movepicker_no_ttm

I have completely removed the four "transposition table move" in the MovePicker, thus simplifying the jump table (it now has 15 stages instead of 19), and in particular removing the padding nops at the top.

I would be very curious to know how the Ryzen handles this now, and if the crashes are still there.

**Comment by Vinvin20** [comment] 2018-03-14 23:57
More information here : 
http://fujii.github.io/2017/06/23/how-to-reproduce-the-segmentation-faluts-on-ryzen/
and here : https://community.amd.com/thread/215773?start=1860&tstart=0

**Comment by noobpwnftw** [comment] 2018-03-18 09:52
@snicolet The behavior on my Ryzen is random and it is not only causing segfaults, but also different kinds of weird crashes including general protection faults. I think it is not solvable with coding.

For this fork it still crashed with segfaults after some 200 games, but this one passed 5000 games https://github.com/official-stockfish/Stockfish/pull/1454.

**Comment by noobpwnftw** [comment] 2018-03-23 18:59
After the recent master commit, AMD amazingly responded to my RMA request(a week ago) as I quote a part of its original text:

"另外，我们在多个处理器上运行了标准的Stockfish的源代码（source code），并未发现segfault错误和GP错误。同时，我们运行您客户提供的程序时仅发现GP错误。但如前所述，在标准的Stockfish 源代码中没有发现错误。

综上，我们的结论是没有证明显示锐龙处理器是造成您问题的原因。我们建议您升级您的BIOS，并且使用主板厂商验证的内存型号（参照厂商的内存支持列表）。从而确保您的机器配置是在最稳定和优化的环境下使用验证过的稳定内存条。"

Shame on you AMD, seriously.

**Comment by noobpwnftw** [comment] 2018-03-23 19:07
For those who can't read Chinese, they said that they ran standard compilation of Stockfish(assuming master or release) on multiple CPUs and did not find segfault or GP error, when running my source code build I provided above, they only find GP error.

So they think that it is not the CPU that is bugged, I need to update BIOS, use memory modules from QVL, etc, to ensure a "stable" system.

**Comment by noobpwnftw** [comment] 2018-03-23 19:38
I’m however satisfied with the fact that they are suggesting me that the latest build does not crash from their tests, so bd59560480cc4f43a4ba75dc827ba27bcebb92dd appears to get around with the bug as we hoped. I’d never buy any AMD chips and SF won’t crash anymore, case closed.

**Comment by Vizvezdenec** [comment] 2018-03-24 21:19
I guess this one can be closed now, is it, @snicolet ?

**Comment by Vizvezdenec** [comment] 2018-03-24 21:31
http://tests.stockfishchess.org/tests/view/5ab6b6870ebc5902932cbd1e well I actually see some crashes there.
Not as much as we had at start but still much more then in usual tests I guess...

**Comment by noobpwnftw** [comment] 2018-03-25 03:17
@Vizvezdenec Yes, I think we can close this one because:
1. Recent master crashes way less than before, at least the hot path has no bug triggering pattern anymore
2. Random crash on crappy CPUs is really not a software problem

**Comment by snicolet** [comment] 2018-03-25 10:16
Closing.

The good point is that we have all learned a lot, and that AMD engineers have heard of Stockfish by now :-)

**Closed by snicolet** 2018-03-25 10:16 UTC
