### ISSUE TITLE
wrong evaluation of draw position

### ISSUE THREAD

**Issue by mendi80** [official-stockfish/Stockfish#4103] opened 2022-07-06 21:40 UTC
Position: q7/8/2p5/B2p2pp/5pp1/2N3k1/6P1/7K w - - 0 1
The latest version (5/07/2022) miss the draw and evaluate -4.8
Compared to an older version like 14/05/2022 that see the draw and evaluate 0.00.

**Comment by vondele** [comment] 2022-09-04 05:50
I think this is an interesting hard puzzle for engines in that it basically needs to resolve to the 50 move rule to see the draw evaluation. For this one needs to extend search very deep, which causes something like #3911 .. on the other hand, the right move is found almost instantly.

**Comment by MaiaChess** [comment] 2022-09-09 18:18
There is also the reverse of this problem
Position: rnb1q2k/2ppnr1p/p4p1B/3PpP1N/1P1bP1R1/2NB4/1PP3PP/5R1K w - - 5 22
SF15 don't see the lose and evaluate 0.00 = draw
Compared to an older version SF14 that see the lose and evaluate -2.00

![image](https://user-images.githubusercontent.com/112132122/189417788-5fe47c41-771d-469f-98b9-dc0e41bbafdc.png)

**Comment by Craftyawesome** [comment] 2022-09-09 18:45
> There is also the reverse of this problem Position: rnb1q2k/2ppnr1p/p4p1B/3PpP1N/1P1bP1R1/2NB4/1PP3PP/5R1K w - - 5 22 SF15 don't see the lose and evaluate 0.00 = draw Compared to an older version SF14 that see the lose and evaluate -2.00

Do you have the full solution? SF14 also eventually drops to near 0.

**Comment by MaiaChess** [comment] 2022-09-09 19:01
**SF14 at depth 40 evaluate -1.50**

![image](https://user-images.githubusercontent.com/112132122/189423847-44e821bf-7a4d-45bc-8b30-e89d51363816.png)



**SF11 at depth 40 evaluate -2.60**
![image](https://user-images.githubusercontent.com/112132122/189424167-4f6771e6-1a5a-47c2-8d9e-5e166038f266.png)

**Comment by dav1312** [comment] 2022-09-09 19:02
This is the line that I got doing some fast analysis

```
[FEN "rnb1q2k/2ppnr1p/p4p1B/3PpP1N/1P1bP1R1/2NB4/1PP3PP/5R1K w - - 5 22"]

22.Nxf6 Qd8 23.d6 cxd6 24.Bc4 d5 25.Ncxd5 Nxd5 26.Nxd5 Ra7 27.c3 d6
28.Rf3 Nc6 29.Rg5 Rab7 30.h4 Ba7 31.Kh2 Ne7 32.Nxe7 Qxe7 33.f6 Qe8 34.Bxf7 Qxf7
35.Rg7 Be6 36.g4 *
```
But then the latest dev refuted the whole thing with 24.Rf3 which is winning for white

**Comment by Craftyawesome** [comment] 2022-09-09 20:06
> **SF14 at depth 40 evaluate -1.50**

Keep in mind that lichess SF14 is using a smaller net that's a few elo worse on average. It looks like it missed 24.Rf3 as mentioned above.

**Comment by MaiaChess** [comment] 2022-09-09 20:59
> But then the latest dev refuted the whole thing with 24.Rf3 which is winning for white

That's right , after Rf3 It seams that white is winning ! therefore, the position is not draw

**Comment by dav1312** [comment] 2022-09-09 21:03
> white is winning ! therefore, the position is not draw

That is the wrong conclusion. It's a draw because black can play 22... Rxf6

**Comment by MaiaChess** [comment] 2022-09-11 05:43
**Wrong evaluation of whole game !!!**

https://lichess.org/yIlhD9xz

This game is between **SF8** and **AlphaZero** that analyzed by **SF15** 

![image](https://user-images.githubusercontent.com/112132122/189513826-378052f3-7823-4b69-8ecc-bb8f197c8912.png)

We know **SF15** is very stronger that **SF8**  

Please tell me why white lose without any mistake or even inaccuracy ??

<img src="https://user-images.githubusercontent.com/112132122/189514148-940e631d-ad40-42f0-9a74-409ac9063289.png" width="600">

**Comment by peregrineshahin** [comment] 2022-09-11 06:01
@MaiaChess I will assume you're legit asking
First the concept of mistakes and inaccuracies is not something that is embedded in Stockfish, it is just Lichess way of interpreting the amount of eval shift, and yeah you can lose even if you don't play any mistakes and inaccuracies in chesscom and lichess by being outplayed a bit by bit without much gap in the shift of the eval that's one thing

Second Lichess uses another net and maybe a modified binary for SF to run smoothly
Third it is not SF 15 also its Stockfish 14+ on my end
Fourth you cannot compare an engine running on a browser to find the critical eval shift between two engines, do it on a good hardware
Fifth this is unrelated to the issue
I can go on and on

**Comment by MaiaChess** [comment] 2022-09-11 06:18
![image](https://user-images.githubusercontent.com/112132122/189514919-ea95d552-0b44-468d-bd95-62e2ac594c69.png)

lichess analyze the game via stockfish 15  & its own dedicated server ... not local browser 

Also pay attention this game is from sf8 , so sf15 must can find mistake of sf8 , So how should we understand why black lost ?

**Comment by peregrineshahin** [comment] 2022-09-11 06:29
Simply black is lost because it got outplayed a bit by a bit, there are millions/billions of possibilities
And some variations has a little difference in the eval that choosing from them is the battle ground between engines
Download SF 15 yourself and let it run with good parameters and analyse it well you will certainly find moments that has greater eval shift
When two engines play against each other that's the expected behavior, outplaying another engine can be done in those lines that for example differs 0.04 or even less also and it makes sense because it can accumulate
And anyways The goal of SF 15 wasn't a chess evaluater, it's an engine that needs to make good moves and win
If there is a better eval in recent versions its a byproduct of the recent elo gains (product being able to get better results than the previous one) but it's not the main goal of stockfish development
And if it is really it's unobtainable anyways because nobody knows the real truth about the position anyways
I suggest you think of SF 15 as an engine that wouldn't make the mistakes that SF 8 did
And not mainly a better evaluator (which indeed SF 15 already is)

**Comment by MaiaChess** [comment] 2022-09-11 07:19
> Simply black is lost because it got outplayed a bit by a bit

This is not completely true , please pay attention lichess analyze the game **from end to first , not first to end**

 Just one inaccuracy cant cause lose a game , **inaccuracy defined as the delta function for evaluate mistake** 
 
You will see the analysis of this game in the future by SF20 that was able to find blunder & mistake from game 

 please pay attention the SF8 did not have NNUE for play game against AlphaZero

**Comment by peregrineshahin** [comment] 2022-09-11 07:37
For god sake what do you mean by a Lichess server analysis?
Request analysis takes 1 sec to finish for the whole game
How is this any hella trustable
Don't get me wrong I love Lichess, but if you even run the analysis in your broweser it's even better than this request server analysis button
When you want to analyze games between two engine you can't just by one click and 1 sec get the full report maybe you can in 2090 but not in 2022
You can go to the Lichess source code or ask somebody in lichess and they will totally agree that this feature can't and shouldn't give reports about engine vs engine games
You are repeating yourself again and again, just go see how many nodes does this feature calculate per move
It is not a good indicator
Whereas it is for human games but also not for top players out there

**Comment by bftjoe** [comment] 2022-09-11 07:42
Lichess uses fixed nodes analysis at low hash size, it means nothing in engine vs engine play.

**Comment by dav1312** [comment] 2022-09-11 08:22
@MaiaChess Please don't use Lichess's server analysis for engine vs engine games.
Their analysis is limited to 1.5M nodes, intended for games between humans.

**Comment by MaiaChess** [comment] 2022-09-11 18:24
That's right , but i found another analyze of this game by SF11

https://lichess.org/P17ZTBlR

![image](https://user-images.githubusercontent.com/112132122/189542677-481429db-dd90-428f-86a4-8b3915a1c0df.png)

Compare With analyze of this game by SF15

https://lichess.org/yIlhD9xz

![image](https://user-images.githubusercontent.com/112132122/189542749-b2292998-041e-48b9-ad01-34e35cb9d2de.png)

It show that analyze of SF11 is more clear that SF15 , SF15 is stronger that SF11 but this power will cause its weaknesses because it is not perfect

**Comment by MaiaChess** [comment] 2022-09-12 20:06
Another wrong evaluate by sf15 

position : 2bqr1k1/4rpbp/ppPp1np1/8/6P1/Q1N1PP2/PP5P/R1BR2K1 w - - 0 24

**SF15 say e4 is bestmove and evaluate -3.70**

`info depth 30 seldepth 50 multipv 1 score cp -527 nodes 55292078 nps 1020393 hashfull 1000 tbhits 0 time 54187 pv e3e4 f6e4 c3e4 e7e4 f3e4 e8e4 a3d6 e4e1 d1e1 g7d4 d6d4 d8d4 e1e3 d4g4 g1f2 g4h4 f2g1 h4d4 a2a4 c8h3 c1d2 d4b2 a1a3 b2d2 e3h3 d2c1 g1g2 c1c6 h3f3 g8g7 a3c3 c6d7 c3c2 d7g4 g2f2 g4a4 c2c7 a4e8 f3e3 e8b5 f2g1`

![image](https://user-images.githubusercontent.com/112132122/189743600-2bfa9a5f-e9a2-463b-bb2a-97010c4fa997.png)

### _But compare with sf11 ...._

**SF11 say bestmove is Qxd6 and evaluate -3.93**
**SF11 say  e4 is not bestmove and evaluate -4.91**

![image](https://user-images.githubusercontent.com/112132122/189746067-b706a078-bc6b-4d92-b427-bbb04f8578a6.png)



which one is correct ? sf15 or sf11 ?

**Comment by MaiaChess** [comment] 2022-09-12 20:43
(@dav1312 , @peregrineshahin , @Craftyawesome , @bftjoe , ....)

**Please friends who have disagreed with me  , answer this question , thanks**

**Comment by Craftyawesome** [comment] 2022-09-12 21:56
> which one is correct ? sf15 or sf11 ?

The position is completely lost. It is subjective what the best move to try to save the game is. Neither is really wrong or right.

And if you want to argue subjective, Leela also prefers e4. -5 to -11.

**Comment by MaiaChess** [comment] 2022-09-12 23:20
> The position is completely lost

its not completely lost , **e4 is blunder** , also SF15 prefer Qxd6 only depth=>40 

this is the same result of SF11 at depth 20

**Comment by jxu** [comment] 2022-09-16 06:40
@MaiaChess are you impersonating the creators of https://github.com/CSSLab/maia-chess?

**Comment by MaiaChess** [comment] 2022-09-16 07:08
Not just similar names and fans 

@jxu Please send the content related to this issues , thanks

**Comment by shorome2** [comment] 2022-09-17 19:12
> Just one inaccuracy cant cause lose a game , **inaccuracy defined as the delta function for evaluate mistake**
> You will see the analysis of this game in the future by SF20 that was able to find blunder & mistake from game
> please pay attention the SF8 did not have NNUE for play game against AlphaZero

I should have grabbed popcorn for this...

Your view of Computer Engine Chess is a bit simplistic. SF's NN is tuned on ~5k CPUs. The tests you gave weren't even performed on TCEC equipment much less all of Fishtest. The accuracy of a specific move in the middle game isn't objective... it's subjective to the ideas being calculated vs what the opponent is actually doing. If your opponent already played this game and won and it remembered the game perfectly, do you expect an engine with very limited computing power to be able think far enough ahead to draw these games? 

I expect SF using max threads and hash and a 7man TB to be able to correctly evaluate the positions you gave. The only problem is you're expecting moves that were calculated by a supercomputer to be refuted by your PC at low depth, low hash, and low thread count --without an EGTB.

Should there be better scalability between what SF can do on a supercomputer vs your PC? yes
But, as was mentioned earlier, you should probably use a super computer to analyze a game from another supercomputer... 40 depth is nothing... I have a third gen ryzen 7 with only 16 GB ram and it can reach 70 depth 100 selective depth in a matter of 3-5mins on these game positions

**Comment by MaiaChess** [comment] 2022-09-17 19:57
> Should there be better scalability between what SF can do on a supercomputer vs your PC ? 

_Yes that's right , But remember Kasparov's loss to an amateur opponent , Kasparov thought that his opponent had an idea for each move but the opponent was just playing his simple game_ 

 **SF15 is stronger than SF11 but this power will cause its weaknesses because it is not perfect**
 
 https://github.com/official-stockfish/Stockfish/issues/4103#issuecomment-1243017262

**Comment by RogerThiede** [comment] 2022-09-17 22:10
@MaiaChess, what is it that you're trying to convey?  Do you believe you have found an actual issue in the source code?  Do you believe you have found a _systemic_ issue in the latest neural network?
We can discover many positions which are draw by Syzygy Tablebase lookup but which the latest neural network gives vastly different evaluations.

**Comment by jxu** [comment] 2022-09-17 22:11
> > Should there be better scalability between what SF can do on a supercomputer vs your PC ?
> 
> _Yes that's right , But remember Kasparov's loss to an amateur opponent , Kasparov thought that his opponent had an idea for each move but the opponent was just playing his simple game_
> 
> **SF15 is stronger than SF11 but this power will cause its weaknesses because it is not perfect**
> 
> [#4103 (comment)](https://github.com/official-stockfish/Stockfish/issues/4103#issuecomment-1243017262)

what does this even mean? it's too vague to tell and there's no point in comparing engine calculations to human calculations. maybe Kasparov lost a simul or blitz game to an amateur once, but it sounds more like a made up urban myth

**Comment by MaiaChess** [comment] 2022-09-17 22:22
>  Do you believe you have found a _systemic_ issue in the latest neural network? 

yes , if we can analyze  position for depth 100 then sf15 is absolutely stronger that sf11 , but for low depth 20-30 , sf11 is better than sf15  , for example see this :

https://github.com/official-stockfish/Stockfish/issues/4103#issuecomment-1244339190

> We can discover many positions which are draw by Syzygy Tablebase lookup but which the latest neural network gives vastly different evaluations.

please send your position that you say sf15 prefer better move than sf11

**Comment by MaiaChess** [comment] 2022-09-17 22:27
> what does this even mean?

I mean that sometimes simple moves are more powerful than each moves 

we cant analyze every position for depth 100 - 200 

**Kasparov said that start game is same end game with 32 pieces**

**Comment by jxu** [comment] 2022-09-17 23:33
> I mean that sometimes simple moves are more powerful than each moves


?????????????

**Comment by MaiaChess** [comment] 2022-09-18 00:09
> ?????????????
```

info depth 10  bestmove A1

info depth 20  bestmove A2

info depth 30  bestmove A3

info depth 30  bestmove A4
......

info depth N  bestmove AN
```


@jxu  we cant find  info depth ∞  bestmove , sometimes bestmove is a simple move at low depth , NNUE training is done for high depth & it cause may return not bestmove

**Comment by MaiaChess** [comment] 2022-09-21 00:18
https://user-images.githubusercontent.com/112132122/191386851-17fd8ef8-17e7-4448-98dc-030692ce68e0.mp4

_**Kasparov Comments on Alphazero vs. Stockfish match**_

**Comment by nathan-lc0** [comment] 2022-11-21 02:42
The original position that started this issue seems to no longer be a problem. Latest stockfish finds ne4 and evaluates it as 0.00 almost instantly on a single thread. Perhaps can be closed.

**Comment by Craftyawesome** [comment] 2022-11-21 03:06
I am getting -2.08 on a single thread. Multithread seems to flatline at some random eval, sometimes 0. But either way, the issue tracker might not be the best place for positions SF gets wrong.

**Comment by vondele** [comment] 2022-11-21 06:37
I'm closing this in light of the last two comments

**Closed by vondele** 2022-11-21 06:37 UTC
