### ISSUE TITLE
position.cpp: Line 934

### ISSUE THREAD

**Issue by d3vv** [official-stockfish/Stockfish#2374] opened 2019-10-26 10:44 UTC
`move_piece(pc, to, from); // Put the piece back at the source square`

Line looks like strange due to declaration:

`inline void Position::move_piece(Piece pc, Square from, Square to) {`

"from" second argument, and "to" third..

**Comment by gvreuls** [comment] 2019-10-26 12:28
Read what the comment says. This was intended, it's putting the piece back at the square it was moved from earlier.

**Comment by d3vv** [comment] 2019-10-27 17:20
I mean, absolutely any programmer looking at this code can use it as an example. Not everyone (including myself) looks at definitions when there are thousands of them. Here either call the variables as well, or write the code as well.

**Comment by d3vv** [comment] 2019-10-27 17:22
And even if you look at the comment, it’s not obvious that the variable assignments are exchanged

**Comment by Rocky640** [comment] 2019-10-27 20:42
If you have a replacement to suggest, you are welcome.

**Comment by d3vv** [comment] 2019-10-27 21:52
@Rocky640 Just I do not believe that if I do this work I will not be subjected to arrogant criticism..
I saw it before from some SF developers.. 
My position is that any algorithm should be fastest even if it doesn’t affect anything..
A bunch of shit was thrown at me when when I suggested replacing slow and non-quality prng-algorithm with one of them:
http://prng.di.unimi.it/

My pleasure, my honor.. But no.. sorry
I truly wish to SF prosperity only
But I will only try to show places that are "not-ice" for me.. And decide for yourself

**Comment by gvreuls** [comment] 2019-10-28 01:48
If you're referring to me, sorry if you feel I was arrogant towards you. We really appreciate the work you do and the many CPU hours you have contributed to the project.

The point about the code is that this is part of ``Position::undo_move(Move m)`` and a few lines above your line 934 you can see how the variables get their names:
https://github.com/official-stockfish/Stockfish/blob/648c7ec25db2040c0af34dd846dfa3f57af5ad0a/src/position.cpp#L909-L911
So the variable names where taken from fields in ``Move`` with the same names, which seems perfectly logical to me.

No hard feelings okay?

**Comment by MichaelB7** [comment] 2019-10-28 06:04
@d3vv  I’m sure @gvreuls meant no ill will.  Written words can often be read as more harsh than if they were spoken. Many here speak/write English as a second language - and in some cases they use google translate.  That also can cause unintended meanings. I’m am certain that I can speak for the group and say that we all appreciate your work and contributions to the project. God Bless.

**Comment by d3vv** [comment] 2019-10-28 10:41
@gvreuls I wasn't talking about you :)
Take it easy

**Comment by snicolet** [comment] 2020-01-09 23:31
Closing.

**Closed by snicolet** 2020-01-09 23:31 UTC
