### ISSUE TITLE
Stockfish 12 cannot see this mate in 20 unless you make the first correct move for it.

### ISSUE THREAD

**Issue by DLPB2** [official-stockfish/Stockfish#3338] opened 2021-02-08 01:40 UTC
https://www.chess.com/forum/view/more-puzzles/mate-in-20?page=1

Houdini in 2011 could.

I am using Intel i9, 10 cores.

**Comment by DLPB2** [comment] 2021-02-08 01:47
It seems to get fixated on NE5-F3 as a first move.

**Comment by Torom** [comment] 2021-02-08 10:27
I can confirm that. Crystal finds the mate immediately.

**Comment by vdbergh** [comment] 2021-02-08 11:38
Stockfish is not optimized for mate finding but for Elo.

**Comment by scchess** [comment] 2021-02-08 11:51
@vdbergh is 100% correct. Stockfish is never made for solving silly puzzles like it. It's strength builds on it's ability to play better chess.

**Comment by DLPB2** [comment] 2021-02-08 18:58
@vdbergh is 100% correct. Stockfish is never made for solving silly puzzles like it. It's strength builds on it's ability to play better chess.

That's missing the point entirely.  The fact it misses such an easy forced mate is a problem.  This is meant to be the strongest engine on Earth.  This "silly" puzzle highlughts a flaw in how Stockfish isbehaving.  It sucks at closed positions, evidently.  It should be contemplating the other branches - but for 30 minutes on an i9 10 core processor it sits there doomed to one branch that leads nowhere.

**Comment by BM123499** [comment] 2021-02-08 19:12
`Strongest` doesn't mean that it will always win, or that it will always find the best move. It means it's excellent on most common positions of the game and good on less common positions.
It's hard to improve closed position because it's not common to happen. The puzzle is good, but you will hardly find in a normal game. And the engine is still winning, but not on the fastest way.
Everything has a weak spot. You just found out an example. If Stockfish was that strongest engine, it would be Invictus in all games.

**Comment by ddobbelaere** [comment] 2021-02-08 19:23
> That's missing the point entirely. The fact it misses such an **easy forced mate** is a problem. This is meant to be the strongest engine on Earth. This "silly" puzzle highlights **a flaw** in how Stockfish is behaving. It **sucks at closed positions, evidently**. It **should be** contemplating the other branches - but for 30 minutes on an i9 10 core processor it sits there doomed to one branch that leads nowhere.

Easy forced mate, flaw, sucks at closed positions (evidently!).

Dude...

**Comment by DLPB2** [comment] 2021-02-08 19:34
"dude" sounds like a 2 year old's response.  So does "It's not a bug, it's a feature."  Do something about it - or don't.  This is simply a report.

**Comment by BM123499** [comment] 2021-02-08 19:45
@scchess may have used a strong word `silly`. but you, @DLPB2, seem to be overreacting. it's indeed a flaw... but it's not like it will lose the game either. It's may be a structural failure that is not optimize to evaluate this kind of position. But as I said, we should optimize most common position over less common position.

**Comment by Sopel97** [comment] 2021-02-10 21:47
1. This is a composition, not a position from an actual game. Stockfish is not made to solve such positions and we don't care about them.
2. Every issue like that should be immediately closed with "Cannot fix" because it's impossible to make a fix targetting a single position.

**Comment by snicolet** [comment] 2021-02-10 22:21
Cannot fix, and the discussion is shifting towards insults.

Closing.

**Closed by snicolet** 2021-02-10 22:21 UTC

**Comment by bahaullah** [comment] 2021-04-13 10:38
Puzzles are a great way to teach chess, Houdini is moving in that direction with puzzle solving Avatars and natural language commentary / Analysis, shouldn't Stock also?
