### ISSUE TITLE
Empty string in position fen crashes Stockfish

### ISSUE THREAD

**Issue by AnotherCommander** [official-stockfish/Stockfish#665] opened 2016-05-04 11:47 UTC
Using revision 3487eb9 x86-64-modern build for Windows,starting up Stockfish and entering
```
position fen 
```
(i.e. no string for position) results in segfault.

Tested on Windows 7 x64, Intel i7 640M 2.8GHz, 8GB RAM, Intel HD gfx. The crash happens with a self-compiled binary, as well as the binary downloaded from abrok.eu.

**Comment by AnotherCommander** [comment] 2016-05-04 12:10
Crash backtrace generated by make build ARCH=x86-64-modern COMP=mingw -j4, with Makefile build flags edited for -O0 -g:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000045d642 in attacks_bb<(PieceType)4> (s=SQ_NONE, occupied=0)
    at bitboard.h:246
246       return (Pt == ROOK ? RookAttacks : BishopAttacks)[s][magic_index<Pt>(s, occupied)];
(gdb) bt
#0  0x000000000045d642 in attacks_bb<(PieceType)4> (s=SQ_NONE, occupied=0)
    at bitboard.h:246
#1  0x00000000004247b8 in Position::attackers_to (this=0x22f280, s=SQ_NONE, 
    occupied=0) at position.cpp:458
#2  0x000000000046b5ab in Position::attackers_to (this=0x22f280, s=SQ_NONE)
    at position.h:306
#3  0x00000000004239cd in Position::set_state (this=0x22f280, si=0x12f0ee0)
    at position.cpp:325
#4  0x0000000000423639 in Position::set (this=0x22f280, fenStr=..., 
    isChess960=false, si=0x12f0ee0, th=0x329dd0) at position.cpp:279
#5  0x0000000000000000 in ?? ()
(gdb) 
#0  0x000000000045d642 in attacks_bb<(PieceType)4> (s=SQ_NONE, occupied=0)
    at bitboard.h:246
#1  0x00000000004247b8 in Position::attackers_to (this=0x22f280, s=SQ_NONE, 
    occupied=0) at position.cpp:458
#2  0x000000000046b5ab in Position::attackers_to (this=0x22f280, s=SQ_NONE)
    at position.h:306
#3  0x00000000004239cd in Position::set_state (this=0x22f280, si=0x12f0ee0)
    at position.cpp:325
#4  0x0000000000423639 in Position::set (this=0x22f280, fenStr=..., 
    isChess960=false, si=0x12f0ee0, th=0x329dd0) at position.cpp:279
#5  0x0000000000000000 in ?? ()
(gdb) ```

**Comment by aprijal-psrb** [comment] 2016-05-04 12:37
Any wrong fen will crashed include empty fen, i think it's code will hard to handled

**Comment by mcostalba** [comment] 2016-05-05 07:05
FEN string is assumed to be correct. Indeed the usual way to get the FEN string is from the GUI during game play and the parsing functions rely on FEN to be correct (as always is) to do the job.

This is by design, so I close this as non-issue.

**Closed by mcostalba** 2016-05-05 07:05 UTC
