### ISSUE TITLE
stockfish crash

### ISSUE THREAD

**Issue by ab-chesspad** [official-stockfish/Stockfish#3676] opened 2021-08-24 19:02 UTC
I do not think that it's a good idea to let SF crash on invalid input.
In fact, it crashes on invalid FEN, e.g.
position fen 8/8/8
stockfish: position.h:252: Stockfish::Square Stockfish::Position::square(Stockfish::Color) const [with Stockfish::PieceType Pt = (Stockfish::PieceType)6]: Assertion `count<Pt>(c) == 1' failed.
Segmentation fault (core dumped)

**Comment by ppigazzini** [comment] 2021-08-24 19:51
See the answer on the wiki https://github.com/glinscott/fishtest/wiki/Fishtest-faq#why-does-sf-crash-on-incorrect-fen-or-fens-of-illegal-positions

**Comment by ab-chesspad** [comment] 2021-08-25 15:48
This is a very lame answer.
First, on"no established mechanism to communicate such an error". CF still "communicates" the error by crash. When SF is running as a separate process, like in DroidFish, it's not easy to figure out what is wrong here. The very least is to issue an error message and ignore the faulty command.
Second, there is no need to fully verify FEN correctness. Only the things that would break the program.
Third, SF should not crash in any situation. Letting it crash creates many further problems and does not look professional.

**Comment by ppigazzini** [comment] 2021-08-25 16:39
> This is a very lame answer.

Please, read the original forum thread for some insights about that answer (to a very frequently asked question) It's funny how you will find several answers for any of your questions :)
https://groups.google.com/g/fishcooking/c/KxZjB0VsZHk/m/zs-dGxaoDQAJ 

> First, on"no established mechanism to communicate such an error". CF still "communicates" the error by crash. When SF is running as a separate process, like in DroidFish, it's not easy to figure out what is wrong here. The very least is to issue an error message and ignore the faulty command.

As stated in the wiki answer: "If you find a GUI through which you can crash Stockfish or any other engine, then by all means report it to that GUI's developers."

> Second, there is no need to fully verify FEN correctness. Only the things that would break the program.

As stated in an answer of that thread:
"If this one crash is "fixed", then 999,999 ways of crashing Stockfish remain. What you are asking for is to be provided with an false sense of security. You would like to think that you can rely on Stockfish being secure, but it is not and it will never be. Not if this crash is "fixed" and not if the next 100 crashes you will report are "fixed". "

> Third, SF should not crash in any situation. Letting it crash creates many further problems and does not look professional.

As stated in an answer of that thread:
"Anyway, have you thought about what you would want SF to do?
Silently accept corrupted input and produce nonsensical output? 
Output an error message? Please let us know which UCI diagnostic you are thinking of... none exists.
I guess SF could be made to exit(1) upon encountering illegal input. But there is no need for that and it would needlessly clutter the code."

**Comment by JackWright347** [comment] 2021-08-28 14:47
Yeah, that's the neat part. There has been an obvious fundamental software design problem ("to crash or not to crash") for years, but there is no will to address it. There are more important things to do. As long as the ELO number can be driven up by the NNUE updates, just leave us alone with the unimportant little things. No one feels responsible for the crashes. Nobody dares to take care of them.

**Comment by jhellis3** [comment] 2021-08-28 15:49
And those damn ninjas holding a knife to your throat.

**Comment by jhellis3** [comment] 2021-08-28 15:51
But really it sounds like a good job for you.  Something to occupy your time.  Or you could just pay someone else to spend theirs....

**Comment by JackWright347** [comment] 2021-08-28 17:02
That's exactly what I mean. Thank you!

**Comment by jhellis3** [comment] 2021-08-28 18:45
"There has been an obvious fundamental software design problem ("to crash or not to crash") for years, but there is no will to address it. ... No one feels responsible for the crashes. Nobody dares to take care of them."  

Looks like that includes JackWright347.

**Comment by jhellis3** [comment] 2021-08-28 18:46
"In fact, if I had my way, I would solve this one concrete invalid FEN crash problem differently than with C++ try{} and catch(...)."

Literally nobody is stopping you.  Nobody.

**Comment by JackWright347** [comment] 2021-08-28 23:00
As I said, the problem is not technical, any normal C++ developer can get it implemented and unit tested in no time:

```
if (!Position::is_valid_fen(gen)) {
   sync_cout << "info string ERROR: invalid FEN" << sync_endl;
   return;
}
```

How the function is_valid_fen() could look like has been discussed and implemented a thousand times as well
https://chess.stackexchange.com/questions/1482/how-do-you-know-when-a-fen-position-is-legal
https://github.com/daylen/stockfish-mac/blob/master/Chess/position.cpp

and anyone could do it, including jhellis3 probably.

The problem is, in my humble opinion and experience, that the maintainers of this project just don't want this. Instead, fairy tales are told again and again that this has been the explicit stance of one of the "founding fathers" and that this is the way it is and also tons of documentation is written that "Crashing is OK". That's why I don't waste my time to make such pull requests. I do not like to waste my time. But please, at any time someone else, maybe jhellis3, can try to get it through. Good luck.

**Comment by jhellis3** [comment] 2021-08-28 23:58
But I don't care.   And my time is too valuable for you to afford. Maybe somebody that cares should do it, or pay someone else for their time.  Either would be more productive than whatever this is....

**Comment by jhellis3** [comment] 2021-08-29 00:00
And again you don't need to get it through, just make your own branch and live your dream, nobody is stopping you.

**Comment by JackWright347** [comment] 2021-08-29 08:39
Thank you, I knew you'd say the same thing again. That's exactly what I mean. You don't care, everyone else doesn't care, by now I don't care either, my time is also too valuable to explain the elementary basics that no software should crash without an error message, as the OP has already tried in vain. You learn that in your first software engineering lectures if you are a professional software developer.

Well, it is established that "Stockfish crashes are OK". Why bother. Thanks you and good luck!

**Comment by vdbergh** [comment] 2021-08-29 09:21
It is not a technical but a philosophical issue.  Personally I do not agree with the SF philosophy that crashing is OK (especially since the precondition for SF to work correctly is unverifyable) but I also see no point in getting worked up about it.

**Comment by jhellis3** [comment] 2021-08-29 11:34
My time is too valuable, but someone else's isn't.  I think we may be getting to the root of the issue.

**Comment by ab-chesspad** [comment] 2021-09-22 18:58
Hi Joseph,
how can I create a branch in SF repository? I want to push my changes
regarding building SF as shared library and handling errors with exceptions.
Thank you
Alex Bootman

**Comment by ppigazzini** [comment] 2021-09-22 20:29
```bash
# login in GitHub and fork https://github.com/official-stockfish/Stockfish
# clone your Stockfish GitHub repo as local git repo origin remote
git clone https://github.com/ab-chesspad/Stockfish
# add upstream remote
git remote add upstream https://github.com/official-stockfish/Stockfish
git config user.name "ab-chesspad"
git config user.email "your_email_here"

# to keep you local git and origin up to date with latest upstream
git fetch -p origin
git fetch -p upstream
git checkout master
git reset --hard upstream master
git push origin master

# make a local new branch
git checkout -b your_new_branch
# write your code in .ccp .h
git commit -a -m "Write here your commit msg"
# push your branch on origin
git push origin your_new_branch
# login in your GitHub repo and open a PR toward official repo
```

**Comment by vondele** [comment] 2022-02-20 18:07
closing. As before, we expect input to conform to the specs.

**Closed by vondele** 2022-02-20 18:07 UTC
