### ISSUE TITLE
SF dev version (October, 14) PV analysis bug

### ISSUE THREAD

**Issue by Coolchessguykevin** [official-stockfish/Stockfish#1785] opened 2018-10-22 16:22 UTC
Hello, dear developers!

Reporting a terrible bug that I found in the SF dev versions after of October 14th.

The fact is that the SF in the PV analysis starts to show crazy PVs. In them, it offers frankly losing and weak moves, loses the queen without compensation with one move, and shows very weak moves very often one PV after one.

This happens most often in complex positions.

I checked the modern and bmi version on two different computers (both with 4 cores and 7 threads for SF). My GUI is Aquarium 2018. The SF settings were default (but UCI analysis mode was ON and Analysis contempt was BOTH and = 0).

I have a suspicion that this happened after adding the "Correctly track down pv even in fail-high case" patch.

I suggest to look at the example. There is a position:
r1b1kb1r/pp2pppp/2n2n2/2Pp4/5B2/q3PN2/P1PN1PPP/1R1QKB1R w Kkq - 0 8

Below I place two PVs in which SF easily lose the queen in two principal continuations. 

[FEN "r1b1kb1r/pp2pppp/2n2n2/2Pp4/5B2/q3PN2/P1PN1PPP/1R1QKB1R w Kkq - 0 8"]

{[#]} 8. c4 (8. Bb5 g6 9. Ne5 Qxc5 10. c4 Bg7 11. Qa4 O-O 12. Bxc6 bxc6 13.
Nd3 dxc4 14. Nxc5 Bf5 15. Qxc4 Bxb1 16. Nxb1 Ne4 {0.41/46 (1:43:16)}) 8... a6
9. Ne5 Qxc5 10. Be2 e6 11. cxd5 Nxd5 12. Rc1 Qa7 13. Bg3 Bb4 14. O-O Nxe5 15.
Bxe5 O-O 16. Nc4 b5 17. Nd6 Bxd6 18. Bxd6 Rd8 19. e4 Rxd6 20. exd5 Rxd5 21.
Qa4 {[%eval 0,0][%meval TB:102k]}{ 0.15/53  (6:44:20) *, 2018} *

Please fix this bug. It has become very difficult to analyze my games with this issue.

It is not known how this generally affects the very first move in the analyzed position. Will the SF make the strongest move or ...? I'm not sure anymore.

Sincerely.

**Comment by vondele** [comment] 2018-10-22 20:14
@pb00068 ?

**Comment by DragonMist** [comment] 2018-10-22 20:47
Just for the record, I haven't observed any weird PVs with 14 and 21 Oct versions, SF bmi2 default on F14 GUI. Must check more thoroughly though.

**Comment by RomeoA23** [comment] 2018-10-22 21:02
I can confirm this bug.

[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]
[Analysis "Stockfish 141018 64 POPCNT"]
[AnalysisTime "3185"]
[FEN "r1b1kb1r/pp2pppp/2n2n2/2Pp4/5B2/q3PN2/P1PN1PPP/1R1QKB1R w Kkq - 0 8"]
[SetUp "1"]

8. Bb5 g6 9. c4 Bg7 10. Ne5 Qxc5 11. Qa4 dxc4 12. Bxc4 a6 13. Nb3 Qb6 14. Nxf7
Rf8 15. Ng5 Qb4+ 16. Qxb4 Kd8 {(0:53:05) 47592755kN}{[%eval 32,48,Stockfish
141018 64 POPCNT][%meval 3185s|TB:33k]} *

GUI Aquarium, option **UCI_AnalyseMod**  - true, Contempt=0, PV=1, 14 threads, hash=2048, Syzygy 6 men.

**Comment by DragonMist** [comment] 2018-10-22 21:06
Can you please try it with default contempt?

**Comment by pb00068** [comment] 2018-10-23 05:28
One thing that I can state at first glance, is that it surely don't affects the very first move.
It can happen, and I hope it's merely this, that the reported strange pv's reffer to lowerbound/upperbound outputs by the engine. As I tried to explain in the relevant PR the PV in case of a fail low or fail high can't be interpreted as a primary variation in the classical sense: it's just a path to the point where the fail h/l occured. Anyhow please give me some time to verify, thanks...

**Comment by pb00068** [comment] 2018-10-23 05:38
Adressed to all bug-reporters here: can you please verify how your GUI reports lowerbound/upperbound scores? For instance Arena ist displaying them by placing a +/- prefix to depth. And can you then please report, if the strange pv's belong to this category of output or not, thanks.

**Comment by pb00068** [comment] 2018-10-23 06:46
What I had figured out while testing #1771, is that relative often after resolving the fail/h/l the new obtained pv followed up the previously displayed pv until the before last ply by deviating at the very last ply previously shown. I remember being puzzled about this, but finally I wasn't able to recognize something wrong with it. 
Now it looks like exactly this last move being problematic (= the blunder):
8. c4 a6 9. Ne5 Qxc5 10. Be2 e6 11. cxd5 Nxd5 12. Rc1 Qa7 13. Bg3 Bb4 14. O-O Nxe5 15.
Bxe5 O-O 16. Nc4 b5 17. Nd6 Bxd6 18. Bxd6 Rd8 19. e4 Rxd6 20. exd5 Rxd5 21. Qa4 (Qa4 is a blunder)

8. Bb5 g6 9. c4 Bg7 10. Ne5 Qxc5 11. Qa4 dxc4 12. Bxc4 a6 13. Nb3 Qb6 14. Nxf7
Rf8 15. Ng5 Qb4+ 16. Qxb4 Kd8 (Kd8 is a blunder)

If it is only this the problem: always the last move shown in a longer pv at a lowerbound/upperbound, then the according fix would be trivial (=simply truncate the last move output at longer pv's in lowerbound/upperbound case). Also the running [test ](https://github.com/pb00068/Stockfish/compare/738a6dfd4c71c3ce11d614076117793b4cdf119e...204b53478b91d5e02a48756e6df1092a79663202) perhaps fixes the issue.

What is puzzling me is the pv:
8. Bb5 g6 9. Ne5 Qxc5 10. c4 Bg7 11. Qa4 O-O 12. Bxc6 bxc6 13. Nd3 dxc4 14. Nxc5 Bf5 15. Qxc4 Bxb1 16. Nxb1 Ne4 
here the blunder apparently happens already at move 13

**Comment by pb00068** [comment] 2018-10-23 09:48
Hi @Coolchessguykevin,
while I'm consistently able to reproduce lowerbound/upperbound pv's with blunder moves at the end,
(for instance:
```
depth 25 seldepth 39 multipv 1 score cp 75 lowerbound nodes 18716842 nps 1232668 hashfull 291 tbhits 0 time 15184 pv f1b5 e7e6 f3e5 a3c5 c2c4 f6d7 e5d7 c8d7 e1g1 a7a6 b5a4 b7b5 c4b5 c5b5

depth 27 seldepth 39 multipv 1 score cp 58 upperbound nodes 35230361 nps 1588097 hashfull 495 tbhits 0 time 22184 pv f1b5 e7e6 f3e5 a3c5 c2c4 f8e7 c4d5 e6d5 e1g1 e8g8 b5c6 b7c6 b1c1 c5b6 c1c6 b6d8 d1b1 f6h5 f1c1 h5f4 e3f4 f7f6 e5c4
```
)
I'm absolutely not able to reproduce any  lowerbound/upperbound pv with a queen-loosing move in the middle of the pv like your one in move 13. I use this [branch ](https://github.com/pb00068/Stockfish/tree/analyze_Issue1785) to detect such pv's (engine will abort as soon the situation get encountered).

**Comment by Coolchessguykevin** [comment] 2018-10-23 10:41
Dear pb00068,

i have restarted my analisys again in this position and reproduced this bug again.

Here is full COPY\PASTE PVs from Stockfish. I marked as BOLD the line with queen loss :

 [+0.29]  d=38  8.Bb5 g6 9.Ne5 Qxc5 10.c4 Bg7 11.Qa4 dxc4 12.Bxc4 a6 13.Nb3 Qb6 14.Nxf7 Ne4 15.Nd2 Nc3 16.Rxb6 Nxa4 17.Rxc6 bxc6 18.Nxh8 Bxh8 19.Ne4 Bf5 20.Ng5 Nc3 21.O–O Rd8 22.Nf7 Bd3 23.Bxd3 Kxf7 24.Bxa6 Rd2 25.Bc4 e6 26.a3 Bg7 27.Rc1 Ne2 28.Bxe2 Rxe2 29.Rb1 Ra2 30.Rb7 Kf6 31.h4(0:06:19) 3402351kN
 [+0.41]  d=37  8.Bb5 g6 9.Ne5 Qxc5 10.c4 Bg7 11.Qa4 dxc4 12.Bxc4 a6 13.Nb3 Qb6 14.Nxf7 Ne4 15.Nd2 Nc3 16.Rxb6 Nxa4 17.Rxc6 bxc6 18.Nxh8 Bxh8 19.Ne4 Bf5 20.Ng5 Nc3 21.O–O Rd8 22.Nf7 Bd3 23.Bxd3 Kxf7 24.Bxa6 Rd2 25.Bc4 e6 26.a3 Bg7 27.Rc1 Ne2 28.Bxe2 Rxe2 29.Rb1 Ra2 30.Rb7 Kf6 31.h4 Rxa3(0:05:44) 3090747kN
 [+0.50]  d=37  8.Bb5 g6 9.Ne5 Qxc5 10.c4 Bg7 11.Qa4 dxc4 12.Bxc4 a6 13.Nb3 Qb4 14.Qxb4 Nxb4 15.Bxf7 Kf8 16.Nc5 Nh5 17.Rxb4 Nxf4 18.exf4 Bxe5 19.fxe5 Kxf7 20.e6 Bxe6 21.Rf4 Bf5 22.g4 Rhc8 23.Nb3 e5 24.Rf3 a5 25.Kd1 e4 26.Rf4 b6(0:05:13) 2804173kN
 **_[+0.37]  d=37  8.Bb5 g6 9.Ne5 Qxc5 10.c4 Bg7 11.Qa4 O–O 12.Bxc6 bxc6 13.Nd3 dxc4 14.Nxc5 Bf5 15.Nxc4 Bxb1 16.Qxc6 Bxa2 17.Ne5 Nd5 18.Qd7 Rfc8(0:05:04) 2726476kN_**
 [+0.28]  d=37  8.Bb5 g6 9.Ne5 Qxc5 10.c4 Bg7 11.Qa4 dxc4 12.Bxc4 a6 13.Nb3 Qb4 14.Qxb4 Nxb4 15.Bxf7 Kf8 16.Nc5 Nh5 17.Rxb4 Nxf4 18.exf4 Bxe5 19.fxe5 Kxf7 20.e6 Bxe6 21.Rf4 Bf5 22.g4 Rhc8 23.Nb3 e5 24.Rf3 a5 25.O–O e4 26.Rf4 a4 27.Na1 Rc4(0:04:58) 2672285kN
 [+0.19]  d=36  8.Bb5 g6 9.c4 Bg7 10.cxd5 Nxd5 11.Be5 O–O 12.Rb3 Qa5 13.Bxg7 Kxg7 14.Qa1 Nf6 15.O–O Rd8 16.Nc4 Qc7 17.Bxc6 bxc6 18.Qe5 Qxe5 19.Ncxe5 Be6 20.Ra3 Rd5 21.Rc1 a5 22.h3 Nd7 23.Nxc6 Rxc5 24.Rxc5 Nxc5 25.Nxe7 Kf6 26.Nc6 Bd5 27.Rc3 Ne6 28.Nfe5 Bxc6 29.Nxc6(0:04:34) 2459067kN
 [+0.34]  d=36  8.Bb5 g6 9.Ne5 Qxc5 10.c4 Bg7 11.Qa4 dxc4 12.Bxc4 a6 13.Nb3 Qb4 14.Qxb4 Nxb4 15.Bxf7 Kf8 16.Nc5 Nh5 17.Rxb4 Nxf4 18.exf4 Bxe5 19.fxe5 Kxf7 20.e6 Bxe6 21.Rf4 Bf5 22.g4 Rhc8 23.Nb3 Rc2(0:04:19) 2316830kN
 [+0.26]  d=36  8.Bb5 g6 9.O–O Bg7 10.h3(0:04:00) 2147126kN
 [+0.34]  d=35  8.Bb5 g6 9.O–O Bg7 10.Nd4 a6 11.Bxc6 bxc6 12.Be5 Qxc5 13.c4 Bd7 14.Qc1 Nh5 15.N4b3 Qa7 16.Bxg7 Nxg7 17.Na5 Rb8 18.Qa3 Ne6 19.Rxb8 Qxb8 20.Rb1 Qd8 21.c5 h5 22.Rb6 Qc7 23.h3 g5 24.Rb7 Qc8 25.Qb4 O–O 26.Nf3 f6 27.Nd4 Nxd4 28.exd4(0:03:52) 2076478kN
 [+0.45]  d=35  8.Bb5 g6 9.O–O Bg7 10.Nd4 a6 11.Bxc6 bxc6 12.Be5 O–O 13.Rb6 Qxc5 14.Rxc6 Qa5 15.N2b3 Qa3 16.Qa1 Bd7 17.Rc3 Rac8 18.Nc5 Qa5 19.Ndb3 Qd8 20.Rd1 a5 21.a4 Bf5 22.Nd4 Bd7 23.Qb2 Nh5(0:03:33) 1909528kN
 [+0.27]  d=35  8.Bb5 g6 9.O–O Bg7 10.Nd4 a6 11.Bxc6 bxc6 12.Be5 O–O 13.Rb6 Qxc5 14.Rxc6 Qa5 15.N2b3 Qa3 16.Qa1 Bd7 17.Rc3 Rac8 18.Nc5 Qa5 19.Ndb3 Qd8 20.Rd1 a5 21.a4 Bf5 22.Nd4 Qd7(0:03:26) 1846974kN
 [+0.18]  d=35  8.Bb5 g6 9.Ne5 Qxc5 10.c4 Bg7 11.Qa4 dxc4 12.Bxc4 a6 13.Bxf7 Kf8 14.Nxc6 Bd7 15.Qb3 Bxc6 16.O–O Nd5 17.Rbc1 Qb5 18.Bxd5 Qxd5 19.Qxd5 Bxd5 20.Nc4 Bxc4 21.Rxc4 b5 22.Rc7 Kf7 23.Rfc1 Bb2 24.R1c6 Rhd8 25.h3 Rd1 26.Kh2 Rd2 27.e4 Rd4 28.f3(0:03:15) 1754237kN
 [+0.27]  d=35  8.Bb5 g6 9.c4 Bg7 10.Ne5 Qxc5 11.Qa4 dxc4 12.Bxc4 a6 13.Bxf7 Kf8 14.Nxc6 Bd7 15.Qb3 Bxc6 16.O–O Nd5 17.Rbc1 Qb5 18.Be6 Nxf4 19.exf4 Qxb3 20.Nxb3 a5 21.Rfd1 Bf6 22.g4 Bb2 23.Rb1 Ba3 24.Nd4 Kg7 25.Nxc6 bxc6 26.Rd3 Bd6 27.f5 Rhd8 28.Kg2 gxf5 29.Rbd1(0:02:26) 1312410kN
 [+0.35]  d=34  8.Bb5 g6 9.Ne5 Qxc5 10.c4 Bg7 11.Qa4 dxc4 12.Bxc4 a6 13.Bxf7 Kf8 14.Nxc6 Bd7 15.Qb3 Bxc6 16.O–O Nd5 17.Rbc1 Qb5 18.Be6 Nxf4 19.exf4 Qxb3 20.Nxb3 Bb2 21.Rb1 Bc3 22.Rfd1 a5 23.g3 Kg7 24.Bd5 Rhb8 25.Bxc6 bxc6 26.Rbc1(0:02:07) 1134609kN
 [+0.33]  d=33  8.Bb5 g6 9.Ne5 Qxc5 10.c4 Bg7 11.Qa4 dxc4 12.Bxc4 a6 13.Bxf7 Kf8 14.Nxc6 Bd7 15.Qb3 Bxc6 16.O–O Nd5 17.Rbc1 Qb5 18.Be6 Qxb3 19.Nxb3 Nxf4 20.exf4 a5 21.Rfd1 Bf6 22.g4 Kg7 23.Bd7 Bb2 24.Rb1 Rhd8 25.Bxc6 Rxd1 26.Rxd1 bxc6 27.Rd7 Kf7 28.Kg2 h5 29.g5 Bc3 30.Nc5(0:01:55) 1028831kN
 [+0.34]  d=32  8.Bb5 g6 9.Ne5 Qxc5 10.c4 Bg7 11.Qa4 dxc4 12.Bxc4 a6 13.Bxf7 Kf8 14.Nxc6 Bd7 15.Qb3 Bxc6 16.O–O Nd5 17.Rbc1 Qb5 18.Be6 Qxb3 19.Nxb3 Nxf4 20.exf4 a5 21.Rfd1 Bf6 22.Nc5 Kg7 23.Bh3 Kf7 24.g3 Rhd8 25.Bd7 a4 26.Bxc6 Rxd1 27.Rxd1 bxc6 28.Nd7 Ra7 29.Kg2 Ke6 30.Nb6(0:01:37) 862376kN
 [+0.40]  d=32  8.Bb5 e6 9.c4 Be7 10.cxd5 Nxd5 11.Bd6 Bxd6 12.Rb3 Qxc5 13.Ne4 Qb4 14.Rxb4 Bxb4 15.Ned2 O–O 16.Qb3 Bd7 17.Bd3 Rfd8 18.O–O Rac8 19.a3 Be7 20.Qxb7(0:01:28) 783427kN
 [+0.53]  d=32  8.Bb5 e6 9.c4 Be7 10.cxd5 exd5 11.Nd4 O–O 12.O–O Qxc5 13.Rc1 Qb6 14.Bxc6 bxc6 15.Rxc6 Qb2 16.Rc7 Re8 17.Qc1 Qxc1 18.Rfxc1 Bb4 19.N2b3 Ba6 20.a3 Be7 21.R1c6 Bc4 22.Nd2 Bxa3 23.Nxc4 dxc4 24.Nb5 Bb4 25.Rxc4 Nd5 26.R7c6 Nxf4 27.Rxb4 Ne6 28.Rc1(0:01:25) 757849kN
 [+0.71]  d=32  8.Bb5 g6 9.Ne5 a6 10.Bxc6 bxc6 11.O–O Bg7 12.c4 O–O 13.Qc1 Qa4 14.Rb3 Nh5 15.Ra3 Qb4 16.cxd5 cxd5 17.Nb3 Bf5 18.Nc6 Qb7 19.Nbd4 Rfe8 20.Be5 Rac8 21.Rb3 Qd7 22.Bxg7 Nxg7 23.Na5 Qa4 24.Ra3 Qb4 25.Ndc6 Qh4 26.Rd1 Ne6 27.Rxd5 Be4(0:01:17) 688322kN
 [+0.62]  d=31  8.Bb5 g6 9.c4 Bg7 10.Ne5 a6 11.Bxc6 bxc6 12.O–O O–O 13.Qc1 Qa4 14.Rb3 Nh5 15.Ra3 Qb4 16.cxd5 cxd5 17.Nb3 Bf5 18.Nc6 Qb7 19.Nbd4 Rfe8 20.Be5 Rac8 21.Rb3 Qd7 22.Bxg7 Nxg7 23.Na5 Qa4 24.Ra3 Qb4 25.Ndc6 Qb5(0:01:06) 586167kN

**Comment by Coolchessguykevin** [comment] 2018-10-23 10:43
Please see the attached screensot with the bug PV line. 

![sf pv bug](https://user-images.githubusercontent.com/44373850/47355221-8540dc80-d70c-11e8-9221-b8c84f7040e3.jpg)

**Comment by pb00068** [comment] 2018-10-23 11:03
Can you please report the RAW output given by Stockfish (I think most GUI nowadays have the option to display this), thanks.

**Comment by DragonMist** [comment] 2018-10-23 11:04
From Kevin's output here, it looks as the bug appeared in fail high line.

**Comment by vondele** [comment] 2018-10-23 11:09
It will definitely be related to this change. I had some concerns at PR time, but didn't write it down (the nodes are really not PV nodes anymore, i.e. their eval is outside [a,b]. I don't know if this can be fixed, might need a revert. Anyway, good thing is that this doesn't affect play.

**Comment by pb00068** [comment] 2018-10-23 12:18
Bug is confirmed now, since I reproduced following silly pv from above position:
8. Bb5 Qxc5 9. O-O a6 10. Bxc6+ Qxc6 11. c4 dxc4 12. Ne5 Qe6 13. Ndxc4 b5
14. Qf3 Nd5 15. Rfd1 Bb7 16. Na5 Nxf4 17. Qxb7 Qxe5 18. Qxa8+ Qb8 
(will be followed by 19. Qxb8#)
I will open PR for reverting  #1771, sorry for my fault.

**Comment by DragonMist** [comment] 2018-10-23 12:52
But please continue to get down to the bottom of this, it is very useful feature to have insight into fail high/low pv.

**Comment by joergoster** [comment] 2018-10-25 22:05
Maybe the following will help someone to fully understand what is going on here.
If I insert this code
```
      if (!rootNode && PvNode && moveCount == 1)
          ss->pv[0] = move;
```
just before step 15 of our main search function, I don't get truncated PVs.

One example, with **master**:
info depth 23 seldepth 33 multipv 1 score cp 56 lowerbound nodes 14758399 nps 1160525 hashfull 999 tbhits 0 time 12717 pv d2d4
info depth 23 currmove d2d4 currmovenumber 1
info depth 23 seldepth 33 multipv 1 score cp 69 lowerbound nodes 16243331 nps 1159327 hashfull 999 tbhits 0 time 14011 pv d2d4

**patch**:
info depth 23 seldepth 33 multipv 1 score cp 56 lowerbound nodes 14758399 nps 1155346 hashfull 999 tbhits 0 time 12774 pv d2d4 d7d5 d2d4 d7d5 e4e5 c7c5 c2c3 b8c6 g1f3 g8e7 f1d3 c5d4 c3d4 e7f5 d3f5 e6f5 b1c3 f8e7 a2a3 c8e6 e1g1 e8g8 h2h3 a7a6 f1e1 a8c8 c1f4 h7h6
info depth 23 currmove d2d4 currmovenumber 1
info depth 23 seldepth 33 multipv 1 score cp 69 lowerbound nodes 16243331 nps 1154055 hashfull 999 tbhits 0 time 14075 pv d2d4 d7d5 d2d4 d7d5 e4e5 c7c5 c2c3 b8c6 g1f3 g8e7 f1d3 c5d4 c3d4 e7f5 d3f5 e6f5 b1c3 f8e7 a2a3 c8e6 e1g1 e8g8 h2h3 a7a6 f1e1 a8c8 c1f4 h7h6

The basic idea is that the first move we search at a node is also our initial PV move at this node. Later this will eventually be replaced by a new PV from below that node. This seems to imply there is no valid PV move saved at every ply when failing-high/-low at the root, or the backing up of the pv is somewhere interrupted.

Note: I don't claim this is the correct 'fix' for the possible bug. Is there even a bug? Also, I didn't check for correctness, but the PVs of the bench positions looked ok.
Like I initially said, maybe this helps to shed some light on the issue and finding the root cause and a proper fix.

**Comment by joergoster** [comment] 2018-10-25 22:43
Just noticed 'd2d4 d7d5' appearing twice in above PV. OMG!
Too late here, need some sleep ...

**Comment by DragonMist** [comment] 2018-10-25 22:45
Also 5th ply is illegal :D

**Comment by vondele** [comment] 2018-10-26 05:04
I guess we can close this issue, as it is fixed in master.

**Closed** 2018-10-26 05:42 UTC

**Comment by joergoster** [comment] 2018-10-27 19:45
Interested people able to do their own compiles, may want to grab the sources from https://github.com/joergoster/Stockfish/commit/b9c2496ae86e885447a66c9a95cfb1d1ec410759 which seems to be a working fix. I have NOT verified the legality of the PVs right now, so use it at your own risk. ;-)
Some feedback would be more than welcome!

**Comment by joergoster** [comment] 2018-10-27 20:09
@vondele Thank you! Very helpful indeed, Joost.
