### ISSUE TITLE
Several crashes Stockfish 11

### ISSUE THREAD

**Issue by GiordanoVicoli** [official-stockfish/Stockfish#3105] opened 2020-09-04 06:07 UTC
Hi,

I have included Stockfish 11 (not Stockfish nnue) in my iOS application but I noticed that it crashes very often at the following line: 

TTEntry* TranspositionTable::probe(const Key key, bool& found) const {

  TTEntry* const tte = first_entry(key);
  const uint16_t key16 = key >> 48;  // Use the high 16 bits as key inside the cluster

  for (int i = 0; i < ClusterSize; ++i)
      if (!tte[i].key16 || tte[i].key16 == key16).        <<<<<<<<<<<<<<<<<<<<
      {
          tte[i].genBound8 = uint8_t(generation8 | (tte[i].genBound8 & 0x7)); // Refresh

          return found = (bool)tte[i].key16, &tte[i];
      }

  // Find an entry to be replaced according to the replacement strategy
  TTEntry* replace = tte;
  for (int i = 1; i < ClusterSize; ++i)
      // Due to our packed storage format for generation and its cyclic
      // nature we add 263 (256 is the modulus plus 7 to keep the unrelated
      // lowest three bits from affecting the result) to calculate the entry
      // age correctly even after generation8 overflows into the next cycle.
      if (  replace->depth8 - ((263 + generation8 - replace->genBound8) & 0xF8)
          >   tte[i].depth8 - ((263 + generation8 -   tte[i].genBound8) & 0xF8))
          replace = &tte[i];

  return found = false, replace;
}

Anyone is able to give me some explanation?
Thanks very much and regards,
Giordano

**Comment by ttruscott** [comment] 2020-09-04 17:59
No explanation, but am reminded that the "263" (0x100+7) might as well be "7" since it is only used with add/subtract and then and-ed with 0xF8 and so the 0x100 has no effect on the calculation.

**Comment by ddugovic** [comment] 2020-09-04 20:08
Just to clarify... do you mean SF 11, or SF 12?

**Comment by syzygy1** [comment] 2020-09-05 12:04
@ddugovic As it turns out, this code has changed a bit since SF 11, so this is definitely about SF 11 and not SF 12.

**Comment by syzygy1** [comment] 2020-09-05 12:10
I don't understand how this could crash, but if there is a problem it would seem to be that first_entry() returns an invalid address.

In SF11, first_entry() looks like this:
https://github.com/official-stockfish/Stockfish/blob/c3483fa9a7d7c0ffa9fcc32b467ca844cfb63790/src/tt.h#L87-L90
Looks fine to me. It returns &table[idx] with idx being in the correct range 0 <= idx < clusterCount.

Question for @GiordanoVicoli : what size of TT table are you using?

**Comment by GiordanoVicoli** [comment] 2020-09-05 15:32
I mean SF 11 but also previous releases.
Until some time ago the problems with iOS was the thread management. The problem was fixed after introducing the file thread_win32_osx.h. But now I still have several crashes due the problem I mentioned. My application is similar to SmallFish.
Perhaps there is some problem in interfacing iOS app with Stockfish code? Is there some guideline or some example code to interface Stockfish in a iOS application?

Many thanks to all,
Giordano

**Comment by syzygy1** [comment] 2020-09-05 16:04
@GiordanoVicoli 
If you want to help debug, can you answer the question I asked?

Are you able to see whether tte indeed points to an invalid address when there is a crash? Could you give us the values of "key" and "clusterCount" that cause it?
I have no idea what kind of debugging facilities exist on iOS.

**Comment by GiordanoVicoli** [comment] 2020-09-07 05:56
thank you very much for the help but I am not able to reproduce the crash. As far as I understood it is not a regular crash.

**Comment by vondele** [comment] 2020-09-12 08:36
as the crash can't be reproduced and this refers to and old stockfish, and is probably due to using a non-standard build system, I'll close this issue.

**Closed by vondele** 2020-09-12 08:36 UTC
