### ISSUE TITLE
Old make segfault

### ISSUE THREAD

**Issue by JavaMast** [official-stockfish/Stockfish#2984] opened 2020-08-11 18:27 UTC
Now 2 builds is missed:
**Tweak castling extension**
and
**This commit enables a mixed bench, to improve CI and allow for PGO (profile-build) of the NNUE part of the code.**

============
I notice that impossible to build Stockfish with jobs >1

![Screenshot_851](https://user-images.githubusercontent.com/42765009/89934422-346be200-dc19-11ea-9f78-a402c511ac10.png)

With -j 1 engine is being built successfully

**Comment by gvreuls** [comment] 2020-08-11 19:01
What compiler version do you use, and what make command do you use to build the executable?

**Comment by JavaMast** [comment] 2020-08-11 19:09
@gvreuls 
MinGW 9.3.0 and 10.1.0
 
with:
**make profile-build ARCH=x86-64-avx2    COMP=mingw
make profile-build ARCH=x86-64-avx2  or -j 1  COMP=mingw**
the engine is being built successfully

but with: 
**make profile-build ARCH=x86-64-avx2   -j 8   COMP=mingw**  (or even -j 2)
the engine is not built

**Comment by gvreuls** [comment] 2020-08-11 19:27
@JavaMast Is this a Linux cross compile or are you on Windows? I can't reproduce this on Windows with MinGW 10.2.0

**Comment by vondele** [comment] 2020-08-11 19:33
abrok is on linux.

**Comment by JavaMast** [comment] 2020-08-11 19:34
@gvreuls 
Windows

Possibly this is a reason why 2 latest commits still missed on abrok

**Comment by JavaMast** [comment] 2020-08-11 19:35
@vondele 
what number of jobs is used for this builds?

**Comment by vondele** [comment] 2020-08-11 19:36
I don't know, I just read that on the download page.

**Comment by Viceroy-Sam** [comment] 2020-08-11 19:39
**Three** builds are missing from https://abrok.eu/stockfish/

Tweak castling extension, https://github.com/official-stockfish/Stockfish/commit/ee060464129f8d3af184efa013177a4ef387a394
Add comments to probCut code, https://github.com/official-stockfish/Stockfish/commit/a72cec1ff854a77a92452c2afe2001e05f06e6d4
and
This commit enables a mixed bench, to improve CI and allow for PGO (profile-build) of the NNUE part of the code. https://github.com/official-stockfish/Stockfish/commit/ea6220f3813e5b76b444a02905eaf2c556bdb368

**Comment by gvreuls** [comment] 2020-08-11 19:39
@vondele LTO isn't enabled on MinGW Windows so this most likely isn't a LTO problem, unless @JavaMast sneaks in a ``CXXFLAGS=-flto`` that is.

**Comment by JavaMast** [comment] 2020-08-11 19:41
@gvreuls 
I did not make any changes in makefile and source code

**Comment by gvreuls** [comment] 2020-08-11 19:47
@JavaMast What I meant is that perhaps you do something like
``CXXFLAGS=-flto make profile-build ARCH=x86-64-avx2 -j 8 COMP=mingw ``

Looking at your screenshot again this looks like make itself crashed here, so I'm really clutching at straws about how this happens, make crashes don't occur frequently.

**Comment by JavaMast** [comment] 2020-08-11 19:48
Actually, if make some changes in makefile (delete line 599-604)

_net:
	$(eval nnuenet := $(shell grep EvalFile ucioption.cpp | grep Option | sed 's/.*\(nn-[a-z0-9]\{12\}.nnue\).*/\1/'))
	@echo "Default net: $(nnuenet)"
	$(eval nnuedownloadurl := https://tests.stockfishchess.org/api/nn/$(nnuenet))
	$(eval curl_or_wget := $(shell if hash curl 2>/dev/null; then echo "curl -sL"; elif hash wget 2>/dev/null; then echo "wget -qO-"; fi))
	@if test -f "$(nnuenet)"; then echo "Already available."; else echo "Downloading $(nnuedownloadurl)"; $(curl_or_wget) $(nnuedownloadurl) > $(nnuenet); fi_

engine will builds successfully with jobs >1

**Comment by JavaMast** [comment] 2020-08-11 19:56
@gvreuls 
i use

_make clean
make profile-build ARCH=x86-64-avx2  -j 5   COMP=mingw
strip Stockfish.exe
move Stockfish.exe Stockfish_x64_%datestamp%_AVX2_mingw_10.exe

make clean
pause_

and i have no problems to build SF untill https://github.com/official-stockfish/Stockfish/commit/ea6220f3813e5b76b444a02905eaf2c556bdb368

**Comment by gvreuls** [comment] 2020-08-11 20:07
@vondele The only thing ea6220f changes in the Makefile is adding the ``net`` target to ``profile-build`` target, so somehow the ``net`` target crashes ``make`` in older MinGW versions on Windows when using parallel builds (``-j``). I'm out of my wits here, the ``net`` target is straight from @nodchip according to blame.

**Comment by vondele** [comment] 2020-08-11 20:12
I wrote the `net` target... we rely on this now, and don't have windows to test. So is this an old version of make @JavaMast (`make --version`)

**Comment by gvreuls** [comment] 2020-08-11 20:30
@JavaMast As a workaround you could build the ``net`` target with one job before building the executable, so:
```
make clean
make net
make profile-build ARCH=x86-64-avx2 -j 5 COMP=mingw
strip Stockfish.exe
move Stockfish.exe Stockfish_x64_%datestamp%_AVX2_mingw_10.exe

make clean
pause
```
Can you confirm if this works?

**Comment by JavaMast** [comment] 2020-08-11 20:33
@gvreuls 
does not work

![Screenshot_859](https://user-images.githubusercontent.com/42765009/89946086-0e4f3d80-dc2b-11ea-8e72-5b39f848d4f9.png)

**Comment by vondele** [comment] 2020-08-11 20:40
while I can use the assumed setup of abrok (ubuntu 18.0.4 / gcc 7.3) to do a windows cross compile with pgo/lto
```
make -j ARCH=x86-64-avx2 COMP=mingw profile-build PGOBENCH="wine ./stockfish.exe bench"
```

**Comment by JavaMast** [comment] 2020-08-11 20:41
@vondele 
try with -j 2

**Comment by vondele** [comment] 2020-08-11 20:43
`-j 2` works as well

@JavaMast is it an option to use the new windows installer for fishtest to upgrade the installation of msys2? 
https://groups.google.com/g/fishcooking/c/2rUlDQZINNw/m/PTZJ4lnKBAAJ

**Comment by JavaMast** [comment] 2020-08-11 20:55
With this changes it works fine:

-profile-build: config-sanity objclean profileclean **net**
+profile-build: config-sanity objclean profileclean

-clean: objclean profileclean
+clean: objclean profileclean **net**


![Screenshot_862](https://user-images.githubusercontent.com/42765009/89947857-c7167c00-dc2d-11ea-8918-6f07dba28e19.png)

![Screenshot_863](https://user-images.githubusercontent.com/42765009/89947868-cc73c680-dc2d-11ea-917f-a51148f9514d.png)

**Comment by JavaMast** [comment] 2020-08-11 20:59
Also works fine with
profile-build: **net** config-sanity objclean profileclean

**Comment by vondele** [comment] 2020-08-11 21:02
that's bizarre, but well. Can you test if this still works if you remove by hand `nn-*.nnue` before the build (thus force the download).

**Comment by vondele** [comment] 2020-08-11 21:03
can you also report the output of `make --version` so we know what it is.

**Comment by JavaMast** [comment] 2020-08-11 21:06
@vondele 
already triyed - it works

![Screenshot_860](https://user-images.githubusercontent.com/42765009/89948880-8f103880-dc2f-11ea-941f-68d27218ea77.png)


==============
![Screenshot_864](https://user-images.githubusercontent.com/42765009/89948894-97687380-dc2f-11ea-969a-45cee44e0423.png)

**Comment by vondele** [comment] 2020-08-11 21:08
![image](https://user-images.githubusercontent.com/4202567/89949062-8f0c3a80-dc27-11ea-9d42-a92bd4a25a16.png)

2006 .... and still going strong (almost).

**Comment by vondele** [comment] 2020-08-11 21:09
So, I'll make a patch with the workaround, but it really is that.... some bug must have been fixed in the last 14 years.

**Comment by mstembera** [comment] 2020-08-12 01:15
Just FYI.  My old make version was 3.81 and I had the same exact issue as posted above by @JavaMast.  After upgrading to the latest version 4.3 provided by msys2 it's resolved.

**Comment by ssj100** [comment] 2020-08-12 05:23
Hi, will this solve the abrok issue?

**Comment by vondele** [comment] 2020-08-12 05:26
As we don't know what the exact problem is at abrok, we can't tell. However, I expect the owner of abrok to fix this, but probably when he has time.

**Closed** 2020-08-12 05:50 UTC

**Comment by ssj100** [comment] 2020-08-12 18:28
abrok back up.
