### ISSUE TITLE
Older patch verification

### ISSUE THREAD

**Issue by mstembera** [official-stockfish/Stockfish#2538] opened 2020-02-01 01:42 UTC
Since loose test bounds have been identified as the root cause of the recent regression 
https://github.com/official-stockfish/Stockfish/issues/2531
and 5 of 7 retested patches since SF11 had to be reverted it's quite probable that other patches(committed before SF11 release but after the loose bounds were introduced) also cause regressions.  Even if other regression tests didn't show anything as significant as the most recent one individual patches could easily have gone unnoticed since several patches are bundled in a single regression test. Some regression tests which were expected to be positive due to including several elo gainers were in fact negative albeit within error bounds.  It may make sense to systematically verify these older patches as we did the recent ones since SF11.  While this seems like bad news it's actually a golden opportunity to gain some "easy" elo while removing code.  How far back was the first commit based on the bad/loose bounds?

**Comment by Rocky640** [comment] 2020-02-01 01:48
January 7, 2020, I mentioned this in previous thread.

**Comment by mstembera** [comment] 2020-02-01 02:37
@Rocky640 Ah ok thanks!  I just saw the original issue was closed and no patches before SF11 were reverted.
Should I close this?

**Comment by vondele** [comment] 2020-02-01 07:50
@Rocky640 @mstembera  there have been three changes to the testing procedure in recent times
* Change of STC bounds https://github.com/glinscott/fishtest/commit/d7b5129de4ebab4179580e7cecd814feaa14f799
* Change to pentanomial https://github.com/glinscott/fishtest/commit/61d6890ad306ac9a483eb2cd5ebf42def14a68f6
* Change to logistic https://github.com/glinscott/fishtest/commit/948adb1fa657aa4de89e3e74d54e52bc681d7930

The first 2 made it easier to pass, while I was assuming that the last one was no real change, but rounding could influence that. I think that it made sense to have some tests as far back as  Oct 23, 2019

**Comment by snicolet** [comment] 2020-02-01 09:45
True, and I see the book as part of the testing process too, so in fact we have changed four things:

* Oct, 23 : Change of STC bounds https://github.com/glinscott/fishtest/commit/d7b5129de4ebab4179580e7cecd814feaa14f799
* Dec, 18: Change to pentanomial https://github.com/glinscott/fishtest/commit/61d6890ad306ac9a483eb2cd5ebf42def14a68f6
* Jan, 3 : Change of testing book https://github.com/glinscott/fishtest/commit/dc948b77ec89d794ff7a97a4d11880de69d1e2de
* Dec, 28 : Change to logistic bounds https://github.com/glinscott/fishtest/commit/948adb1fa657aa4de89e3e74d54e52bc681d7930

Concerning the change to logistic bounds and rounding, the conversion formula depends on the draw rate so the results are not the same at STC and LTC. Consider for instance these two tests and click at the "raw statistics" link at the bottom:

http://tests.stockfishchess.org/tests/view/5e34b56fe70d848499f637bb
http://tests.stockfishchess.org/tests/view/5e2f767bab2d69d58394fd04

* The first one (ultra fast TC) gives a conversion of LogisticElo bounds {0, 2} to BayesElo bounds [0, 2.7]
* The second one (the LTC +7 Elo patch) gives a conversion of LogisticElo bounds {0, 2} to BayesElo bounds [0, 4.47], very far from the [0, 3.5] we had before.

**Comment by snicolet** [comment] 2020-02-01 10:43
Also, the LogisticElo STC and LTC bounds for simplifications give different BayesElo bounds, with the LTC bounds looser than the old [-3, 1] bounds:

STC :  {-1.5, 0.5} corresponds to [-2.4 , 0.8]
LTC :  {-1.5, 0.5} corresponds to [-3.4, 1.15]

Sources:
http://tests.stockfishchess.org/tests/view/5e34812630ae32da08941d65
http://tests.stockfishchess.org/tests/view/5e354daee70d848499f6380c

**Comment by vondele** [comment] 2020-02-01 10:59
Right, book plays a role as well. I recall Elo measurements for the old and new book gave similar results, for SF10->SF11.

**Comment by vondele** [comment] 2020-02-01 11:27
but, concerning the book, probably the most important chance is its size. I seem to see that 2moves_v2.pgn contains 'just 12092' positions, while the new is 150932. In the old tests, the same position must have been played 10s of times, while now it is more rare. This must have influenced the derived statistics.... not sure in which way. @vdbergh ?

**Comment by snicolet** [comment] 2020-02-01 11:41
Intuitively, in case of repeated games in a SPRT test, I think that we have the following effects:

* if the repeated game results in a double draw or a 1-1 result, then the estimated Elo of the test will tend to zero: this will make Elo-gaining tests harder to pass, and help simplifications and non-regression tests to pass.

* if the repeated game results in one win and one draw for the test branch, then the Elo estimate will go up: this will make Elo-gaining tests easier to pass, and help simplifications and non-regression tests to pass.

* if the repeated game results in one win and one draw for the base branch, then the Elo estimate will go down: this will make Elo-gaining, simplifications and non-regression tests more difficult to pass.

**Comment by vondele** [comment] 2020-02-01 12:04
I think the Elo results doesn't really change (since any position has roughly the same chance to be repeated), but the variance is influenced.

**Comment by vdbergh** [comment] 2020-02-01 12:10
@vondele @snicolet I do not really know what the effect is of repeated openings. I never seriously thought about this since I always thought correlations between games are not strong.  Now I think this is wrong but I have not revisited the issue. 

If the result is deterministic then it seems obvious to me that the replay can yield no new information (correct me if I make a mistake here). If there is some correlation then we get some information but less than what we expect. Hence we should have less confidence in our results. @vondele already arrived at a similar conclusion a while ago and I agree with it. However I am confused about how to properly formulate this effect mathematically and how to possibly quantify it (I am rather busy right now, so I can't devote much time to it).

**Comment by vdbergh** [comment] 2020-02-01 12:16
@vondele I am confused about the variance. If we have two "cheat" coins, one with only heads and the other with only tails and we pick them randomly then the result is indistinguishable from using a fair coin. So the variance of the outcome is the same.

**Comment by vondele** [comment] 2020-02-01 12:18
good, that would imply the new book increases the confidence in our result.

Maybe variance is the wrong word... even though I somehow link this with the confidence that you use.

I think the math is an extension of the pentanomial model in some way. For each position there can now be more match results. However, the correlation between games is unknown. I guess that could be measure extended matches with just 1 book position.

**Comment by snicolet** [comment] 2020-02-01 12:26
I may be easier to quantify via simulation: from time to time, instead of throwing a dice to simulate a new game result according to the Elo difference, just pick a previous result at random.

**Comment by vondele** [comment] 2020-02-01 12:34
if we pick a previous result it is assuming 'deterministic' games, which is the 'easy' case. The question which is hard to answer is how similar are (in our testing conditions) the games that start from the same position. We know if is not deterministic if we play with TC, the question is how much correlation remains.

**Comment by snicolet** [comment] 2020-02-01 12:47
> if we pick a previous result it is assuming 'deterministic' games

Or at least deterministic game results :-)

**Comment by Stefano80** [comment] 2020-02-01 15:52
@vdbergh to formulate mathematically, I think the most interesting way would be to have a starting position dependent (pentanomial), let me call it PE (I dont know whether this exists, I think of it as the couple Bayeselo/Drawelo). You could also assume that this PE is engine dependent. You draw a set of random positions and for each position you draw a PE(position, eng1, eng2) from a distribution which is slightly skewed to reflect white advantage. After that you draw a pentanomial result for every single game. This looks like a doubly stochastic process, one could probably write down the analytical expressions for expectation and variance.

If you have infinitely many positions that do not repeat and you keep playing games, your empirically estimated PR will converge to something like <PE(position, eng1, eng2)> where you take the expectation over the positions (or something in that direction).

If you have only finitely many positions, and they do repeat, you will converge to the same value, where you take the average over a distribution with finite support.

So the questions seems to me whether the rate of convergence for the distribution with finite support is significantly smaller than in the other case.

I hope this makes sense, if not, my fault.

**Comment by xoto10** [comment] 2020-02-03 14:30
What about simplifications done under the old [-3,1] bounds - do we trust they are ok?

**Comment by vdbergh** [comment] 2020-02-03 15:18
@xoto10 Despite many attempts, simplifications have never been proved to be causing regressions. It seems the bounds were always good enough.

**Comment by xoto10** [comment] 2020-02-03 15:27
@vdbergh OK. That was my assumption, but I thought I should ask.

**Comment by dorzechowski** [comment] 2020-02-03 23:27
Just small clarification: we have never used 2moves_v2 book in fishtest. Only version 2moves_v1 was used and it contains over 40k positions. 2moves_v2 was an attempt to clean up v1 by removing "unnatural" openings. They have about the same Elo resolution but v2 has smaller bias according to measurements done by @vdbergh some time ago (see #1853).

Repeated openings very often lead to diverse results. It's actually very hard to get whole duplicated games, even on 1 core on the same machine. Of course several opening moves usually tend to be the same so it's effectively like playing with a deeper book.

**Comment by gvreuls** [comment] 2020-02-06 17:06
Could this have something to do with the new cutechess-cli? Ever since we're using the new cutechess-cli we get a warning message for every batch of games:
> Warning: 2 opening repetitions vs 1 games per encounter

If I understand the help text correctly, to play 250 games with each opening repeated twice the parameters for the new cutechess-cli should be `cutechess-cli -rounds 125 -games 2 -repeat ...` (this doesn't generate any warnings) while the workers still use the old version parameters `cutechess-cli -repeat -games 250 ...`. Do these old parameters still do the right thing or do we play each opening only once now as the warning seems to imply?

**Comment by vondele** [comment] 2020-02-06 17:28
@gvreuls that's something that could be posted as a worker update in fishtest. However, downloading a pgn from fishtest, all is fine, it seems. (125 different starting fens, both 2x played).

**Comment by vondele** [comment] 2020-04-03 14:25
I'll close this, I think the situation is essentially resolved, and possible remainders of useless patches will be weeded out with the normal process of simplifications and improvements.

**Closed by vondele** 2020-04-03 14:25 UTC
