### ISSUE TITLE
Support different Net Architecture

### ISSUE THREAD

**Issue by CaptainFuture1405** [official-stockfish/Stockfish#3670] opened 2021-08-22 10:59 UTC
In order to give network developers more opportunities to experiment and to support networks with different architectures, the NnueVersion should not be defined as a fixed value in nnue.c, but should be determined dynamically via the function readu_le_u32(d), see the function verify_net().
The function verify_net() itself will then be obsolete.
Depending on NnueVersion, the network parameters, e.g. kHalfDimensions, can be determined.

The easiest way to do this code extension is when the the code is prepared for a new network architecture.

**Comment by Sopel97** [comment] 2021-08-22 11:16
> Depending on NnueVersion, the network parameters, e.g. kHalfDimensions, can be determined.

No, this is false. The NnueVersion is vague, and because "hashes" are used to identify the parts of the network we can only reliably provide validation. This could be resolved with https://github.com/glinscott/nnue-pytorch/pull/140.

There are, however, a number of implementation issues that are not related to the way the nets are stored:

1. One possible solution would be to make a network container providing a virtual "evaluate" method, but this introduces a virtual function call and will hinder inlining without PGO. This would also only allow using architectures from a predefined subset.
2. The other possibility is to make the layer sizes not constants. This would prevent constant propagation optimisation, and in particular hinders loop unrolling. A lot of dispatch that is now static would be moved to the runtime. 
3. Supporting the nets of different sizes would require more optimized code paths for sizes that are not supported by the current code. A lot of code, and even more dispatch logic.
4. Multiple feature sets would need to be supported. Some have different requirements for the maximum active feature count, and the need to account for that would prevent us from using constant sized features arrays. This would either require using a container with dynamically allocated storage, or an upper bound.
5. It's a lot of code that won't be tested on fishtest

I don't think this is a good direction. People who experiment with different architectures can still do so by modifying the source code.

**Comment by vondele** [comment] 2022-02-20 18:08
our master branch just supports one net version, by design. Users should in general just use the embedded net. Developers can change the code as needed. As architectures evolve it is quite hard to maintain compatibility.

**Closed by vondele** 2022-02-20 18:08 UTC
