### ISSUE TITLE
 No more output after 9 seconds

### ISSUE THREAD

**Issue by Vinvin20** [official-stockfish/Stockfish#581] opened 2016-01-25 08:52 UTC
Last output after 9 sec, then no more output for 6 minutes !?
CPU still at 100% usage

Conditions :
With only 1 best line (couldn't reproduced with 2 best lines).
Syzygy 6 pieces
6 cores-6 threads

Same problem with version "stockfish_16011823_x64_modern.exe"

FEN: 3Q4/7p/p7/8/8/6p1/2k1n1P1/7K w - - 0 12

Stockfish_16012415_x64_modern:
...
 50/76    00:01     44.831k    30.812k    +5,78    12.Qa5 h6 13.Qa2+ Kd3 14.Qxa6+ Kd2 15.Qa5+ Ke3 16.Qb6+ Kd2 17.Qb4+ Kd3 18.Qa3+ Kd2 19.Qa7 Ke1 20.Qa5+ Kf1 21.Qf5+ Ke1 22.Qe6 h5 23.Qf5 h4 24.Qe5 Kf2 25.Qc5+ Kf1 26.Qf8+ Ke1 27.Qh6 Kf1 28.Qg5 Kf2 29.Qe5 Kf1 30.Qa5 Kf2 31.Qb4 Ke3 32.Qc5+ Kd2 33.Qe5 Ke1 34.Qf6 Kd2 35.Qg5+ Ke1 36.Qd5 Kf2 37.Qf7+ Ke1 38.Qg7 Kf2 39.Qa1 Ke3 40.Qa3+ Kf2 41.Qf3+ Ke1 42.Qf5 Kd2 43.Qa5+ Ke3 44.Qb6+ Kd2 45.Qd6+ Ke3 46.Qh6+ Kf2 47.Qe6 Ke1 48.Qd6 Kf1 49.Qf6+ Ke1
 51/76    00:01     54.664k    30.419k    +5,78    12.Qa5 h6 13.Qa2+ Kd3 14.Qxa6+ Kd2 15.Qa5+ Ke3 16.Qb6+ Kd2 17.Qb4+ Kd3 18.Qa3+ Kd2 19.Qa7 Ke1 20.Qa5+ Kf1 21.Qf5+ Ke1 22.Qe6 h5 23.Qf5 h4 24.Qe5 Kf2 25.Qc5+ Kf1 26.Qf8+ Ke1 27.Qh6 Kf1 28.Qg5 Kf2 29.Qe5 Kf1 30.Qa5 Kf2 31.Qb4 Ke3 32.Qc5+ Kd2 33.Qe5 Ke1 34.Qf6 Kd2 35.Qg5+ Ke1 36.Qd5 Kf2 37.Qf7+ Ke3 38.Qb3+ Kf2 39.Qb6+ Ke1 40.Qd6 Kf1 41.Qf6+ Ke1 42.Qf5 Kd2 43.Qa5+ Ke3 44.Qa3+ Kf2 45.Qf3+ Ke1 46.Qe3 Kf1 47.Qe4 Ke1 48.Qg4 Kf2 49.Qe6 Kf1
 52/81    00:02     72.445k    31.663k    +5,78    12.Qa5 h6 13.Qa2+ Kd3 14.Qxa6+ Kd2 15.Qa5+ Ke3 16.Qb6+ Kd2 17.Qb4+ Kd3 18.Qa3+ Kd2 19.Qa7 Ke1 20.Qa5+ Kf1 21.Qf5+ Ke1 22.Qe6 h5 23.Qf5 h4 24.Qe5 Kf2 25.Qc5+ Kf1 26.Qf8+ Ke1 27.Qh6 Kf1 28.Qg5 Kf2 29.Qe5 Kf1 30.Qa5 Kf2 31.Qb4 Ke3 32.Qc5+ Kd2 33.Qe5 Ke1 34.Qf6 Kd2 35.Qg5+ Ke1 36.Qd5 Kf2 37.Qf7+ Ke3 38.Qb3+ Kf2 39.Qb6+ Ke1 40.Qd6 Kf1 41.Qf6+ Ke1 42.Qf5 Kd2 43.Qa5+ Ke3 44.Qa3+ Kf2 45.Qf3+ Ke1 46.Qe3 Kf1 47.Qe4 Ke1 48.Qg4 Kf2 49.Qe6 Kf1 50.Qf7+ Ke1 51.Qg7 Kf2 52.Qa1
 53/84    00:04     159.631k    34.182k    +5,78    12.Qa5 h6 13.Qa2+ Kd3 14.Qxa6+ Kd2 15.Qa5+ Ke3 16.Qb6+ Kd2 17.Qb4+ Kd3 18.Qa3+ Kd2 19.Qa7 Ke1 20.Qa5+ Kf1 21.Qf5+ Ke1 22.Qe6 h5 23.Qf5 h4 24.Qe5 Kf2 25.Qc5+ Kf1 26.Qf8+ Ke1 27.Qh6 Kf1 28.Qg5 Kf2 29.Qe5 Kf1 30.Qa5 Kf2 31.Qb4 Ke3 32.Qc5+ Kd2 33.Qe5 Ke1 34.Qf6 Kd2 35.Qg5+ Ke1 36.Qd5 Kf2 37.Qf7+ Ke3 38.Qb3+ Kf2 39.Qb6+ Ke1 40.Qd6 Kf1 41.Qf6+ Ke1 42.Qf5 Kd2 43.Qa5+ Ke3 44.Qa3+ Kf2 45.Qf3+ Ke1 46.Qe3 Kf1 47.Qe4 Ke1 48.Qd3 Kf2 49.Qa3 Kf1 50.Qa1+ Kf2 51.Qb1 Ke3 52.Qb6+ Kd2
 54/84    00:09     324.986k    35.748k    +5,78    12.Qa5 h6 13.Qa2+ Kd3 14.Qxa6+ Kd2 15.Qa5+ Ke3 16.Qb6+ Kd2 17.Qb4+ Kd3 18.Qa3+ Kd2 19.Qa7 Ke1 20.Qa5+ Kf1 21.Qf5+ Ke1 22.Qe6 h5 23.Qf5 h4 24.Qe5 Kf2 25.Qc5+ Kf1 26.Qf8+ Ke1 27.Qh6 Kf1 28.Qg5 Kf2 29.Qe5 Kf1 30.Qa5 Kf2 31.Qb4 Ke3 32.Qc5+ Kd2 33.Qe5 Ke1 34.Qf6 Kd2 35.Qg5+ Ke1 36.Qd5 Kf2 37.Qf7+ Ke3 38.Qb3+ Kf2 39.Qb6+ Ke1 40.Qd6 Kf1 41.Qf6+ Ke1 42.Qf5 Kd2 43.Qa5+ Ke3 44.Qa3+ Kf2 45.Qf3+ Ke1 46.Qe3 Kf1 47.Qe4 Ke1 48.Qd3 Kf2 49.Qc4 Ke3 50.Qe6+ Kd2 51.Qd6+ Ke1 52.Qb4+ Kf1 53.Qc5
 55/84    00:09     340.052k    35.935k    +5,78    12.Qa5 h6 13.Qa2+ Kd3 14.Qxa6+ Kd2 15.Qa5+ Ke3 16.Qb6+ Kd2 17.Qb4+ Kd3 18.Qa3+ Kd2 19.Qa7 Ke1 20.Qa5+ Kf1 21.Qf5+ Ke1 22.Qe6 h5 23.Qf5 h4 24.Qe5 Kf2 25.Qc5+ Kf1 26.Qf8+ Ke1 27.Qh6 Kf1 28.Qg5 Kf2 29.Qe5 Kf1 30.Qa5 Kf2 31.Qb4 Ke3 32.Qc5+ Kd2 33.Qe5 Ke1 34.Qf6 Kd2 35.Qg5+ Ke1 36.Qd5 Kf2 37.Qf7+ Ke3 38.Qb3+ Kf2 39.Qb6+ Ke1 40.Qd6 Kf1 41.Qf6+ Ke1 42.Qf5 Kd2 43.Qa5+ Ke3 44.Qa3+ Kf2 45.Qf3+ Ke1 46.Qe3 Kf1 47.Qe4 Ke1 48.Qd3 Kf2 49.Qc4 Ke3 50.Qe6+ Kd2 51.Qd6+ Ke1 52.Qe7 Kf1

**Comment by Vinvin20** [comment] 2016-01-25 16:09
May be there's some issues with the position being draw at some depths ? Related with Syzygy ?

**Comment by zamar** [comment] 2016-01-26 00:32
A few questions:

- If you send 'stop' command to stockfish. Does it print a bestmove?
- If you leave Stockfish running for a few hours, does it ever come back alive?

**Comment by nabildanial** [comment] 2016-01-26 00:47
"go infinite" works fine with me, stopped until depth 99. No sygyzy though.
________________________________
info depth 95 seldepth 109 multipv 1 score cp 708 nodes 10462481150 nps 45635876 hashfull 999 tbhits 0 time 229260 pv d8c8 c2d2 c8a6 d2e1 a6h6 e1f2 h6h7 f2e3 h7e7 e3d2 e7h4 d2e3 h4h7 e3f2 h7e7 f2e1 e7h4 e1d2 h4h8 d2e3 h8a8 e3d2 a8b7 d2e3 b7c6 e3f2 c6h6 f2e1 h6h3 e1d2 h3h5 d2e1 h5h6 e1f2 h6b6 f2e1 b6b3 e1d2 b3a4 d2e3 a4a1 e3f2 a1a8 f2e1 a8e4 e1f2 e4e6 f2e1 e6e5 e1d2 e5e8 d2e1 e8d8 e1f2 d8d1 f2e3 d1d7 e3f2 d7b5 f2e1 b5e8 e1f2 e8c6 f2e3 c6b5 e3d2 b5b4 d2e3 b4b7 e3d2 b7b3 d2e1 b3a2 e1f2 a2a1 f2e3 a1f6 e3d2 f6f7 d2e1 f7c7 e1f2 c7d7 f2e3 d7f7 e3d2 f7f6 d2e1 f6d6 e1f2 d6b8 f2e1 b8b2 e1f2 b2e5 f2e1 e5f5 e1d2 f5a5 d2e3 a5h5 e3f2 h5f3 f2e1 f3f8 e1d2
info depth 96 currmove d8c8 currmovenumber 1
stop
info nodes 13480650838 time 302464
bestmove d8c8 ponder c2d2

**Comment by nabildanial** [comment] 2016-01-26 01:05
UPDATE.
Stockfish updates the PV at a slower rate when (6-men) syzygy is in use. It took a VERY long time to go from depth 91 to 92.
__________________________________
info depth 91 seldepth 110 multipv 1 score cp 739 nodes 4384833966 nps 43015980 hashfull 999 tbhits 3578196 time 101935 pv d8c8 c2d3 c8a6 d3e3 a6e6 e3d2 e6h6 d2d1 h6h7 d1e1 h7f5 e1d2 f5e4 d2e1 e4a8 e1f2 a8b8 f2e1 b8c8 e1d2 c8c4 d2e3 c4g4 e3f2 g4c8 f2e3 c8g8 e3d2 g8f8 d2e1 f8c5 e1d2 c5g5 d2e1 g5d8 e1f2 d8a5 f2e3 a5g5 e3f2 g5f6 f2e3 f6b2 e3f2 b2b1 f2e3 b1b8 e3f2 b8d6 f2e1 d6e6 e1d2 e6f7 d2e3 f7d7 e3f2 d7f5 f2e3 f5f7 e3d2 f7b7 d2e1 b7a7 e1d2 a7a1 d2e3 a1d1 e3f2 d1b3 f2e1 b3e3 e1f1 e3e6 f1e1 e6g6 e1f2 g6d3 f2e1 d3b3 e1d2 b3d5 d2e3 d5h5 e3d2 h5g4 d2e1 g4g7 e1d2 g7g6 d2e3 g6e8 e3d2 e8a4 d2e1 a4a2 e1f2 a2b2 f2e1 b2b6 e1d2 b6c7 d2e3 c7a5 e3f2 a5e5 f2e1 e5d5 e1f2
info depth 92 currmove d8c8 currmovenumber 1
stop
info nodes 16765093183 time 422441
bestmove d8c8 ponder c2d3

**Comment by zamar** [comment] 2016-01-28 15:41
@Vinvin20: Please provide additional information about the problem:

- If you send 'stop' command to stockfish. Does it print a bestmove?
- If you leave Stockfish running for a few hours, does it ever come back alive?

If we do not receive this additional key information in reasonable time (let's say within 2 weeks from opening the issue), then we have no choice but to close the issue.

**Comment by joergoster** [comment] 2016-01-29 18:25
@Vinvin20 SF needs some time to resolve the fail-low. This is due to draw by 50-move rule kicking in at that point. And since this happens at a very high search depth, this may take a LOT of time ...

Change the fen to
3Q4/7p/p7/8/8/6p1/2k1n1P1/7K w - - 80 150
and try again.

**Comment by Vinvin20** [comment] 2016-02-03 16:25
I don't use SF in command lien but about only in Arena interface.
I don't know how to set the Syzygy parameters in a command line :-/

**Comment by zamar** [comment] 2016-02-08 00:34
This is likely not a bug. Resolving fail-highs and fail-lows at really high depths can take a long time.

I see no reason to keep this open until evidence proving contrary has been provided.

**Closed by zamar** 2016-02-08 00:34 UTC
