### ISSUE TITLE
Tablebase corruption leads to crash

### ISSUE THREAD

**Issue by LucyFair-TCEC** [official-stockfish/Stockfish#1911] opened 2018-12-29 06:23 UTC
someone in chat mentioned his observation and i checked on linux for comparison. if a 6men syzygy file is corrupt but needs to be used, stockfish crashes silently. that may have caused several crashes in TCEC Bonus tournament (where winblows is used).

**Comment by Hanamuke** [comment] 2018-12-29 10:32
I would say that it is on the user.

**Comment by snicolet** [comment] 2018-12-29 11:06
Is there any checksum signature inside the tablebase files themselves?

**Comment by snicolet** [comment] 2018-12-29 11:54
So maybe we could document somewhere (in the readme?) the commands that users can use to verify them. My point is that if even TCEC admins failed to notice that their files were corrupt, it means that the verification step is no-obvious.

**Comment by snicolet** [comment] 2018-12-29 11:56
@syzygy1 Any insight/advice on this subject?

**Comment by LucyFair-TCEC** [comment] 2018-12-29 17:59
Well, i myself did download those tablebases years ago and (ofc) did check them via md5sum command, since md5 verification files did exist. I just had to check ALL the files, including the ones with less than 6 men. (I still have those md5-files, in case they would be difficult to find. But with todays transfer rates allowing for a much faster download, this step might not even have crossed their mind.

BTW: Any verification inside StockFish would make it slower at some point in time, which is obviously undesirable, so i am with you on the entire issue, just wanted to make it public.

**Comment by rklrkl** [comment] 2018-12-30 14:38
A command inside Stockfish (i.e. that has to be run manually rather than being part of Stockfish's startup) that verifies the tablebases might be quite useful. This could be implemented by having the md5 checksums embedded in the Stockfish source (to avoid having to keep a seperate .md5 checksum file), including an md5sum checksum function in Stockfish and checksumming every possible tablebase file found (inc. 7-men don't forget!), reporting those that fail. This could take a while to run, so a nice feature might be a pre-scan to get the total byte size of all the tablebases so that an ETA to completion could be displayed.

If the built-in checksummer idea isn't taken up, then documentation on how to checksum the tablebases should be supplied with Stockfish. This gets messy on platforms that don't have an md5sum command though.

**Comment by NickolasReynolds** [comment] 2018-12-30 23:38
Would it be possible to modify the probing code without impacting performance such that Stockfish fails a tad more gracefully/informatively?

**Comment by syzygy1** [comment] 2018-12-31 00:18
There are internal checksum but it would take way too long to verify them on start up of the engine or on first access of a table.

It would be possible to add the checksum verification to Stockfish as a user command, but it seems better to leave this to an external tool (tbcheck).

One could look into making the code more robust against corrupted files, but one should keep in mind that corruption is caused by hardware errors and once there are hardware errors, there will be crashes.

**Comment by mcostalba** [comment] 2018-12-31 07:16
I agree with @syzygy1, the tool should be external, the tool is not a magic wand against hardware errors. 

SF assumes all its inputs (UCI commands, TB, fen strings, etc) are correct. This greatly simplifies the engine that can focus just on chess. IMO it is a safe assumption considering that an UCI engine is intended not to be interfaced directly by a human (if not for very simple testing/debugging).

**Comment by gvreuls** [comment] 2018-12-31 13:57
Just a question: would this still cause a silent crash if we enabled exceptions or would stockfish abend gracefully (we use `-fno-exceptions` in the Makefile)?

**Comment by Rocky640** [comment] 2018-12-31 17:02
I asked rcostheta (from TCEC) if he ran the md5 verification once he downloaded the files again. He said "there is no need to, the files downloaded without problem this time". Not a very careful guy.

**Comment by syzygy1** [comment] 2019-01-01 11:43
@Rocky640
and not very knowledgeable either

@gvreuls
C++ exceptions don't catch segfaults. Segfaults are undefined behaviour, so there is no standard C++ way to deal with them (as far as I'm aware).

At least on Linux segfaults can be caught by installing a signal handler, but it seems tricky to get that right (figuring out thst a segfault was caused by a corrupt TB file and recovering correctly), and I'm sure the SF maintainers wouldn't like such tricky platform specific solutions.

**Comment by vondele** [comment] 2019-01-02 08:12
my guess would be that most 'corruptions' are just incomplete downloads. If the tb files would contain their size in a header (I don't know if they do), I guess a simple size check on discovery would catch the common case error.

Other than that, I don't think the engine should e.g. compute the md5sum.

**Comment by syzygy1** [comment] 2019-01-03 16:11
@vondele 
Good idea. Unfortunately the tb file headers do not contain the file sizes.

However, the size of each tb file modulo 64 is 16, and that should catch the majority of the incompletely downloaded files.

**Comment by snicolet** [comment] 2019-01-04 15:16
Closing after https://github.com/official-stockfish/Stockfish/commit/bb843a00c1ef381162dc9c2491b5436b6cf5563f has been merged

**Closed** 2019-01-04 15:17 UTC
