### ISSUE TITLE
Stockfish 10 64 Bit crashes when analysing position

### ISSUE THREAD

**Issue by chofer32** [official-stockfish/Stockfish#2464] opened 2019-12-26 10:17 UTC
When analysing the position 
2r5/5p1k/p4b2/2Rp1pr1/1Pn1q3/2P3PP/P4P2/2RQ2K1 b KQkq - 0 1
and moving Rc5 on Scid stockfish crashes and Scid comes with the message "The analyse engine terminated without exit code"

![Screenshot_2019-12-26_stockfish10_64](https://user-images.githubusercontent.com/2420454/71471895-38a1d700-27d1-11ea-8b1f-68fa46c4a1bb.png)

**Comment by ianfab** [comment] 2019-12-26 10:33
The FEN is invalid, because it contains castling rights although the kings moved already, and on invalid input the behavior is undefined, which might include crashing. It is the responsibility of the GUI to validate the FEN/position.

**Comment by Rocky640** [comment] 2019-12-27 18:08
I confirm the issue with Scid, and also that without the bad castling rights there is no problem.
Other GUI, such as Arena, will clear the incorrect castling flags before passing the position to the chess engine.

"It is the responsibility of the GUI to validate the FEN/position."
Sure, but in Position& Position::set, at step # 4, we validate if en passant is a valid capture or not

It would not be much trouble to validate the castling rights as well.

For example, the following code could be used at step # 3 (line 269 to 304)
to clear any invalid castling rights in the fen.
The suggseted code also enforce the chess960 rule which is that in the starting position, the king must be placed on a square between the rooks.

```
 while ((ss >> token) && !isspace(token))
  {
      Square rsq;
      Color c = islower(token) ? BLACK : WHITE;
      Piece rook = make_piece(c, ROOK);

      token = char(toupper(token));

      // Bypass possibly wrong castling rights
      if (relative_rank(c, square<KING>(c)) != RANK_1) continue;
      File kf = file_of(square<KING>(c));
      if (!isChess960 && kf != FILE_E) continue;
      if (isChess960 && map_to_queenside(kf) == FILE_A) continue;

      if (token == 'K')
          for (rsq = relative_square(c, SQ_H1); piece_on(rsq) != rook && file_of(rsq) > (isChess960 ? kf + 1 : FILE_H); --rsq) {}

      else if (token == 'Q')
          for (rsq = relative_square(c, SQ_A1); piece_on(rsq) != rook && file_of(rsq) < (isChess960 ? kf - 1 : FILE_A); ++rsq) {}

      else if (token >= 'A' && token <= 'H')
          rsq = make_square(File(token - 'A'), relative_rank(c, RANK_1));

      else
          continue;

      if (piece_on(rsq) != rook) continue;

      set_castling_right(c, rsq);
  }
```

**Comment by MichaelB7** [comment] 2019-12-27 18:18
FYI for those that might not be familiar with Chess960  Castling rules

Rules for Castling in Chess960 (Fischer Random Chess)

Due to the different starting positions, castling in Fischer Random Chess
(FRC) might look quite complicated to a new player. The rules are actually
very easy to learn because they have not changed. So if you are familiar
with the castling rules for standard chess, you will be fine.

As in standard chess, Fischer Random chess960 allows each player to castle
once per game. After castling, the king and rook's final positions are
exactly the same as they would be in standard chess. Thus, after castling
a-side (known as 0-0-0 or* Queen-side castling* in standard chess), the
King lands on the c-file (c1 for White and c8 for Black) and the Rook is on
the d-file (d1 for White; d8 for Black). After castling h-side (known as
0-0 or* King-side castling*), the King lands on the g-file (g1/g8) and the
Rook on the f-file (f1/f8).

The rules for castling in FRC are the same as those in standard chess:

   1. Unmoved: The king and the castling rook must not have moved before in
   the game, including castling.
   2. Unattacked: All of the squares between the king's initial and final
   squares (including the initial and final squares) must not be under attack
   by any opposing piece.
   3. Vacant: All the squares between the king's initial and final squares
   (including the final square), and all of the squares between the rook's
   initial and final squares (including the final square), must be vacant
   except for the king and castling rook.

These rules have the following consequences:

   - If the initial position happens to be the standard chess initial
   position, these castling rules have exactly the same effect as the standard
   chess castling rules.
   - All the squares between the king and castling rook must be vacant.
   - Castling cannot capture any pieces.
   - The king and castling rook cannot "jump" over any pieces other than
   each other.
   - A player may castle at most once in a game.
   - If a player moves his king or both of his initial rooks without
   castling, he has lost the ability to castle for the rest of the game. If
   only one rook has been moved, the king may not castle using that rook, and
   thus may not castle to that side of the board.
   - In some FRC positions, it is possible to castle if the a, b, or h
   squares are occupied. This is because the king does not land on these
   squares after castling, nor does the king travel through them.
   - The king may not be in check before or after castling.
   - The king cannot move through check.

**Comment by MichaelB7** [comment] 2019-12-27 18:20
[deleted my post - it had nothing to with this issue]

**Comment by MichaelB7** [comment] 2019-12-27 18:26
I would rather see the engine exit , then have the engine assume it knows the correct FEN.  To me if there an error in the FEN, then the whole FEN is subject to scrutiny.  I do not believe that the GUI should be correcting error silently as well - follows the rule GIGO. It should crash as it requires the user to validate the FEN.  I'm old school, but that is the way it used to be.  Perhaps a better option for the GUI, is to note through a message popup what was wrong with the FEN and how the GUI fixed it.  But the engine should not be doing that.

**Comment by vdbergh** [comment] 2019-12-28 08:25
I thought being "old school" amounted to always handle invalid user input gracefully and certainly not crash. You don't want an assembler program to crash when passed invalid code. And certainly no one would accept the excuse that it is the responsibility of the C-compiler to invoke the assembler program with correct code.

But I realize I am in a very small minority here.

**Comment by MichaelB7** [comment] 2019-12-28 14:41
@vdbergh well, I'm not that old  ;>)  , I would be fine if SF self corrects and if prints an informational  warning informing to user that the FEN was corrected

**Comment by vondele** [comment] 2020-01-23 21:10
Since this is caused by an invalid FEN, and we currently accept valid input only, I'll close the issue.

I suspect full FEN validation is actually somewhat involved, so without seeing the code it is hard to judge if this is worth adding as a feature.

**Closed by vondele** 2020-01-23 21:10 UTC

**Comment by vdbergh** [comment] 2020-01-23 21:57
This is not so much fen validation as position validation. In other words is not about parsing the fen (which is relatively generic) but checking that the resulting board position is legal.

**Comment by vondele** [comment] 2020-01-23 22:02
yes, sure, the board represented by the fen is not valid... which kind of makes the fen invalid, right. Also syntactically invalid fens will cause trouble, of course.

**Comment by vdbergh** [comment] 2020-01-23 22:15
Well I don't know. The FEN syntax is relatively generic (it is used for all kinds of other variants as well). So in my mind this is not a syntax error but a higher level "semantic" error. But of course it is not black or white (it never is).

**Comment by snicolet** [comment] 2020-01-23 22:33
SF crashing in the presence of incorrect castling rights in fen is one of the most frequent issues we have to answer, and it has even lead Marco to include the subject in the wiki: https://github.com/glinscott/fishtest/wiki/Fishtest-faq#why-sf-crashes-on-incorrect-fen

I must admit that I am a bit less "extremist" than him and less convinced by the "a crashlog is an error message" motto, and that in fact I think that it would be nice to always avoid crashes, if possible.

But as he points out, it is a difficult subject because 

1) there is no obvious error reporting scheme in UCI. The best we could use, it seems, would be the `info string <message>` command.
http://talkchess.com/forum3/viewtopic.php?f=7&t=71617

2) as far as I know, there is no clear ordering for the `position FEN` command and the `switch to Chess960` command sent by GUI. So what should be do if we are in normal chess mode (`Chess960 = false`), then receive an invalid FEN with invalid castling rights, then receive the `Chess960 = true` command ?

**Comment by vdbergh** [comment] 2020-01-23 23:35
I think SF ignores illegal moves no? Why should it then not also just ignore an illegal fen? To help the user it could send an info string message which the GUI will then display I assume (otherwise what would be the purpose of "info string"?). I also think that as long UCI_960 is not set to true, SF should treat a fen as a fen for standard chess.
