### ISSUE TITLE
stockfish: child terminated with signal 11

### ISSUE THREAD

**Issue by Dialga** [official-stockfish/Stockfish#579] opened 2016-01-22 02:38 UTC
I'm unsure if this is caused by polyglot or stockfish, but I'll post here anyway just in case.

Requires xboard, stockfish and polyglot to be installed
Steps to reproduce:
1. xboard -fcp stockfish -fUCI -scp stockfish -sUCI
2. Edit > Edit Position
3. Move black king to e3
4. Mode > Two Machines

Result: POLYGLOT: pipex_exit(): stockfish child terminated with signal 11.

**Comment by MichaelB7** [comment] 2016-01-22 05:08
Not sure why you would start xboard via the command line? But using the xboard GU dos et ip the position and load two stockfishes, it plays fine:

[Event "Computer Chess Game"]
[Site "Mac-Pro.local"]
[Date "2016.01.21"]
[Round "-"]
[White "Stockfish 7"]
[Black "Stockfish 7"]
[Result "0-1"]
[TimeControl "12+0"]
[FEN "rnbqkbnr/pppppppp/8/8/8/4K3/PPPPPPPP/RNBQ1BNR w kq - 0 1"]
[SetUp "1"]

{--------------
r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . K . . .
P P P P P P P P
R N B Q . B N R
white to play
--------------}
1. f3 {-1.32/14} e5 {+1.18/13 0.2} 2. Kf2 {-1.27/14 0.4} d5 {+1.43/14 0.4}
3. e3 {-1.39/14 0.6} Bd6 {+1.41/14 0.3} 4. Nc3 {-1.22/14 0.2} Nf6
{+1.25/14 0.3} 5. d4 {-1.21/15 0.5} O-O {+1.28/14 0.1} 6. Nge2
{-1.26/15 0.4} Nc6 {+1.28/15 1.4} 7. Kg1 {-1.34/15 0.4} Re8 {+1.24/15 0.3}
8. a3 {-1.36/14 1.3} a6 {+1.25/14 0.3} 9. h3 {-1.22/14 0.2} h5
{+1.26/14 0.3} 10. Bd2 {-1.25/15 1.2} Ne7 {+1.14/14 0.4} 11. g4
{-1.32/14 0.3} Ng6 {+1.38/13 0.2} 12. Bg2 {-1.23/12 0.1} c6 {+1.42/14 0.4}
13. Qf1 {-1.24/14 0.5} exd4 {+1.28/13 0.4} 14. exd4 {-1.16/14 0.6} Bc7
{+1.20/14 0.4} 15. Re1 {-0.93/13 0.2} Bd7 {+0.86/14 0.7} 16. Bg5
{-0.89/15 0.5} Nf8 {+0.91/14 0.6} 17. Bd2 {-0.96/14 0.3} N6h7
{+0.87/14 0.3} 18. Nf4 {-0.75/13 0.2} Ne6 {+0.72/15 0.6} 19. Nxe6
{-0.98/14 0.5} Bxe6 {+0.79/15 0.5} 20. Qf2 {-0.91/15 0.3} Bd6
{+0.85/14 0.4} 21. f4 {-0.97/13 0.5} Qc7 {+0.89/14 0.2} 22. gxh5
{-0.54/13 0.2} Bf5 {+0.79/12 0.1} 23. Kh2 {-0.53/12 0.1} Rxe1
{+1.07/15 0.7} 24. Rxe1 {-0.47/13 0.4} Nf6 {+0.96/15 0.5} 25. Qh4
{-0.82/13 0.2} Be7 {+0.76/15 0.7} 26. Qf2 {-0.83/14 0.3} Bxc2
{+0.80/14 0.2} 27. Bc1 {-0.89/14 0.3} Bf5 {+0.97/13 0.1} 28. Re5
{-0.82/14 0.3} g6 {+0.97/14 0.3} 29. Qe3 {-0.60/14 0.2} Bf8 {+1.06/13 0.1}
30. Bf3 {-0.80/13 0.2} Nd7 {+0.88/15 0.3} 31. Rxf5 {-1.07/15 0.4} gxf5
{+0.87/13 0.1} 32. Qd3 {-1.09/15 0.2} Qd6 {+1.00/14 0.3} 33. Qxf5
{-1.12/13 0.2} Re8 {+1.25/14 0.2} 34. Qg4+ {-1.24/16 1.0} Kh8
{+1.30/16 0.4} 35. Qf5 {-1.29/16 0.9} Qe6 {+1.41/16 0.2} 36. Qxe6
{-1.43/15 0.1} fxe6 {+1.33/15 0.2} 37. Nd1 {-1.32/16 0.5} Nb6
{+1.62/15 0.5} 38. b3 {-1.50/14 0.2} Kg7 {+1.51/15 0.1} 39. Nf2
{-1.59/15 0.5} Nc8 {+1.63/15 0.1} 40. Nd3 {-1.53/13 0.1} Nd6 {+1.55/17 0.2}
41. Bg4 {-1.48/16 0.3} Nf5 {+1.43/16 0.2} 42. Kg2 {-1.46/13 0.1} Bd6
{+1.49/16 0.2} 43. Bb2 {-1.44/15 0.2} Kf6 {+1.39/16 0.5} 44. Kf3
{-1.42/14 0.1} a5 {+1.31/17 0.3} 45. a4 {-1.41/16 0.1} Rh8 {+1.43/17 0.3}
46. Bc3 {-1.38/16 0.3} Bb4 {+1.50/17 0.3} 47. Ba1 {-1.52/18 0.5} Rh7
{+1.39/16 0.2} 48. Bb2 {-1.56/15 0.2} b5 {+1.57/16 0.4} 49. Ba1
{-1.61/15 0.2} Rb7 {+1.60/16 0.3} 50. Ke2 {-1.61/14 0.1} Ng3+
{+1.63/16 0.8} 51. Ke3 {-1.60/14 0.1} bxa4 {+1.95/16 0.2} 52. bxa4
{-2.03/15 0.3} Rh7 {+2.04/14 0.1} 53. Nc5 {-2.12/16 0.2} Nxh5
{+2.17/16 0.1} 54. Bb2 {-1.97/16 0.2} Ng3 {+2.09/17 0.2} 55. Kd3
{-2.09/17 0.2} Re7 {+2.17/17 0.2} 56. Kc2 {-2.17/16 0.3} Nf5 {+2.12/16 0.1}
57. Kd3 {-2.08/17 0.3} Nd6 {+1.97/17 0.2} 58. Ba1 {-2.18/18 0.2} Kf7
{+2.17/17 0.6} 59. Bh5+ {-2.11/16 0.2} Kf8 {+2.29/19 0.8} 60. Bg6
{-2.17/16 0.3} Nb7 {+2.46/15 0.1} 61. Ke2 {-2.40/14 0.1} Nxc5
{+2.56/15 0.2} 62. dxc5 {-2.48/15 0.1} Bxc5 {+2.65/12 0.1} 63. h4
{-2.57/15 0.1} Bd6 {+2.86/16 0.4} 64. Bf6 {-2.60/14 0.1} Rb7 {+2.91/13 0.1}
65. Bc3 {-2.98/14 0.3} Bxf4 {+3.24/14 0.1} 66. Bxa5 {-3.02/14 0.2} c5
{+3.29/14 0.2} 67. Be1 {-3.27/15 0.3} Rb3 {+3.52/14 0.2} 68. Bf2
{-3.78/15 0.5} Kg7 {+3.91/14 0.2} 69. h5 {-4.05/15 0.5} d4 {+4.31/15 0.2}
70. a5 {-4.31/15 0.2} Ra3 {+4.37/14 0.1} 71. a6 {-4.31/13 0.1} Rxa6
{+4.44/15 0.1} 72. Kd3 {-4.45/16 0.2} Ra3+ {+4.66/16 0.1} 73. Ke4
{-4.51/15 0.1} Bd6 {+4.79/18 0.2} 74. Bxd4+ {-4.56/17 0.1} cxd4
{+5.32/16 0.3} 75. Kxd4 {-4.98/16 0.2} Rh3 {+5.37/14 0.1} 76. Be8
{-6.24/16 0.4} Kh6 {+10.20/16 0.3} 77. Kc4 {-8.76/15 0.2} Rxh5
{+12.55/16 0.2} 78. Bd7 {-47.27/17 0.4} e5 {+53.80/17 0.2} 79. Be8
{-123.44/19 0.5} Rh4+ {+123.45/19 0.2} 80. Kd3 {-123.46/22 0.1} e4+
{+123.46/19 0.1} 81. Ke2 {-123.47/23 0.1} Rh2+ {+123.48/25 0.1} 82. Ke3
{-123.48/24 0.1} Kg5 {+123.49/26 0.1} 83. Kd4 {-123.50/25 0.1} e3
{+123.50/26 0.1} 84. Bb5 {-123.50/24 0.1} e2 {+123.51/24 0.2} 85. Bc6
{-123.51/22 0.2} e1=Q {+99.89/24 0.1} 86. Bg2 {-99.88/22 0.1} Bb4
{+99.91/25 0.1} 87. Kd5 {-99.92/30 0.1} Qc3 {+99.93/38 0.1} 88. Bf1
{-99.94/51 0.1} Rh4 {+99.95/126 0.1} 89. Be2 {-99.96/127 0.1} Qc5+
{+99.97/127 0.1} 90. Ke6 {-99.98/1 0.1} Qf5# {+99.99/127 0.1}
{Xboard adjudication: Checkmate} 0-1

The error sig 11 is a memory fault - one of the programs accessed a memory location that was not assigned to it.   If it is reproducible, compile and link with -g, and then run it with lldb which should show exactly where it is crashing...

**Comment by zamar** [comment] 2016-01-22 07:49
It sounds like XBoard bug. If you move black king to e3, the position is illegal. XBoard shouldn't send the position to engines.

**Comment by zamar** [comment] 2016-01-23 16:52
I could reproduce this, but the problem is that xboard send an illegal position to polyglot/Stockfish.

I'm closing this bug report, but the correct action would be to raise a bug against xboard.

**Closed by zamar** 2016-01-23 16:52 UTC
