### ISSUE TITLE
 Buggy winning material eval (2 same colour bishops) 

### ISSUE THREAD

**Issue by Vinvin20** [official-stockfish/Stockfish#576] opened 2016-01-19 09:44 UTC
SF (gives a winning score to this position because it thinks that g1=B?? wins 
(Without Syzygy, but we could probably find side effects with Syzygy too.)
8/8/3k4/8/8/7K/6pP/4b3 b - - 1 4

See details here : http://www.talkchess.com/forum/viewtopic.php?t=58952

**Comment by lucasart** [comment] 2016-01-19 12:06
There is no bug:
* g1=Q or g1=R: stalemate.
* g1=N+: draw (because Kg2 Ne2 Kf1, picks-up a piece).
* g1=B: draw (because KBBKP with wrong color bishops).
* not promoting loses the pawn and is also a draw.

So, whatever black plays, this position is drawn. SF does not play a move that results in the wrong game result (ie. loss instead of draw). So it is only cosmetic, and not a bug.

If every drawn position where SF does not report a 0.00 score was considered a bug, then there are more bugs in SF than atoms in the universe...

**Comment by Vinvin20** [comment] 2016-01-19 13:33
As you don't understand, here's the bug : Stockfish plays Rxd2 because it thinks that play Re1 is losing (buggy because the endgame with 2 Bs same colour is draw).
28/59	00:24	 140.999k	5.675k	-5,56	1.Rd8+ Kg7 2.Rxd2 g1Q+ 3.Kf3 Kf7 4.Rg2 Qf1+
28/59	00:24	 140.999k	5.675k	-5,56	1.Kf3 g1Q 2.Rxd2 Kf7 3.Rg2 Qf1+ 4.Kg3 Kg6 5
29/59	00:24	 140.999k	5.675k	-5,56	1.Rxd2 g1Q+ 2.Kf3 Kf7 3.Rg2 Qf1+ 4.Kg3 Kg6

**Comment by MichaelB7** [comment] 2016-01-19 14:45
Ok - I'll bite - copy and paste the fen you posted and tell us how white plays Re1?

**Comment by Vinvin20** [comment] 2016-01-19 15:26
It's in the first link I posted (the solution):

[Event "-"]
[Site "-"]
[Date "2016.01.18"]
[Round "?"]
[White "W"]
[Black "B"]
[Result "1/2-1/2"]
[SetUp "1"]
[FEN "5k2/8/8/3R4/6K1/8/3b2pP/8 w - - 0 1"]

1. Rf5 Ke7 2. Re5 Kd6 3. Re1 Bxe1 4. Kh3 
1/2-1/2

**Comment by MichaelB7** [comment] 2016-01-19 15:54
Got it - white has a force draw , but doesn't see it (without egtb).  I'm assuming it will see  the draw with egtb?  Not at the computer right now to check.

**Comment by lucasart** [comment] 2016-01-20 04:29
If you want to get attention from developpers, you need to be precise:
* in the initial position you posted, there is no Rook.
* then you talk about another position where SF does not see the correct move Re1.
* then you show the solution, which is now Rf5 ?

Make less noise describe things precisely and provide minimal reproduction steps (UCI commands to pass to SF). Once you are able to do that, we can start looking at it. And we will tell you if its a bug or not, and whether we're going to do something about it or not.

**Comment by ajithcj** [comment] 2016-01-20 08:20
@lucasart, pls look at the talkchess link provided and the subsequent posts. Its pretty clear what he's talking about.
Also, it was Joona who asked Vinvin20 to raise this as a bug on the forum.

**Comment by zamar** [comment] 2016-01-20 21:43
I've checked the position and code, and there is no bug.

The fact that Stockfish misevaluates some positions doesn't necessarily mean that there is a bug... So I plan to close this issue shortly...

**Comment by Vinvin20** [comment] 2016-01-20 23:00
It's a big error in the evaluation. 
It's the same thing as : don't support underpromotion or claim a draw after 2 repetitions.
Those are not bugs but problems.

**Comment by MichaelB7** [comment] 2016-01-21 00:33
I see it as a "nice to have".   If one allows EGTB is a crucial tool  to obtain correct evaluations in a endgame position , why then are we saying SF must get the evaluation correct without EGTB?  Was that not the main point  of adding EGTB in the first place? The tricky part is how do you add the correct code , without making SF slower or cause a mis-evaluation in a similar yet different position? Then consider that EGTB "gets" you there ( I.e. , correct evaluation) why are we even talking about this? I appreciate the fact that this drives some people nuts,  but their agenda is different than ours - we want the engine that plays the best and why spend time , effort and resources on issue that at most , will gain  less than 1 ELO and probably less than that even.  Just my $.02.

Ps - I would love to see this fixed with minimal effort and resources, but I don't see that happening.   To get it right , will probably be a little more intense that what some people think.

**Comment by zamar** [comment] 2016-01-21 09:13
@Vinvin20: It's not a same thing.

There are millions of positions that Stockfish misevaluates badly for various reasons.

It's a design choice that we do not focus on special cases, but try to write a program that plays excellent chess on average.

On the other hand, if there are elegant fixes for special cases, I'm not against implementing them. But in any case, this is not a bug.

Issue closed.

**Closed by zamar** 2016-01-21 09:13 UTC

**Comment by mcostalba** [comment] 2016-01-21 16:48
I think we can close this: newer gcc has the issue fixed.

**Comment by Vinvin20** [comment] 2016-01-21 18:17
@MichaelB7  and @zamar same thing for underpromotions :
Less than 1 Elo, special case, ...

Thanks to all !

**Comment by zamar** [comment] 2016-01-21 18:50
@Vinvin20: If you can't understand the difference between a generic feature (like under promotions) and a very specific mis-evaluation problem never occuring in real games, then I can't help you.

Issue closed.

**Comment by Vinvin20** [comment] 2016-01-21 19:07
@ zamar  "never occuring in real games" <- probably it's you who don't understand.
In 1991, Lachex didn't compute underpromotion because it "never occuring in real games".
https://chessprogramming.wikispaces.com/ACM+1991#Knight%20Promotion
After this game, the underpromotion were appended to Lachex.

**Comment by mcostalba** [comment] 2016-01-21 19:48
Underpromotions are part of the chess rules. Your case is conceptually
different.

**Comment by Vinvin20** [comment] 2016-01-22 00:09
3-fold repetition is part of the chess rules too, despite this fast, Stockfish continues to erroneously claim 0.00 after 2 times the same position.

**Comment by mcostalba** [comment] 2016-01-22 06:09
This is really off topic, you are just making useless arguments, not
related with this issue.
