### ISSUE TITLE
Buggy test 512*32

### ISSUE THREAD

**Issue by JojoM-sf** [official-stockfish/Stockfish#3211] opened 2020-11-01 14:52 UTC
In [SPSA tune_512x32](https://tests.stockfishchess.org/tests/view/5f9a0d376a2c112b60691c12), I do get all sorts of different errors. Output looks like this:

`Warning: Start index larger than book size, wrapping after 150932.`
`Warning: Engine New-88cc6db563(0): no response to ping`
`Terminating process of engine New-88cc6db563(0)`
`Warning: Engine New-88cc6db563(4): no response to ping`
`Terminating process of engine New-88cc6db563(4)`
`Warning: Engine Base-88cc6db563(6): no response to ping`
`Terminating process of engine Base-88cc6db563(6)`
`Warning: Unexpected result claim from New-88cc6db563: 1/2-1/2 {Draw by stalled connection}`
`Finished game 1 (New-88cc6db563 vs Base-88cc6db563): * {No result}`
`Score of New-88cc6db563 vs Base-88cc6db563: 0 - 0 - 0  [nan] 0`
`Warning: Unexpected result claim from Base-88cc6db563: 1/2-1/2 {Draw by stalled connection}`

**Comment by gvreuls** [comment] 2020-11-01 15:33
I've reported this also, see the comments on 55da154484

**Comment by vondele** [comment] 2020-11-01 15:40
@SFisGOD ?

**Comment by vondele** [comment] 2020-11-01 15:53
The problem is the branch compiles in about >16000 UCI parameters even if there are only 128 used. Setting just 128 options takes about 8.5s on my machine, and that's also the time it takes to reply to a readyok command, so the engine gets timed out. 

test with `./stockfish < inp2.txt`
[inp2.txt](https://github.com/official-stockfish/Stockfish/files/5471227/inp2.tx

@SFisGOD this needs to be fixed by making only a part of the array tunable, not the full one.

**Comment by JojoM-sf** [comment] 2020-11-01 15:55
I hope this behaviour does not render the test results completely invalid?

**Comment by SFisGOD** [comment] 2020-11-01 16:14
@vondele I stopped the test. 

> this needs to be fixed by making only a part of the array tunable, not the full one.

Yes, I should have done that.

**Comment by vondele** [comment] 2020-11-01 16:25
OK, thanks.

**Closed by vondele** 2020-11-01 16:25 UTC
