### ISSUE TITLE
Mate 0 without upperbound - is this logical?

### ISSUE THREAD

**Issue by jackalsh** [official-stockfish/Stockfish#1056] opened 2017-04-04 21:47 UTC
I use Stockfish for massive calculations and met very strange behaviour, probably a bug.
Let's examine FEN position: **8/8/8/5K2/1r3p2/6k1/R7/8 w - - 4 75** 

Using official engine 8 for Linux [downloaded from official site](https://stockfish.s3.amazonaws.com/stockfish-8-linux.zip).

To see this behaviour yourself please run code [https://gist.github.com/jackalsh/793a61ece2d25d39bdd17814d79e7ff1](https://gist.github.com/jackalsh/793a61ece2d25d39bdd17814d79e7ff1) and wait until exception. Usually several minutes are enough.

Root case:
From Arena log:
```
2017-04-05 00:53:57.489-->1:stop
2017-04-05 00:53:57.491<--1:info depth 13 seldepth 31 multipv 1 score cp -1141 nodes 577762 nps 3877597 tbhits 0 time 149 pv a2a1 f4f3 f5e6 g3g2 a1a2 f3f2 e6d6 b4f4 a2c2 g2g1 c2c3 f4f6 d6c5 f2f1q c3c4 f1f5 c5d4 g1g2 d4c3
2017-04-05 00:53:57.492<--1:info depth 12 seldepth 31 multipv 2 score mate 0 nodes 577762 nps 3877597 tbhits 0 time 149 pv a2a8 f4f3 a8g8 g3h3 g8h8 h3g2 h8g8 g2f1 f5g5 f3f2 g5h5 f1e2 g8e8 e2f3 e8e7 b4b5 h5h6 f2f1q e7f7 f3g2 f7g7 g2h3 g7f7 f1d3 h6g7
2017-04-05 00:53:57.493<--1:bestmove a2a1 ponder f4f3
```

As you see from here, multipv 2 is set to mate 0. There is no chance this is logical. This can not be upperbound cut, because upperbound lexem is not here. I expect to see **mate 0 upperbound** but this is not the case.

I can work around this, but you better see and try to fix it.

**Comment by jackalsh** [comment] 2017-04-04 21:54
This is a duplicate of #502.

**Comment by joergoster** [comment] 2017-04-06 17:37
@jackalsh I just pushed a fix here: https://github.com/joergoster/Stockfish/tree/issue502
This should avoid outputting mate 0 scores at all. Can you please try it?

**Comment by zamar** [comment] 2017-04-08 00:10
Closing as duplicate of #502.

**Closed by zamar** 2017-04-08 00:10 UTC
